### ISSUE TITLE
Cannot test Firefox from Dex on Linux

### ISSUE THREAD

**Issue by gogo9th** [sitespeedio/browsertime#1004]
Hi,
 
I'm trying to run browsertime from Dex on Linux (Android phone), but if I test firefox, I get the following error:

:expose_runner/chrome-experiment-result$ browsertime -b firefox https://www.google.com
:expose_runner/chrome-experiment-result$ cd ..
:dextop/expose_runner$ nodejs node_modules/browsertime/bin/browsertime -b firefox https://www.google.com
[2019-12-01 23:25:44] INFO: Running tests using Firefox - 3 iteration(s)
(node:10632) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 2
    at earlyTermination.catch.e (/home/dextop/expose_runner/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:10632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I wonder if there is any way to get around this error.

**Comment by soulgalore** [comment]
Hi @gogo9th you are running on Android did I get that right? The latest Geckodriver should support that, but when I tested I couldn't get it to work, I wonder if there's something missing in how we configure it. When I looked at the release notes I could find an example (like full example)  if you can find that it would really help!

Best
Peter

**Comment by gogo9th** [comment]
Hi Peter,

Thanks for the note. I couldn't get it working yet, but if I ever succeed, I will let you know. Thanks.

**Comment by soulgalore** [comment]
@gogo9th did you try with the options of "Support for Firefox on Android" https://github.com/mozilla/geckodriver/releases ?

**Comment by soulgalore** [comment]
Closing this since I locally can run the tests on Firefox on Android.
