### ISSUE TITLE
Collect metrics also on timeout for pageCompleteCheck

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#101]
Today we wait on <code>window.performance.timing.loadEventEnd</code> + 2 seconds before we collect metrics. But if the loadEventEnd never happens, the test timeouts (think we have 60s right now) and no metrics is collected. Would be cool to collect metrics even when it timeouts.

I have one URL that fails today that we can use for test:
https://www.ryanair.com/gb/en/

**Comment by tobli** [comment]
Yep, this is a good idea. However I think the process exit code should still be non zero, since there's no good way to tell if the collected values were "good enough" or not.

**Comment by soulgalore** [comment]
This will be kind of fixed by https://github.com/sitespeedio/browsertime/issues/186 let us close this one.
