### ISSUE TITLE
How to pass browser preference value that contains colon

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#1018]
One of my preferences to pass to the flag `--firefox.preference` has the form of: `value`:`https://abc.com/api.html`. Apparently, this will cause this error:

> `ERROR: Firefox preferences 'value':'https:/abc.com/api.html' need to of the format key:value, preference was not set`

Can someone please tell me how could I pass a url-like value to `--firefox.preference`.
Thank you!

**Comment by soulgalore** [comment]
I think we don't handle that. Can you share what preference so I can have a look?

**Comment by phongiswindy** [comment]
@soulgalore The firefox preference I am trying to pass is `'network.trr.uri'` which is followed by a URL value. So doesn't it mean Browesertime currently only support preferences that take only Boolean value?

**Comment by soulgalore** [comment]
This will go out in the coming 8.0.0. I'll try to release that when Chrome 80 becomes stable.
