### ISSUE TITLE
How to properly pass customized firefox binary to `--firefox.binaryPath`

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#1023]
I have a customized firefox built from [gecko](https://github.com/mozilla/gecko-dev) using [mach](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation) on Ubuntu. The building process provides me with a directory `../obj-x86_64-pc-linux-gnu/dist/bin` which contains the binary file of firefox and related library files. Can some one please tell me how I can point the `--firefox.binaryPath` to this custom-built firefox. 

What I have done is to copy the whole `bin` directory of firefox to where I am currently running the `docker` command with these 2 flags `-v $(pwd):/browsertime` and `--firefox.binaryPath "/browsertime/bin/firefox"`. However, I got these errors:

> Google Chrome 78.0.3904.108 
> Mozilla Firefox 71.0
> [2019-12-11 03:20:31] INFO: Running tests using Firefox - 1 iteration(s)
> [2019-12-11 03:20:32] INFO: Browser failed to start, trying 2 more time(s): invalid argument: can't kill an exited process
> [2019-12-11 03:20:33] INFO: Browser failed to start, trying 1 more time(s): invalid argument: can't kill an exited process
> [2019-12-11 03:20:34] ERROR: BrowserError: Could not start the browser with 3 tries
>     at SeleniumRunner.start (/usr/src/app/lib/core/seleniumRunner.js:85:13)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> [2019-12-11 03:20:34] ERROR: No data to collect
> [2019-12-11 03:20:34] INFO: Browser failed to start, trying 0 more time(s): invalid argument: can't kill an exited process
> [2019-12-11 03:20:34] INFO: Wrote data to browsertime-results/youtube.com/2019-12-11T032031+0000

Thank you for your help!

**Comment by soulgalore** [comment]
Hi @phongiswindy ok, so I see from the log that it at least have the right path (else it would tell you that). Can you check that the bin file has the right permissions to execute? Else I'm not sure what's  causing it. You could try with Nightly or Beta just to see if its a thing with the built or if its a generic failure.

**Comment by phongiswindy** [comment]
@soulgalore, thank you so much for the confirmation that the path I passed is correct. The problem was indeed because of the permission to execute!
