### ISSUE TITLE
Refactor gecko profiler code in iteration

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1065]
We should move https://github.com/sitespeedio/browsertime/blob/master/lib/core/engine/iteration.js#L232-L285 to somewhere in Firefox, it could probably be moved to onStopIteration

**Comment by ncalexan** [comment]
In fact, this whole approach is not great: we can get the profile data over the wire (using Firefox privileged JS) rather than off the device disk, which is strictly more versatile.  I have some WIP in this direction; as I get back to work I should be able to push it up.

**Comment by soulgalore** [comment]
I just moved the code so its is under Firefox instead, that will make the iteration blob easier to follow, then we can take it from wire again (if there's no penalty for doing that).

**Comment by soulgalore** [comment]
This is OK for now.
