### ISSUE TITLE
Failed to decode response from marionette

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1066]
On the one of the test servers we get errors like: **Failed to decode response from marionette** when we use geckoProfiler and windowRecorder.

URLs that failed:
https://wikimediafoundation.org
https://us.yahoo.com/

But I'm not sure the URL is the reason, let me see if I can reproduce.

**Comment by soulgalore** [comment]
This is a memory issue on the server. Upgrading to a larger instance fixed the problem.

**Comment by ncalexan** [comment]
> This is a memory issue on the server. Upgrading to a larger instance fixed the problem.

For what it's worth, I have seen this locally in situations that are unlikely to be OOM.  I have no theory at this time.

**Comment by soulgalore** [comment]
Aha ok. I could see on the test server that the issue went away when upgrading to more memory but I guess then it can be multiple causes.
