### ISSUE TITLE
newStart for doing removeOrange is not correct. 

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1093]
I think the `newStart` variable defined [here](https://github.com/sitespeedio/browsertime/blob/master/lib/video/postprocessing/finetune/index.js#L21) needs to be adjusted. 

I did a few tests and this was what I saw
newStart is `1.723` and video starts at `1.722400`
newStart is `1.813` and video starts at `1.812278`

And later when we execute the ffmpeg command which cuts the video to remove the orange frame,  ~~an extra orange will be created, which causes the start of the output video is one frame off.~~. Some miss alignment happened to the frames, which caused the output became one frame off

**Comment by soulgalore** [comment]
Hi @sefeng211 aha thanks. Do you have time to give it a try to fix it? Else I can have a look later on, I'm in the middle of verifying that all base functionality is working, when I'm done with that I can look at other things.

**Comment by sefeng211** [comment]
Sure, I can try to fix it. In the meantime, I am also investigating other issues such as why the timestamp-overlay added video misses some frames (passing `-vsync 0` seems fix, however the timestamp overlay doesn't match the timestamp of the video)

**Comment by sefeng211** [comment]
Closing this off as the patch is merged.
