### ISSUE TITLE
Window recorder don't work on Android

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1098]
`bin/browsertime.js -b firefox -n 1 https://www.sitespeed.io --skipHar --video --firefox.windowRecorder --android --visualMetrics`

gives 
```
[2020-01-11 07:52:56] ERROR: Could not find window recording directory in /Users/peter/git/browsertime/browsertime-results/www.sitespeed.io/2020-01-11T075236+0100
[2020-01-11 07:52:56] ERROR: TypeError: Cannot read property 'substr' of undefined
    at findRecordingStartTime (/Users/peter/git/browsertime/lib/video/screenRecording/firefox/firefoxWindowRecorder.js:63:23)
    at FirefoxWindowRecorder.stop (/Users/peter/git/browsertime/lib/video/screenRecording/firefox/firefoxWindowRecorder.js:195:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I wonder if something went wrong in my refactor? However I cannot see where we set the folder name on the android device, let me have a look tonight.

**Comment by soulgalore** [comment]
I think the problem is that we set _layers.windowrecording.path_ wrong on Android, let me try to fix that tonight.

**Comment by soulgalore** [comment]
I fixed the missing path on Android but there still something that is wrong. There's no png files created on the phone, but I can see that the directory _windowrecording-20200111232630_ is created?

**Comment by ncalexan** [comment]
> I fixed the missing path on Android but there still something that is wrong. There's no png files created on the phone, but I can see that the directory _windowrecording-20200111232630_ is created? I'm using 68.4.1 (that should work right?).

My guess is that the async-without-a-Promise nature in 68 is biting here: see https://bugzilla.mozilla.org/show_bug.cgi?id=1581240, which didn't land until 72.  Not sure if browsertime is even using the API that should save the day... in any case, this needs an arbitrary wait, and the wait can be long for long page loads.

**Comment by soulgalore** [comment]
Aha ok! I tried adding some more wait time but didn't get it to work but could be I added it on the wrong place, So what do you think, should we release without it? What version of Firefox do you run in your environment?

**Comment by soulgalore** [comment]
Thus works now in latest FF.
