### ISSUE TITLE
Teach browsertime about brand new `--firefox.env` option for setting environment variables

### ISSUE THREAD

**Issue by ncalexan** [sitespeedio/browsertime#1109]
Cutting edge (re, trunk) `geckodriver` builds will support configuring the runtime environment, including on Android, now that I've implemented https://bugzilla.mozilla.org/show_bug.cgi?id=1607960.  This ticket tracks exposing `--firefox.env` as part of browsertime, just like we can set `--firefox.prefs`, etc.

There's not (yet) support for this in `selenium-webdriver`, so this will be another "side-around".

**Comment by soulgalore** [comment]
This has been fixed.
