### ISSUE TITLE
Firefox on Android is not closing when finished

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1120]
On my Moto G5 Firefos opens but is never closed after a test run.

Upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1298921

**Comment by ncalexan** [comment]
This should be addressed in Fennec 68 when it is next released.  By my calculations, the patch didn't make 68.4.1 (https://archive.mozilla.org/pub/mobile/releases/68.4.1/, released Jan 8, 2020) but should make 68.4.2.

**Comment by ncalexan** [comment]
Looks like 68.4.2 was cut today (Jan 17, 2020) and includes the change: https://hg.mozilla.org/releases/mozilla-esr68/shortlog/e215d711213984716b1c44db7d1254397de6ef4b includes https://hg.mozilla.org/releases/mozilla-esr68/rev/47aae290cc07a7c24a7e38bbc8e603aa66f14663.

**Comment by soulgalore** [comment]
Great, thank you @ncalexan for investigating!

**Comment by soulgalore** [comment]
This has been released and fixed upstream.
