### ISSUE TITLE
Consider normalizing videos from VFR to CFR before any video transformation. 

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1123]
Android adb screen recorder records the video in variable frame rates and users are not allowed to adjust. 

Using ffmpeg to do operations on VFR videos would mess the timestamps up. 

I think we should consider to always convert VFR videos to CFR (60 FPS for example) before any video transformation. For example, before removing the orange frame. This also fixes #1108

**Comment by soulgalore** [comment]
@sefeng211 you are right., We actually used to convert it to 60fps but is seems to have disappeared through the year, let me dig into the history. I'll ping you when I find it and consult you if it is the right way to do it!

**Comment by soulgalore** [comment]
I removed it in 7737807ca1f67b10b2fe12bd0037d244ad9b728d but no good comment. I can re-add it this weekend, @sefeng211 do the old convert look good or did you think of something else?

**Comment by sefeng211** [comment]
@soulgalore Thanks, it looks good :)

**Comment by sefeng211** [comment]
Oh one thing is, this old conversion does the conversion right away, even before calculating visual metrics. I was thinking still to use the original video(VFR) for visual metrics calculation, and we convert it after that.

**Comment by sefeng211** [comment]
It does change the visual metrics number a little bit, not a lot though, just a tiny bit of changes. However, since there are no evidence that shows the visual metrics numbers are wrong, I think we should keep using the original video to do visual comparisons, and convert it afterwards. What do you think @soulgalore ?

**Comment by soulgalore** [comment]
Let me do branch tonight and we can have look what it looks like!

**Comment by soulgalore** [comment]
Added a PR, but it seems it still off, I could see that first visual change metric isn't added exactly when it happens in the video.

**Comment by sefeng211** [comment]
Hmm, Let me try to reproduce it.

**Comment by sefeng211** [comment]
@soulgalore First Visual Change seems correct me. What was the issue?

**Comment by soulgalore** [comment]
This was fixed right?
