### ISSUE TITLE
Firefox on Android with WebRender needs a hack for visual metrics to work correctly 

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1164]
This is the tracking bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1606365 
This is the hack we merged in `mozilla/browsertime`: https://github.com/mozilla/browsertime/pull/60

TLDR is if you have WebRender enabled, Visual metrics numbers are incorrect. 

Honestly, I'd love to see we fix the original bug instead of having this hack every where, however I am not sure when that will happen. 

Let me know if you want this hack as well :)

**Comment by soulgalore** [comment]
If it makes your life easier @sefeng211 , please add it here too :)

**Comment by soulgalore** [comment]
Closing since in the upstream issue it seems to be a non issue.
