### ISSUE TITLE
TSProxy is broken in Browsertime 8.0

### ISSUE THREAD

**Issue by kenrick95** [sitespeedio/browsertime#1168]
I tried the new Sitespeed 12.0 (which uses Browsertime 8.0) and it was broken due to me using connectivity throttling using TSProxy (other engines are fine).

```
[2020-02-07 11:05:31] DEBUG: [browsertime] Running with options: {
  "scripts": [],
  "iterations": 3,
  "delay": 0,
  "videoParams": {},
  "statistics": true,
  "browser": "chrome",
  "connectivity": {
    "profile": "3g",
    "engine": "tsproxy"
  },
  "screenshot": true,
  "screenshotParams": {
    "type": "png",
    "png": {
      "compressionLevel": 6
    },
    "jpg": {
      "quality": 80
    },
    "maxSize": 2000
  },
  "viewPort": "360x640",
  "xvfbParams": {
    "display": 99
  },
  "chrome": {
    "CPUThrottlingRate": 5,
    "collectConsoleLog": true,
    "enableTraceScreenshots": true,
    "mobileEmulation": {
      "deviceName": "iPhone 6"
    }
  },
  "verbose": 3,
  "mobile": true,
  "screenshotType": "png",
  "coach": true
}
[2020-02-07 11:05:31] INFO: [browsertime.connectivity.tsproxy] Start TSProxy:/PROJECT/node_modules/browsertime/vendor/tsproxy.py --rtt  --inkbps  --outkbps  -p 1080 -vvvv
[2020-02-07 11:05:32] VERBOSE: [browsertime.connectivity.tsproxy] usage: tsproxy [-h] [-v] [--logfile LOGFILE] [-b BIND] [-p PORT] [-r RTT]
               [-i INKBPS] [-o OUTKBPS] [-w WINDOW] [-d DESTHOST]
               [-m MAPPORTS] [-l] [-n] [-f]
[2020-02-07 11:05:32] VERBOSE: [browsertime.connectivity.tsproxy] tsproxy: error: argument -r/--rtt: invalid float value: 'undefined'
```

I traced the error back to this Pull Request: #1160 which renames latency to rtt, but unfortunately the changes did not propagate to the TSProxy codes.

I believe if we made these field renames in https://github.com/sitespeedio/browsertime/blob/631620a433619b71257b240240a96cc7a486203d/lib/connectivity/tsProxy.js, it will work again.

Thanks

P.S. These are what I think the required changes:

- https://github.com/sitespeedio/browsertime/blob/631620a433619b71257b240240a96cc7a486203d/lib/connectivity/tsProxy.js#L39
  should be renamed to `profile.rtt`
- https://github.com/sitespeedio/browsertime/blob/631620a433619b71257b240240a96cc7a486203d/lib/connectivity/tsProxy.js#L41
  should be renamed to `profile.down`
- https://github.com/sitespeedio/browsertime/blob/631620a433619b71257b240240a96cc7a486203d/lib/connectivity/tsProxy.js#L43
  should be renamed to `profile.up`

**Comment by soulgalore** [comment]
Ooops I missed that, thank you @kenrick95 for fixing it! We have test in travis but I guess it doesn't propagate the error correctly. Let me do a fix release ASAP.

**Comment by soulgalore** [comment]
I'll keep this open until you verified @kenrick95 !

Thank you again for reporting AND  fixing the issue, that rarely happens :)

**Comment by kenrick95** [comment]
Verified working~ Thanks a lot!

P.S.: [webcoach](https://www.npmjs.com/package/webcoach) package also need a new version as it depends on [browsertime@8.0.0](https://github.com/sitespeedio/coach/blob/master/package.json#L81)

**Comment by soulgalore** [comment]
Yeah I'll update that but do people set connectivity when running the Coach? The score will not change depending on connectivity, I should make that more clear in the docs.

**Comment by kenrick95** [comment]
Hmm I'm not really sure about that.

I noticed this versioning issue because the resulting yarn.lock in my project (which depends on sitespeed.io npm package) have both browsertime@8.0.0 and browsertime@8.0.1

**Comment by soulgalore** [comment]
Ah I see! I'll fix it asap when I get a chance.
