### ISSUE TITLE
Error running browsertime due to missing output directory

### ISSUE THREAD

**Issue by dpalmeiro** [sitespeedio/browsertime#1208]
Running this simple command results in a missing directory error:

```
denis@denis-xps:/tmp$ node ~/src/browsertime/bin/browsertime.js -n 1 https://www.reddit.com
[2020-02-26 10:48:07] ERROR: Error running browsertime Error: ENOENT: no such file or directory, mkdir '/tmp/browsertime-results/www.reddit.com/2020-02-26T104807-0500''
```
This was using 52121ec7af3583987ba1ec58ba8796e49762b7c6 on Linux Mint 19.

**Comment by dpalmeiro** [comment]
This works with node v10.  I'm not sure if v10 is now required, but perhaps a warning message is necessary since some distros may not be up to v10 yet.

**Comment by gmierz** [comment]
Yup, node v10+ is required for Browsertime and I agree it would be great to have a warning message about this.

I wonder if having a .nvmrc file would help with this.

**Comment by soulgalore** [comment]
Yeah sorry I introduced this when I changed to how we use mkdir directly from fs (instead of mkdirp). Actually we always only actively supported LTS (12.x now), but that isn't reflected in the package.json (10.13) but we don't have the  .nvmrc file that you pointed out @gmierz so we should add that.

**Comment by soulgalore** [comment]
I added a PR for check in the CLI, I think that's the safest way to do the check independent of what tools you use to install.

**Comment by soulgalore** [comment]
If you are running < 10 you get a error in the cli, I think that is enough for now,
