### ISSUE TITLE
Firefox HAR include requests that are from the local cache

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#121]
Ok, in Firefox network, all responses (even though they are from the local cache) is 304. When we get the HAR using the export plugin, the all responses are 200 OK, but the times are 0 ms. 

<img width="1107" alt="screen shot 2016-03-10 at 09 11 50" src="https://cloud.githubusercontent.com/assets/540757/13663205/2955730e-e6a0-11e5-87ba-6dc954a62e05.png">

This is when the page is served using HTTP/1. HTTP/2 looks good.

Maybe we just cleanup the HAR after + file a bug for Firefox? Think we have quite a long list of suggestions for improvements of the HAR file.

**Comment by soulgalore** [comment]
I remember now that when I tested Firefox nightly a while ago 304 was recognized. Need to check again and test it with BT, maybe works now.

**Comment by soulgalore** [comment]
Need to look into this again, think (hope) a lot has happened in Firefox.

**Comment by parangsjo** [comment]
Hello,

I wanted to show you something very important to me, just take a look here <http://thehahintu.wingsandravioli.com/xyijmdio>

Hugs, pa@rangsjo.com

**Comment by soulgalore** [comment]
Tested this today again with Firefox 48.0.1. It's even worse now, the first response is a 200 (should be 304). We should verify what it looks like in Firefox and then report it. First in the trigger.

I tried with nightly (upgraded the HAR Export trigger) and it is the same (with the extra bonus that each request is done two times).

**Comment by soulgalore** [comment]
Added this upstream https://github.com/firebug/har-export-trigger/issues/36

**Comment by soulgalore** [comment]
We clear the HAR now for local cache entries.
