### ISSUE TITLE
Provide an option to re-enable Firefox Tracking Protection

### ISSUE THREAD

**Issue by acreskeyMoz** [sitespeedio/browsertime#1211]
By default, Browsertime disables Firefox's Tracking Protection feature and supporting tech.

See: 
[firefoxPreferences.js](https://github.com/sitespeedio/browsertime/blob/52121ec7af3583987ba1ec58ba8796e49762b7c6/lib/firefox/webdriver/firefoxPreferences.js#L167-L168)

Tracking Protection can have a significant impact on performance (particularly 'Strict' mode which blocks resources from identified trackers.)

This bug is to provide an browsertime option so that Tracking Protection can be enabled if desired.

There will be some work to determine the complete set of preferences from `firefoxPreferences.js` which will need to be optionally removed. (The underlying tech relies on SafeBrowsing).

As a first attempt, I believe the following would be sufficient:

```
'browser.safebrowsing.blockedURIs.enabled': false,
  'browser.safebrowsing.downloads.enabled': false,
  'browser.safebrowsing.downloads.remote.url':
    'http://127.0.0.1/safebrowsing-dummy/downloads',
  'browser.safebrowsing.malware.enabled': false,
  'browser.safebrowsing.passwords.enabled': false,
  'browser.safebrowsing.phishing.enabled': false,
  'browser.safebrowsing.provider.google.gethashURL':
    'http://127.0.0.1/safebrowsing-dummy/gethash',
  'browser.safebrowsing.provider.google.updateURL':
    'http://127.0.0.1/safebrowsing-dummy/update',
  'browser.safebrowsing.provider.google4.gethashURL':
    'http://127.0.0.1/safebrowsing4-dummy/gethash',
  'browser.safebrowsing.provider.google4.updateURL':
    'http://127.0.0.1/safebrowsing4-dummy/update',
  'browser.safebrowsing.provider.mozilla.gethashURL':
    'http://127.0.0.1/safebrowsing-dummy/gethash',
  'browser.safebrowsing.provider.mozilla.updateURL':
    'http://127.0.0.1/safebrowsing-dummy/update',

... 
'privacy.trackingprotection.annotate_channels': false,
  'privacy.trackingprotection.enabled': false,
```

**Comment by soulgalore** [comment]
@acreskeyMoz the reason for this was that the Tracking Protection introduced so much variance in the metrics, since when running a new profile every time, it download the tracking protection lists during the page that is under test, do you know if that has been changed?

**Comment by acreskeyMoz** [comment]
@soulgalore - we disable tracking protection for some tests for that very reason.
Unfortunately the tracking protection lists are still downloaded on launch and can still introduce variance.
We work around this by either introducing conditioning steps in a selenium script prior to performing the measured pageload. Or else we use a system that copies over stable profiles.

**Comment by soulgalore** [comment]
I see. Is this almost the same as `--firefox.disableSafeBrowsing false` ? https://github.com/sitespeedio/browsertime/blob/master/lib/firefox/webdriver/disableSafeBrowsingPreferences.js so there are only a couple of them that needs to be moved?

**Comment by acreskeyMoz** [comment]
Yes, that's it.
I will need to verify the behaviour against tracking protection test sites, but that is the bulk.
Certainly these two would want to be moved with this option:
```
privacy.trackingprotection.annotate_channels : false,
privacy.trackingprotection.enabled : false,
```

**Comment by soulgalore** [comment]
Cool, @acreskeyMoz if you can create a PR, I can do fix release.

**Comment by jesup** [comment]
We're using a preload script to allow first-run stuff to resolve (load www.mozilla.org/en-US, wait N seconds, load about:blank, wait Y seconds).  Even better should be to use a --firefox.profileTemplate <profile dir>, but one needs to be a little careful with how the profile is generated - best is for it to be built with the same version, and even more preferably built (or at least updated) in the last day (so "once-a-day" operations won't immediately get scheduled). The last bit might not be critical.  Note that safebrowsing DBs get updated every ~30min IIRC, so t avoid them updating you need a very recent profile (or update them in the conditioned profile, but disable update checks when testing).

**Comment by soulgalore** [comment]
Ok, so I wonder how do we do it the best way? I think its one use case so you at Mozilla can use it but it would be cool if other Browsertime (and sitespeed.io) users also could run their tests with Tracking Protection turned on.

**Comment by soulgalore** [comment]
We had a meeting and I think this was the outcome: Since Tracking Protection is turned on by default for users and we (=Browsertime) turn it off (to get stable metrics) we potentially give wrong performance metrics of Firefox when a user runs a test. The problem is that with Tracking Protection turned on, Firefox download a new fresh list of domain to block on startup and download can give unstable metrics.

A way to fix that would be to create a profile that have the list already downloaded, and then have the Tracking Protection turned on and make sure it isn't updated for X days (or how that works).

If this works, I think this could be the default behaviour and then we can have a switch for preferences of "optimal stable performance"? 

Adding @tarekziade.

**Comment by soulgalore** [comment]
I can work on this but I need help. @tarekziade could you help me generate a profile with pre-made tracking protection list? I could also make two different versions of the preferences and make a PR and then you all can review it?

**Comment by tarekziade** [comment]
We generate and update conditioned profiles in our CI that should meet your requirements. 
I guess you can fetch them from their permalinks.

I need to know the list of systems you need to support, and I can prepare that list

**Comment by soulgalore** [comment]
Think of me like I don't know anything on how it works :) What do you mean by system? I think it would be ok to just take a snapshot of the list and then update it now and then + we then have an example of a profile, so it easier for users to create their own, following the same pattern.

**Comment by soulgalore** [comment]
This is implemented BUT we miss having all domains downloaded in a profile, so to test you need tio give Firefox 30+s to download the files before you start to test.

**Comment by soulgalore** [comment]
This works but you need to let Firefox wait.
