### ISSUE TITLE
single module test script

### ISSUE THREAD

**Issue by tarekziade** [sitespeedio/browsertime#1216]
I'd like to have the ability to pass to Browsertime a single JS module containing postScript, preScript and tests functions to make it look closer to a standalone test script a developer can have in their tests suite.

current proposed template:

```
    async function setUp(context, commands) {
      console.log("setUp");
    };
    ​
    async function perfTest1(context, commands) {
      return await commands.measure.start('https://www.sitespeed.io/examples/');
    };
    ​
    async function perfTest2(context, commands) {
      return await commands.measure.start('https://www.sitespeed.io/examples/');
    };
    ​
    async function tearDown(context, commands) {
      console.log("tearDown");
    };
 
    module.exports = {
      setUp: setUp,
      tearDown: tearDown,
      tests: [perfTest1, perfTest2]
    };
```

when this script is loaded, BT will look at the three variables exported by the module and use them, or fallback to the existing single function model.

**Comment by soulgalore** [comment]
Hi @tarekziade cool. Let me think about it for a couple of days. Thinking maybe we could just use the current scripting with some small fixes, but that's maybe what you already done in your patch, I haven't looked.

**Comment by tarekziade** [comment]
yeah, let me update the runner so you can see what I've done. of course this is just the prototype, I'll need to do it in a cleaner way with tests etc
