### ISSUE TITLE
appConstants in the result.json

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1249]
Hi @gmierz wanna check one thing that I missed when we merged all your upstream fixes: If your run Firefox today the result JSON includes everything in https://github.com/sitespeedio/browsertime/blob/master/browserscripts/browser/appConstants.js 

so it looks something like this:
```
{"browser":{"appConstants":{"ACCESSIBILITY":true,"ANDROID_PACKAGE_NAME":"org.mozilla.firefox","ASAN":false,"ASAN_REPORTER":false,"BROWSER_CHROME_URL":"chrome://browser/content/browser.xhtml","DEBUG":false,"DEBUG_JS_MODULES":"","DLL_PREFIX":"lib","DLL_SUFFIX":".dylib","EARLY_BETA_OR_EARLIER":false,"ENABLE_REMOTE_AGENT":false,"FENNEC_NIGHTLY":false,"HAVE_SHELL_SERVICE":true, ... and a lot more
```

Is that something you always need from your side? I wanna put that behind a flag, so users needs to enable it to be included in the result? I've been trying to keep the result readable and I'm thinking that information is overkill for a lot of users?

**Comment by gmierz** [comment]
Hi @soulgalore, I agree, we shouldn't always have that information in the results JSON and it should only be gathered if a flag such as `--firefox.appconstants` - what do you think the flag should be called?

**Comment by soulgalore** [comment]
Works fine, thanks for the PR :)
