### ISSUE TITLE
[feature request] spa testing - save artifacts even if commands.wait/click fail

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/browsertime#1266]
When testing spa pages and an element is not found, there is no video, no images, not even a directory saved locally to troubleshoot.

For example, I start a measurement and look for some element to click which is not found so it errors:

```
await commands.measure.start("somepage");
await commands.click.bySelector("button.whatever");
await commands.wait.bySelector("#whatever", 30000);
```

producing:
```
[2020-05-01 00:22:20] INFO: Start to measure somepage
[2020-05-01 00:22:22] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read property 'click' of null
  (Session info: chrome=81.0.4044.92)
[2020-05-01 00:22:22] ERROR: Could not click using selector button.whatever
[2020-05-01 00:22:22] INFO: Usage : FAIL
[2020-05-01 00:22:22] INFO: Error: Could not click using selector button.whatever
    at Click.bySelector (/usr/src/app/node_modules/browsertime/lib/core/engine/command/click.js:230:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

That's all fine as far as logging goes, but it begs the question, 'why not?' So, it would be helpful to still produce the video, artifacts, maybe even an xml dump of the UI so that I can troubleshoot what it did actually experience.

This would be super helpful to have this same output as a completed step:
![image](https://user-images.githubusercontent.com/627937/80771659-f08d1b00-8b08-11ea-9801-3d19b30a6f4b.png)

I'm using:
* docker 
* sitespeed 12.7.1-plus1 
* on AWS Ubuntu 18.04 and my mac

**Comment by soulgalore** [comment]
Yeah maybe we can do something smarter. I usually use the screenshot functionality in catch clauses: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#screenshot

So something like this:
```
try {
// do something on a a element ...
} catch (e) {
// oops somehow the element didn't exists? Why?
await commands.screenshot.take('checkout-button-missing');
}
```

**Comment by petemyron** [comment]
I assume those are uploaded to s3 (if that's configured), but are they referenced/accessible in the html reports?

**Comment by soulgalore** [comment]
Yes they end up on the screenshot page:
![screen](https://github.com/sitespeedio/browsertime/assets/540757/3891b388-f527-4cda-a36b-05ed56441db5)
