### ISSUE TITLE
SeleniumRunner::start() tries to start the browser 3 times - please make this configurable

### ISSUE THREAD

**Issue by acreskeyMoz** [sitespeedio/browsertime#1291]
See the 3 retries in SeleniumRunner::start() 
https://github.com/sitespeedio/browsertime/blob/ce638898742d2a35a4e8819e35ed32c6941565db/lib/core/seleniumRunner.js#L66

Please make this a configuration `.option` (for Mozilla automation purposes)

**Comment by soulgalore** [comment]
This is in master now `--browserRestartTries`.

**Comment by acreskeyMoz** [comment]
Awesome, thank you @soulgalore !
