### ISSUE TITLE
add privileged script APIs

### ISSUE THREAD

**Issue by tarekziade** [sitespeedio/browsertime#1308]
Currently we have:

- js.run(javascript)
- js.runAndWait(javascript)

and running JS in privileged mode requires calling low-level APIs in the driver.

I would like to propose the addition of 2 apis for this, to run in chrome context:

- js.runPrivileged(javascript)
- js.runPrivilegedAndWait(javascript)

**Comment by soulgalore** [comment]
Checked the code and we already have` js.runPrivileged(javascript)` :) I added the andWait method, check if it is what you need.

**Comment by soulgalore** [comment]
Merged to main.
