### ISSUE TITLE
--processStartTime option crashes if used on Chrome (android)

### ISSUE THREAD

**Issue by acreskeyMoz** [sitespeedio/browsertime#1329]
Using the option `--processStartTime true` will cause a crash when used on Chrome for android.

For example, run this test:
```{node} {browsertime.js} https://www.example.com -vvv --browser chrome --processStartTime true --android --chrome.android.package com.android.chrome```

And it will crash with these logs:
```
[2020-08-04 12:03:53] ERROR: [browsertime] TypeError: Cannot set property 'processStartTime' of undefined
    at Measure.collect (/Users/acreskey/.mozbuild/browsertime/node_modules/browsertime/lib/core/engine/command/measure.js:365:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It looks like the object `browser` from `this.result[this.numberOfMeasuredPages].browserScripts.browser` is undefined for Chrome in this case:
https://github.com/sitespeedio/browsertime/blob/bd1d9ed0f8b1e0ff791e5db960427fb22d48aef0/lib/core/engine/command/measure.js#L366

**Comment by acreskeyMoz** [comment]
I'm working on this locally -- one option that I like is moving this to `browserScripts.timings.processStartTime`, but I'll need some guidance on that.

**Comment by soulgalore** [comment]
@acreskeyMoz I'll help you out tomorrow night, I've been away for a couple of days.

**Comment by soulgalore** [comment]
Ok I had a look. Yep I think we can have better place for it. `browserScripts` is the place for data that we get from running JavaScript directly in the browser, so I think move it would be good (I've missed it when it was merged).

Maybe something like:
`this.result[this.numberOfMeasuredPages].process.startTime` if we ever want other process information?

**Comment by acreskeyMoz** [comment]
Thank you for looking at this @soulgalore.

Because of https://github.com/sitespeedio/browsertime/issues/1328 we're not pursuing this one.
Sorry for that. Not sure if it's worth keeping open.
