### ISSUE TITLE
Firefox 79.0.2 on Android fails to start

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1331]
Started to test the newly released Firefox on Android, but it fails to start:

```
bin/browsertime.js https://www.sitespeed.io -n 1 -b firefox  --android
[2020-08-08 19:27:48] INFO: Run tests on Moto G (5) using Android version 8.1.0
[2020-08-08 19:27:48] INFO: Running tests using Firefox - 1 iteration(s)
[2020-08-08 19:27:48] INFO: Skip install HAR trigger on Android
[2020-08-08 19:28:48] INFO: Browser failed to start, trying 2 more time(s): Failed to start browser in 60 seconds.
[2020-08-08 19:28:48] INFO: Skip install HAR trigger on Android
[2020-08-08 19:29:48] INFO: Browser failed to start, trying 1 more time(s): Failed to start browser in 60 seconds.
[2020-08-08 19:29:48] INFO: Skip install HAR trigger on Android
[2020-08-08 19:30:48] INFO: Browser failed to start, trying 0 more time(s): Failed to start browser in 60 seconds.
[2020-08-08 19:30:48] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/Users/peter/git/browsertime/lib/core/seleniumRunner.js:86:13)
```

However on the phone, the browser opens up, but the URL isn't loaded:

<img width="531" alt="Screenshot 2020-08-08 at 19 35 42" src="https://user-images.githubusercontent.com/540757/89716571-5e6d9c00-d9ae-11ea-8296-4d7820612482.png">

Maybe its some configuration that needs to be changed?

**Comment by gmierz** [comment]
Hi Peter, I think this has to do with the intents and/or activity that is being used by default in browsertime. For FF79 (Fenix), we use the following command to start the app:
`[task 2020-08-07T20:59:55.894Z] 20:59:26     INFO -  adb shell_output: adb -s FA79H1A00466 wait-for-device shell su -c "am start -W -n org.mozilla.fenix/org.mozilla.fenix.IntentReceiverActivity -a android.intent.action.VIEW -d about:blank", timeout: None, timedout: None, exitcode: 0, output: Starting: Intent { act=android.intent.action.VIEW dat=about:blank cmp=org.mozilla.fenix/.IntentReceiverActivity }`

Here's the browsertime command we are using for this browser version:
`[task 2020-07-29T18:16:32.986Z] 18:16:32     INFO -  raptor-browsertime Info: browsertime cmd: /builds/task_1596041793/fetches/node/bin/node /builds/task_1596041793/fetches/browsertime/node_modules/browsertime/bin/browsertime.js --firefox.geckodriverPath /builds/task_1596041793/fetches/geckodriver /builds/task_1596041793/workspace/build/tests/raptor/raptor/browsertime/../../browsertime/browsertime_pageload.js --browser firefox --android --firefox.binaryPath /builds/task_1596041793/fetches/node/bin/node --firefox.android.package org.mozilla.fenix --firefox.android.activity org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank`

We have tests running on for this browser through browsertime here if you'd like to look at some logs: https://treeherder.mozilla.org/#/jobs?repo=fenix&tier=1%2C2%2C3&searchStr=browsertime&revision=9066d0bf20aa08ea2a0bf45c4e68bc644f68d68b

**Comment by soulgalore** [comment]
Thank you @gmierz let me change it then for the coming release so it works by default!

**Comment by soulgalore** [comment]
It seems like  `--firefox.android.package org.mozilla.fenix` does't work on the stable release:

`[2020-08-09 12:47:12] INFO: Browser failed to start, trying 2 more time(s): Package 'org.mozilla.fenix' not found`

I'll check more tonight.

**Comment by gmierz** [comment]
Oh yes, the package name you have by default should be correct (org.mozilla.firefox iirc). The package name used in the example is from the nightly build. 

It's either the activity that needs to be changed or adding these extra intents - I think the -d about:blank will resolve the issues: `-a android.intent.action.VIEW -d about:blank`

**Comment by gmierz** [comment]
This activity will need to change to `org.mozilla.firefox.IntentReceiverActivity`: https://github.com/sitespeedio/browsertime/blob/main/lib/firefox/webdriver/index.js#L220

**Comment by soulgalore** [comment]
I tried but didn't get it to work. I'm using
`
--android -b firefox https://www.sitespeed.io -n 1 --firefox.android.activity org.mozilla.firefox.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank`

**Comment by gmierz** [comment]
> I tried but didn't get it to work. I'm using
> ` --android -b firefox https://www.sitespeed.io -n 1 --firefox.android.activity org.mozilla.firefox.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank`

I'll check it out locally today and post here with what I find.

**Comment by gmierz** [comment]
Can you try it with the activity `org.mozilla.fenix.IntentReceiverActivity`?

Here's the command I'm testing with:
`13:21:46     INFO -  raptor-browsertime Info: browsertime cmd: /home/sparky/.mozbuild/node/bin/node /home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/bin/browsertime.js --firefox.geckodriverPath /home/sparky/geckodriver /home/sparky/mozilla-source/mozilla-central/testing/raptor/raptor/browsertime/../../browsertime/browsertime_pageload.js --browser firefox --android --firefox.binaryPath /home/sparky/.mozbuild/node/bin/node --firefox.android.package org.mozilla.firefox --firefox.android.activity mozilla.telemetry.glean.debug.GleanDebugActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=--es --firefox.android.intentArgument=startNext --firefox.android.intentArgument=org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=--esa --firefox.android.intentArgument=sourceTags --firefox.android.intentArgument=automation --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank --browsertime.page_cycles 25 --browsertime.url https://www.amazon.com --browsertime.page_cycle_delay 1000 --browsertime.post_startup_delay 1 --firefox.profileTemplate /tmp/tmpJzNABJ.mozrunner --skipHar --viewPort 1366x695 --pageLoadStrategy none --firefox.disableBrowsertimeExtension true --pageCompleteCheckStartWait 5000 --pageCompleteCheckPollTimeout 1000 --visualMetrics false --timeouts.pageLoad 60000 --timeouts.script 1500000 --resultDir /home/sparky/mozilla-source/mozilla-central/testing/mozharness/build/blobber_upload_dir/browsertime-results/amazon --video false -n 1
`

It's not working for me though because of this error:
```
13:21:46     INFO -  raptor-browsertime Info: Running tests using Firefox - 1 iteration(s)
13:21:56     INFO -  Exception in thread ProcessReader:
13:21:56    ERROR -  Traceback (most recent call last):
13:21:56     INFO -    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
13:21:56     INFO -      self.run()
13:21:56     INFO -    File "/usr/lib/python2.7/threading.py", line 754, in run
13:21:56     INFO -      self.__target(*self.__args, **self.__kwargs)
13:21:56     INFO -    File "/home/sparky/mozilla-source/mozilla-central/testing/mozbase/mozprocess/mozprocess/processhandler.py", line 1116, in _read
13:21:56     INFO -      callback(line.rstrip())
13:21:56     INFO -    File "/home/sparky/mozilla-source/mozilla-central/testing/mozbase/mozprocess/mozprocess/processhandler.py", line 1026, in __call__
13:21:56     INFO -      e(*args, **kwargs)
13:21:56     INFO -    File "/home/sparky/mozilla-source/mozilla-central/testing/raptor/raptor/browsertime/base.py", line 358, in _line_handler
13:21:56     INFO -      raise Exception("Browsertime failed to run")
13:21:56     INFO -  Exception: Browsertime failed to run
13:21:58 CRITICAL -  raptor-browsertime Critical: InvalidArgumentError: setWindowRect is only supported in Firefox desktop
```

**Comment by soulgalore** [comment]
Thank, yep that works. I tried with ` bin/browsertime.js --firefox.android.package org.mozilla.firefox --firefox.android.activity org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=--es --firefox.android.intentArgument=startNext --firefox.android.intentArgument=org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=--esa --firefox.android.intentArgument=sourceTags --firefox.android.intentArgument=automation --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank --android -b firefox https://www.sitespeed.io` but then got the same error as you `setWindowRect`. The strange thing is that I verified that we don't run that on Android, I wonder if it could be something new from Geckodriver, couldn't see that we use that from the code, but will dig into it asap.

**Comment by gmierz** [comment]
Oh sorry! I forgot to put a link to the bug for this error: https://bugzilla.mozilla.org/show_bug.cgi?id=1650872

It seems to be an issue with Marionette.

**Comment by gmierz** [comment]
@soulgalore so the bug was fixed, but it doesn't look like we can get an uplift so we'll have to wait before you can use the release version.

In the mean time, you could try using the beta or nightly builds since nightly is unaffected by this bug, and beta should contain the fix.

**Comment by soulgalore** [comment]
Thank you @gmierz ! I'll try with beta and prepare the setup.

**Comment by gmierz** [comment]
Sounds good, ping me if you hit any issues there. I've requested an uplift of the patch but if that doesn't go through, it will be in the Sept. ~22 release.

**Comment by soulgalore** [comment]
It works for me with nightly but could you help me find the docs (or explain) all of those intentArgument so I know which one I should add as default? That would be super useful :)

**Comment by gmierz** [comment]
@soulgalore you should only need these options: `--firefox.android.activity org.mozilla.firefox.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank`

The -d option specifies the data to display in the browser (in this case it's the about:blank page) and the -a option lets us specify the android action to use.

The rest of the options in the command you listed above are for internal use to change the Glean ping names.

**Comment by soulgalore** [comment]
@gmierz I'm still struggling on getting this to work. Was the fix released in latest 80 (I'm running 80.1.2) or did it just miss it?

**Comment by gmierz** [comment]
@soulgalore it just missed it unfortunately. It should be available in a release on around Sept. 22 - the beta release works for me now though (using the org.mozilla.firefox_beta package name).

**Comment by soulgalore** [comment]
Ok cool, thanks @gmierz !

**Comment by soulgalore** [comment]
So I need all of these to get it to work on beta: 
`--firefox.android.package org.mozilla.firefox_beta --firefox.android.activity org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW --firefox.android.intentArgument=--es --firefox.android.intentArgument=startNext --firefox.android.intentArgument=org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=--esa --firefox.android.intentArgument=automation --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank --android -b firefox https://www.sitespeed.io `

If I try to cherry pick and remove some it seems it always fails. Are the order of the arguments importan @gmierz ?

**Comment by gmierz** [comment]
@soulgalore yes the order is important for these but you should be able to remove these ones:
`--firefox.android.intentArgument=--es --firefox.android.intentArgument=startNext --firefox.android.intentArgument=org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=--esa --firefox.android.intentArgument=automation `

**Comment by soulgalore** [comment]
Yes thanks. I got it working now with` bin/browsertime.js --firefox.android.package org.mozilla.firefox_beta --firefox.android.activity org.mozilla.fenix.IntentReceiverActivity --firefox.android.intentArgument=-a --firefox.android.intentArgument android.intent.action.VIEW  --firefox.android.intentArgument=-d --firefox.android.intentArgument about:blank --android -b firefox https://www.sitespeed.io` so let me set them as default (except the beta package) before next release.

**Comment by soulgalore** [comment]
This works now with latest Firefox stable and latest released Browsertime.
