### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by umeshPathak** [sitespeedio/browsertime#1373]
I have installed browsertime Linux . But getting below error when running it on the Linux

[2020-09-07 16:59:19] INFO: Browser failed to start, trying 0 more time(s): The specified executable path does not exist: /usr/local/lib/node_modules/browsertime/node_modules/@sitespeed.io/geckodriver/vendor/geckodriver

the  **/usr/local/lib/node_modules/browsertime/node_modules/@sitespeed.io/geckodriver/vendor** is empty.
How to setup the geckodriver manually ? How to update it on regular basis to synch it with firefox browser ?

**Comment by soulgalore** [comment]
Hi @umeshPathak did you get an error when you did install it? You set the path to your own Geckodriver using `--firefox.geckodriverPath `. All options should be there if you run `--help`.

**Comment by soulgalore** [comment]
Closing since we didn't get any feedback.
