### ISSUE TITLE
Add an option for webdriver navigation (instead of window.location writes)

### ISSUE THREAD

**Issue by acreskeyMoz** [sitespeedio/browsertime#1395]
Currently Browsertime navigates to the target url by writing to `window.location` :
https://github.com/sitespeedio/browsertime/blob/de710c143f9f49a4fa13c808906ac712406ca586/lib/core/seleniumRunner.js#L223

We have found that, at least in Firefox, this is a codepath that is not representative of a user workflow.
(The `window.location` navigation begins in the content process instead of the parent process, and key optimizations such as a tcp-preconnect are by passed).

The bug is to add an option (default off) to enable navigation via `webdriver.get({url})`

**Comment by acreskeyMoz** [comment]
@soulgalore I have a patch incoming for this.
In Firefox for android (aka Fenix), we've found that this reduces the artificially slow early network timing (e.g. `connectStart`) by ~60ms.

**Comment by soulgalore** [comment]
One question @acreskeyMoz : did you see any difference for Visual Metrics in your test, thinking about when we remove the orange background color running with webdriver navigation?

**Comment by acreskeyMoz** [comment]
@soulgalore We did see improvements in visual metrics, but resulting from the improvement in network times.

But I'm looking at the patch that just landed and it didn't merge correctly when I rebased it:

In the `clearOrange` function I shouldn't be navigating at all:
https://github.com/sitespeedio/browsertime/blob/d167f4566fe91d335fa93e43318799d4f87dac10/lib/core/seleniumRunner.js#L221-L224

With that fixed the orange background removal should be the same with and without webdriver navigation. (i.e. right before the navigation).

Let me make a new issue and patch to fix this.

**Comment by acreskeyMoz** [comment]
Let me know if I should make an issue for https://github.com/sitespeedio/browsertime/pull/1397

Also, we of course haven't flipped this switch on yet in our CI testing.
I still need to validate it on other platforms.
But this is the direction we want to move it.

**Comment by soulgalore** [comment]
>  We did see improvements in visual metrics, but resulting from the improvement in network times.

What I meant was do it correlate with first paint etc? I remember when implementing this a long time ago, this reduced the time between removing the orange and actually navigating = first paint reported by Chrome and first visual change matched, that's why I just reverted back to have follow the exact same pattern in the old flow. Or are you saying you see something else?  :) Then I need time verify and test.

**Comment by acreskeyMoz** [comment]
Ah, I _think_ I understand what you're asking :)

We're seeing changes in the earliest network timing, even at `domainLookupStart.`
And this does bubble up to `firstPaint`.

But I think this change has impact outside of just shifting when the orange is removed:

We did some profiling and analysis and this is giving us the correct parent-process initiated navigation codepath.
So we're pretty sure that the change is because we're skipping the content-process to parent-process IPC and delay in the event queue. We may also be hitting the speculative tcp connect in the parent process (I'll be verifying that).

Work is ongoing for me to find out if this is how we want to test Firefox by default.

**Comment by soulgalore** [comment]
Ok! But you agree that it's ok to do https://github.com/sitespeedio/browsertime/pull/1398 to make sure everything works exactly as before with the old code path?

**Comment by acreskeyMoz** [comment]
Ah, yes, @soulgalore -- that makes sense.
The timing is very sensitive, so I agree that's better to remove the orange in the same script execution.
