### ISSUE TITLE
Can I get the DOM tree of a website via this tool?

### ISSUE THREAD

**Issue by dpburst** [sitespeedio/browsertime#1410]
Hi! I am new to Javascript. I want to get the size of the request and response of each resource (I know how to achieve this already) as well as the dependency relationship between resources in a web. I just wonder whether I can achieve the latter via browsertime? Thank you so much!

**Comment by soulgalore** [comment]
Hi @dpburst sorry for being so late on this. If you mean you want the DOM you get the generated DOM using [scripting](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol) and Chrome devtools protocol for Chrome: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getDocument.

If you mean resources, what resource that was triggered by what, you can see that in the HAR file fro Chrome (initiated by or something like that).
