### ISSUE TITLE
Server terminated early with status 127

### ISSUE THREAD

**Issue by vAugagneur** [sitespeedio/browsertime#144]
Hi, 
I have this error message when i'm trying to use browsertime "Server terminated early with status 127".
I'm using version 0.12.2 of browsertime. 
Os : Debian 8 

> browsertime -u http://www.google.fr -v
> Starting proxy on port 2001, will wait at most 15000 ms
> Fetching http://www.google.fr (1 of 3)
> [Error: Server terminated early with status 127]
> Server terminated early with status 127
> Stopping proxy

I have the same issue with sitespeed.io

> sitespeed.io -u http://www.google.fr -b chrome  -d 0  --resultBaseDir /var/www/perf/sitespeed-result/  --storeJson
> info: OS: 'linux 3.14.99', Node.js: 'v4.4.5', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.8.0_91', browsertime: '0.12.2'
> info: Will analyze 1 page
> info: Running YSlow for http://www.google.fr [phantomjs]
> Starting proxy on port 2001, will wait at most 15000 ms
> info: Queueing browsertime for http://www.google.fr chrome
> info: Running browsertime for chrome http://www.google.fr
> Fetching http://www.google.fr (1 of 3)
> [Error: Server terminated early with status 127, for: [object Object]]
> error: Error running browsertime: [Error: Server terminated early with status 127, for: [object Object]]
> Stopping proxy
> error: Could not generate HAR for http://www.google.fr { [Error: ENOENT: no such file or directory, open '/var/www/perf/sitespeed-result/www.google.fr/2016-06-01-22-28-46/data/har/chrome/www_google_fr.har']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/var/www/perf/sitespeed-result/www.google.fr/2016-06-01-22-28-46/data/har/chrome/www_google_fr.har' }

**Comment by soulgalore** [comment]
Hey @vAugagneur sorry for not answering this before, been focusing on the 1.0 release (you can try out that branch). There we don't BrowserMobProxy and that will hopefully work. For sitespeed.io you can try alpha-1 or build from master.

Best
Peter

**Comment by soulgalore** [comment]
Haven't seen this in the new version, let us know if this is still a problem and we can re-open.
