### ISSUE TITLE
Setting Network Throttle on Chrome internally

### ISSUE THREAD

**Issue by marty90** [sitespeedio/browsertime#1459]
Chrome allows emulating network conditions internally through the developer tools.
This is also exposed via the Chrome DevTools Protocol (see [here](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions)).

Using this feature to emulate network conditions would be very useful as it does not rely on any form of external tools (`tc`, `netem`) and would allow making more tests in parallel (using the `ifb` kernel module makes it somehow cumbersome).

I think using it in BrowserTime is rather easy, using a `preScript`. I [found](https://www.selenium.dev/selenium/docs/api/py/webdriver_chromium/selenium.webdriver.chromium.webdriver.html?highlight=set_network_conditions#selenium.webdriver.chromium.webdriver.ChromiumDriver.set_network_conditions) that that Chrome driver has recently added the `set_network_conditions` method.

Did anyone try this?

**Comment by soulgalore** [comment]
Hi @marty90 you can read more about that throttling in https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md and look for _Request-level throttling_ . I've never used it for testing except outside of one off tries inside of devtools.

**Comment by marty90** [comment]
Thank you for the pointer. Looking at [this](https://docs.google.com/document/d/1TwWLaLAfnBfbk5_ZzpGXegPapCIfyzT4MWuZgspKUAQ/edit), it seems that DevTool Throttling is not very accurate - e.g., does not introduce latency on DNS.

**Comment by marty90** [comment]
Making several tests with shaping is now a bit hard...  Imagine you have a large server, you can hardly parallelize your tests, as you should know in advance how many `ifb` interfaces you need...

**Comment by soulgalore** [comment]
I'm closing but you can use it yourself if you use [scripting and the Chrome devtools protocols](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol).
