### ISSUE TITLE
Getting multiple HAR concurrently

### ISSUE THREAD

**Issue by Tharushan** [sitespeedio/browsertime#1470]
Hello,

I'm having an issue in my process to dockerize my tests using browsertime and hope you can help or at least guide me to better solutions.

## Context

Actually I am using browsertime through docker containers using script like this:

```
#!/usr/bin/env bash

uuid=$(uuidgen)
docker run --shm-size=2g --network=3g --rm -v "$HAR_DIRECTORY":/browsertime sitespeedio/browsertime:3.10.0 \
-n 1 \
--video false \
--visualMetrics false \
--har $uuid \
--gzipHar \
--pageCompleteCheck="return window.performance.timing.fetchStart>0 && Date.now() - window.performance.timing.fetchStart > 30000" \
--verbose \
--chrome.mobileEmulation.deviceName "iPhone 8" \
--chrome.timeline true \
--chrome.enableTraceScreenshots true \
--cpu true \
-c 3g \
--connectivity.engine external \
--cacheClearRaw true \
$1
```

I'm using this to get HAR but the problem is I am actually doing it on at least 10 websites using various parameters ( mobile / desktop,  passing some request headers too ) and there are too much containers used.

## Issue

I then tried updating my script so I can use it in only one container doing all the jobs it looks like this  : 

```
#!/bin/sh

uuid=$(uuidgen)

MOBILE_FETCHER_OPTS=( -n 1 \
--video false \
--visualMetrics false \
--har $uuid \
--gzipHar \
--pageCompleteCheck="return window.performance.timing.fetchStart>0 && Date.now() - window.performance.timing.fetchStart > 30000" \
--verbose \
--chrome.mobileEmulation.deviceName "iPhone 8" \
--chrome.timeline true \
--chrome.enableTraceScreenshots true \
--cpu true \
-c 3g \
--connectivity.engine external \
--cacheClearRaw true
)

npx browsertime "${MOBILE_FETCHER_OPTS[@]}" --chrome.args user-data-dir=/tmp/user1 https://m.youtube.com &
npx browsertime "${MOBILE_FETCHER_OPTS[@]}" --chrome.args user-data-dir=/tmp/user2 https://m.facebook.com &
```

It actually works if I am trying this only on one website but when I try to use it on more than one I have this error : 

> ERROR: [browsertime] Error: Tracing has already been started (possibly in another tab).

Closing both browsertime tests, as you can see I tried using chrome profiles using user-data-dir so it opens an instance of chrome for each tests.

Do someone have a solution for this issue or is this only related to chrome not being able to process multiple tracing at the same time ?

Thanks,

**Comment by soulgalore** [comment]
Hi @Tharushan sorry for not getting back earlier. Can you try to simplify the use case and see when it stops to work? When I try to run something simple like :
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime https://www.sitespeed.io/ --cpu` 
at the same time, I don't get an error.

**Comment by Tharushan** [comment]
Hey @soulgalore ,

Sorry for the late reply, running in multiple containers at the same time actually works but I'm actually trying to parallelize these tests for multiple websites in a single docker container so it's more efficient

**Comment by soulgalore** [comment]
I would run the test in one container per test.
