### ISSUE TITLE
Fresh install on Ubuntu 20.04 Error: Command failed: sudo ip link set dev ifb0 up

### ISSUE THREAD

**Issue by vivacoda** [sitespeedio/browsertime#1497]
Ubuntu 20.04 on dedicated server fresh install  
Install with Nodejs (no docker)
net-tools is installed 

`throttle --up 330 --down 780 --rtt 200`

```Error: Command failed: sudo ip link set dev ifb0 up
Cannot find device "ifb0"

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'sudo ip link set dev ifb0 up',
  stdout: '',
  stderr: 'Cannot find device "ifb0"\n'
}```
Any Idea?

**Comment by soulgalore** [comment]
HI @vivacoda sorry I missed this. Can you try run https://github.com/sitespeedio/throttle directly and then log all commands using `--log` then its easier to see what goes wrong.

Best
Peter

**Comment by nhp** [comment]
I had the exact same issue and could fix it with adding `--cap-add=NET_ADMIN` and `--browsertime.connectivity.engine=throttle` to the docker run command. Afterwards it worked flawless.

**Comment by soulgalore** [comment]
Didn't get any response, closing.
