### ISSUE TITLE
Problem launching Browsertime docker with extension using a specific profile folder on Windows

### ISSUE THREAD

**Issue by Ch3sh1r3-C4t** [sitespeedio/browsertime#1525]
### **Introduction**
Hi, I am a cybersecurity researcher and university student. I am trying to use browsertime to detect the efficiency of browser extensions (focused on security and protect the user) in detecting/blocking malicious sites, as well as measuring the impact on the performance they have.

To do this I created a few browser profiles. Each one of them contains an extension that I wish to test. Those profiles have been zipped after the creation to make sure that every website is tested with the profile in the same condition. When I have to test a website I unzip the profile, launch a test and after the test delete the profile folder used. In the steps below I used the Windows defender extensions, but the result is the same with any extension.

### **Issue**
The problem that I am facing is that on Windows 10 browsertime is not using the profile and the extension is not blocking the websites, even though they should be blocked. I have attached a zip file with the results from browsertime and the screenshots with the expected result and actual result. I also gave it a try using the --extension switch with the crx file of the extension, but the result does not change. I tested this on Linux and it works as expected with the extension blocking the pages.
 Please let me know if there is a way to fix this on Windows and solve this issue.

### **Environment**
Windows 10
Browsertime 11.6.3 (Docker installation)
Chrome Version 89.0.4389.90 (Official Build) (64-bit)
Added C:\Program Files\Google\Chrome\Application to PATH variable to launch chrome using chrome.exe 

### **Configuration File Used (config_Test.json)**
`{
  "iterations": 1,
  "browser": "chrome",
  "chrome": {
    "args": [
        "user-data-dir=./windowsDefender",
        "disable-application-cache",
        "aggressive-cache-discard",
        "chromedriverPath=C:/Program Files/Google/Chrome/Application/chrome.exe"
    ]
  }
}
`

### **Step to reproduce**
1.  Launch Google Chrome with a new profile called windowsDefender using `chrome.exe --user-data-dir=.\windowsDefender`
2. Install [Microsoft Defender Browser Protection](https://chrome.google.com/webstore/detail/microsoft-defender-browse/bkbeeeffjjeopflfhgeknacdieedcoml) in the chrome profile
3. Clear the history and the cache, then close chrome
4. Zip the profile directory using the powershell command `Compress-Archive -Path .\windowsDefender\Default\ -DestinationPath .\windowsDefender.zip` 
5. Delete the windowsDefender profile directory  using the powershell command `Remove-Item -Recurse .\windowsDefender\` 
6. Extract the zipped profile using the powershell command `Expand-Archive -Path windowsDefender.zip -DestinationPath ./windowsDefender/`
7. Launch browsertime with the config file (included above) telling to use the windowsDefender profile, against a known malicious site which should be blocked by the windowsDefenderExtension using the command ` powershell docker run --net=host --rm -v "${pwd}:/browsertime" sitespeedio/browsertime:11.6.3 --resultDir ./ --useSameDir --prettyPrint --video false --videoParams.createFilmstrip false --screenshot true --timeouts.pageCompleteCheck 120000 --config ./config_Test.json https://online-mydebit-payments.com/` 
In case the site I used is down, try to use another website that should be blocked by the windows defender extension. You can find plenty of them on [phisthank](http://phishtank.org/phish_search.php?valid=y&active=y&Search=Search).

### **Results Browsertime**
[resultsbrowsertime.zip](https://github.com/sitespeedio/browsertime/files/6221841/resultsbrowsertime.zip)

### **Expected result**
![expectedResult](https://user-images.githubusercontent.com/44528713/112839882-faaff480-909e-11eb-8528-2f5871ac01f2.png)

### **Actual result with browsertime (page does not get blocked)**
![resultBrowsertime](https://user-images.githubusercontent.com/44528713/112839886-fb488b00-909e-11eb-96df-fcbe741c7166.png)

**Comment by soulgalore** [comment]
Hi @LucSai when you run in Docker, it will use the Chrome version in the container (Linux version). If you wanna run extensions in the container you need to link ("share") your extension dir to the container. For your use case I think its easier to just run the NodeJS version? Then it will use your installed browser etc and its easier conceptuella how to use extensions. Checkout how we install in our Windows GitHub Action: https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/windows.yml

**Comment by LucSai** [comment]
Hi @soulgalore , thank you so much for the quick reply!  I will install the nodejs version and give it a go with it, hopefully it will fix the issue.

**Comment by LucSai** [comment]
Hi @soulgalore I just installed npm and run a test with the version installed with npm, but for some reason it still does not work...
I can clearly see that the profile with the extension gets loaded fine this time, but the extension still don't block the malicious pages for some reason... Can you think of anything else that might be causing this issue or that I might do/implement to try to fix this problem? Thank you again for your help

**Comment by soulgalore** [comment]
How do the block in the extension work? By default we navigate to a new page using JavaScript like this. `window.location='https://www.sitespeed.io';` You can also navigate using webdriver directly, try it out by setting: `--webdriverPageload=true`

**Comment by LucSai** [comment]
Hi, thank you a lot for your help and support! I will try using the webdriverPageLoad switch and see if it improve the situation.

Regarding the extension, as far as I am aware, it should check the URL against the lists of malicious websites from Microsoft, and if the list from windows flag the website as malicious it should warn the user and block it. I am not sure whether they also use other information (such as the IP or check header in the request) to help detecting if the website is malicious.

The description from the chrome web store says: "Protect yourself against online threats, like phishing and malicious websites, with real-time protection from Microsoft. If you click a malicious link in an email or navigate to a site, Microsoft Defender Browser Protection will check it against a constantly updated list of malicious URLs known to Microsoft. 
If the malicious link matches one on the list, Microsoft Defender Browser Protection will show a red warning screen letting you know that the web page you are about to visit is known to be harmful, giving you a clear path back to safety with one click." ([chrome web store](https://chrome.google.com/webstore/detail/microsoft-defender-browse/bkbeeeffjjeopflfhgeknacdieedcoml), [Microsoft website about the extension](https://browserprotection.microsoft.com/learn.html))

**Comment by soulgalore** [comment]
Hi @LucSai did you get it to work? When I looked at the extension it said "Currently supported region(s):  United States " what does that mean?

**Comment by LucSai** [comment]
I honestly don't  know what they mean by the "Currently supported region(s): United States"...
Personally, I think that might refer to the language used, as it is only support English (United State) as a language (but that is only my assumption). At the moment I managed to get it to work by increasing the number of iteration in the configuration file, from one to two.

**Comment by soulgalore** [comment]
I'm not sure what to do with this issue, so I'm closing, please let me know if you think there's anything I can do.
