### ISSUE TITLE
geckoprofiler should wait for a few seconds after `Start GeckoProfiler`

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1538]
We should wait for a few seconds after https://github.com/sitespeedio/browsertime/blob/9004781fda367edcbd7285723949a02c23ec998f/lib/firefox/geckoProfiler.js#L88 to let it settle down.

**Comment by soulgalore** [comment]
I can add that. Is two seconds enough @sefeng211 ?

**Comment by sefeng211** [comment]
I think we uses 3 seconds in Gecko

**Comment by soulgalore** [comment]
Fixed it in https://github.com/sitespeedio/browsertime/pull/1539
