### ISSUE TITLE
Extrac space at the top of a file causes a problem

### ISSUE THREAD

**Issue by mephisto83** [sitespeedio/browsertime#1545]
If i have a empty space before the javascript code, the results won't make it to the metrics.
If i remove the line space, then it works.

![image](https://user-images.githubusercontent.com/7797183/77685507-8b726280-6f69-11ea-8b28-435dad1048b2.png)

**Comment by soulgalore** [comment]
I would just remove the extra space :) The loading of script has changed since this was originally created so hopefully this just works now.
