### ISSUE TITLE
browsertime installation issue - error 404 Not Found - GET http://registry.npmjs.org/browsertime

### ISSUE THREAD

**Issue by ramkumar-sukumaran** [sitespeedio/browsertime#1603]
Hi,

We were trying to install browsertime in my system were getting below error.

npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/browsertime
npm ERR! 404
npm ERR! 404  'browsertime@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Steps which followed for installation:
npm version: 6.14.10

npm config set http-proxy <url>
npm config set https-proxy  <url>
npm config set strict-ssl false
npm config set registry http://registry.npmjs.org/

npm install browsertime -g

checked the URL - http://registry.npmjs.org/browsertime in the browser were I am able to view the json output.

Please help to sort the issue.

Regards
Ram

Entry log file content, removed the directory path...

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '...\nodejs\\node.exe',
1 verbose cli   '...\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'browsertime',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose npm-session af86417b8f3221fb
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 http://registry.npmjs.org/browsertime 94ms
8 http fetch GET 404 http://registry.npmjs.org/browsertime 15ms
9 silly fetchPackageMetaData error for browsertime@latest 404 Not Found - GET http://registry.npmjs.org/browsertime
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 172ms
12 verbose stack Error: 404 Not Found - GET http://registry.npmjs.org/browsertime
12 verbose stack     at ...\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid browsertime@latest
15 verbose cwd ...
16 verbose Windows_NT 10.0.18363
17 verbose argv "...\nodejs\\node.exe" "...\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "browsertime" "-g"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code E404
21 error 404 Not Found - GET http://registry.npmjs.org/browsertime
22 error 404
23 error 404 'browsertime@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by soulgalore** [comment]
Hi @ramkumar-sukumaran I think this is either npm temporary glitch or maybe something in your setup? What happens if you try `npm view browsertime`?

```
....
dist-tags:
canary: 12.0.0-beta.2  latest: 12.10.0  
....

```

**Comment by ramkumar-sukumaran** [comment]
Hi @soulgalore
Please find the below details when I execute the given command.

C:\>npm view browsertime
npm ERR! code E404
npm ERR! 404 'browsertime' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  'browsertime@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by soulgalore** [comment]
My guess is that your proxy settings aren't correct? Does other npm module work?

**Comment by soulgalore** [comment]
I don't see this as problem of Browsertime, must be an npm or proxy problem
