### ISSUE TITLE
Assertion `(ret) != (nullptr)' failed.

### ISSUE THREAD

**Issue by alexandru-io** [sitespeedio/browsertime#1618]
Hi,

While running browsertime on firefox we encountered the following error:
```
[task 2021-06-28T13:58:20.015Z] 13:58:20     INFO -  raptor-browsertime Info: Running tests using Firefox - 1 iteration(s) 
[task 2021-06-28T13:58:21.527Z] 13:58:21     INFO -  raptor-browsertime Info: b"C:\\windows\\system32\\cmd.exe[2144]: c:\\ws\\src\\env-inl.h:949: Assertion `(ret) != (nullptr)' failed." 
[task 2021-06-28T13:58:21.791Z] 13:58:21     INFO -  perftest-results-handler Info: retrieving browsertime test results 
[task 2021-06-28T13:58:21.792Z] 13:58:21     INFO -  perftest-results-handler Critical: unable to find browsertime results at C:\Users\task_1624883051\build\blobber_upload_dir\browsertime-results\youtube-playback-widevine-h264-sfr\browsertime.json 
[task 2021-06-28T13:58:21.792Z] 13:58:21     INFO -  raptor-perftest Info: Removing temporary directory: C:\Users\task_1624883051\AppData\Local\Temp\tmpx2uos4pl 
[task 2021-06-28T13:58:21.840Z] 13:58:21    ERROR -  raptor-main Critical: TEST-UNEXPECTED-FAIL: no raptor test results were found for youtube-playback-widevine-h264-sfr 
[task 2021-06-28T13:58:21.896Z] 13:58:21    ERROR - Return code: 1
```

It looks like node is running out of memory, based on the line referenced in the error (https://github.com/nodejs/node/blob/v12.x/src/env-inl.h#L949).
Is this reproducable on your side? Have you seen this before?

**Comment by soulgalore** [comment]
Hi @alexandru-io not directly when I use Browsertime, but I've seen similar for sitespeed.io users (normally users test more URLS and more metrics within the same run = need more memory). You can increase the memory for NodeJS. I think the default size is 2048 mb (or at least was before). Checkout https://support.circleci.com/hc/en-us/articles/360009208393-How-can-I-increase-the-max-memory-for-Node- for how you can do it. I wonder though, 2 gig is quite much for just one URL with the default metrics collected. There's some docs https://www.sitespeed.io/documentation/sitespeed.io/developers/#debugging-with-chrome where you can debug a NodeJS process (Browsertime) and see where the memory is spent, I haven't used that in a couple of years (maybe the docs need to be updated) but when I last did it was really helpful.

**Comment by alexandru-io** [comment]
@soulgalore the problem is that the test is running node via a command line argument `./mach raptor --test ... --browsertime-node [path_to_binary_node]` and I don't know how to pass that `--max-old-space-size` this way. I'm not familiar with node. Any ideas?

**Comment by soulgalore** [comment]
@alexandru-io you can export that as a node option on your own machine to try. If you are on Linux you can try:

```
echo $NODE_OPTIONS. // Just to check if you have something set before
export NODE_OPTIONS=--max_old_space_size=4096
```

**Comment by soulgalore** [comment]
Closing let me know if that didn't help.
