### ISSUE TITLE
Save incomplete browser recordings

### ISSUE THREAD

**Issue by alexandru-io** [sitespeedio/browsertime#1656]
For the moment browsertime doesn't save browser recordings that firefox crashed during them. We have tests like youtube-playback that have a single page cycle and fail for some reason before browsertime gets to save the recording. This would probably imply catching the browser error/crash and convert the partial recording as a complete one is converted into a video file.

**Comment by soulgalore** [comment]
Hi @alexandru-io yep that would be great. I can have a look, do you have a way I can reproduce or can you see when the crash happens (so if I try to simulate it, I do it at the right place/moment)?
