### ISSUE TITLE
HAR file partially generated

### ISSUE THREAD

**Issue by GianlucaPoliTo** [sitespeedio/browsertime#1664]
Good morning everyone, 
I'm testing a video streaming page and I noticed that the har file generated in output from sitespeedio/browsertime (latest version looking today) is partially generated. In particular, what I see is that the har file generally stops at the (almost) 60 requests of the video, but the experiment should arrive at (almost) 150.

The code to run the experiment is:

sudo docker run --rm -v "$(pwd)":/sitespeed -w / sitespeedio/browsertime \
           --chrome.args enable-quic \
           --chrome.args ignore-urlfetcher-cert-requests \
           --chrome.args autoplay-policy=no-user-gesture-required --chrome.args no-first-run \
           --chrome.args origin-to-force-quic-on=130.192.95.216:8091 \
           --chrome.args ignore-certificate-errors-spki-list=5V2I9iQ0NrsorG7qXJzxuVGyFcla/L4HNMyrzgx7X0E= \
           --chrome.args quic-version=h3 \
           -n 1 \
           --video false \
           --videoParams.createFilmstrip false \
           --visualMetrics false \
           --videoParams.convert false \
           --har har_http3_bw_1_esp_1 \
           --resultDir /sitespeed/results_http3_bw_1_esp_1\
           --pageCompleteCheckStartWait 540000 \
           https://130.192.95.216:8091/controlbar.html --tcpdump

On the server-side, I see 150 requests (the correct values), and also in the pcap collected from browsertime I see that the experiment should consume the entire video. If I try to run the experiment setting video on, I see 9 minutes of video with (almost) 150 requests done.
I didn't understand what could be the problem, anyone can help me?

Thanks a lot,
Gianluca

**Comment by soulgalore** [comment]
I would run tests using `--pageCompleteCheckNetworkIdle` that looks at the network traffic and ends the test when there's silence on the network. That way I think we should be able to get the exact same thing for sure.
