### ISSUE TITLE
[Browsertime] Corrupted video recordings due to missing header information

### ISSUE THREAD

**Issue by afinder-mozilla** [sitespeedio/browsertime#1683]
It seems there is a defect in browsertime that causes some video recordings to not include the header information, which makes the video files corrupt. Having the possibility to change the video format (.mkv for example) before starting the recording itself would help us play the video even though the header information is not included in the file.

Please view the following defect for more information:
https://bugzilla.mozilla.org/show_bug.cgi?id=1670417

**Comment by soulgalore** [comment]
Hi @afinder-mozilla I haven't heard of anything that is broken but if you can help reproduce or help me with the questions I asked in the bugzilla issue:
* Is there a way for me to see the full Browsertime log? I'm thinking if there's something else that goes wrong before the visual metrics error? 
* Can you see a pattern for the tests (a specific use case/URLS) etc? 
* Do the test run on the same machine and have the exact same FFMPEG (just want to verify)?

Before https://github.com/sitespeedio/browsertime/pull/1657 if something broke your testing, the ffmpeg command wasn't  finished correctly so the file was corrupt (but that only happen if you test script throwed an error or if the browser crashed). So check if that PR is included in the version that you run. It was released in 14.6.1 - 2021-10-18.

**Comment by soulgalore** [comment]
So in plain language I think that error happens because of something else that goes wrong in the test. Usually you can see that either by checking the logs (it should be an error before the visual metrics error), check the screenshot (what was actually tested) and check the other metrics that was collected.

**Comment by soulgalore** [comment]
@gmierz could you help me to get some more information here? I sure wanna help out fix it but its hard without more details. Thanks!

**Comment by gmierz** [comment]
Hi @soulgalore, sorry for the delay!

I don't think we have the fix you mentioned in your first comment. I'll update our version and set a need info for myself on the bug to let you know if it's been fixed.

Thanks for the ping!

**Comment by gmierz** [comment]
@soulgalore it looks like the browsertime update is working. I'm gone for the holidays for a couple weeks now though so I'll come back to this with another update in early January. Happy holidays! :)

**Comment by soulgalore** [comment]
@gmierz what's worrying is that the fix was to keep the video if something fails during the tests = something is probably failing in your tests. 
Have a nice holiday :)

**Comment by soulgalore** [comment]
I think this is fixed.
