### ISSUE TITLE
how to use Browsertime from NodeJS with login script?

### ISSUE THREAD

**Issue by dyh333** [sitespeedio/browsertime#1702]
![image](https://user-images.githubusercontent.com/1221313/151115223-c21b7e6d-ba3f-4df3-8a4c-469eca3b65a7.png)

as the title, could give a example how to call login script in nodejs. i only find a simple example using browsertime in nodejs. 

![image](https://user-images.githubusercontent.com/1221313/151115483-83ab7c5f-cf9a-4760-8c23-5dc7085ac2f2.png)

thanks. @soulgalore

**Comment by soulgalore** [comment]
Hi @dyh333 yep sorry that is not documented. Checkout https://github.com/sitespeedio/browsertime/blob/main/lib/core/engine/index.js#L400 - that's the entry point for running scripts.

**Comment by soulgalore** [comment]
Closing let me know if that didn't help.

**Comment by dyh333** [comment]
> Hi @dyh333 yep sorry that is not documented. Checkout https://github.com/sitespeedio/browsertime/blob/main/lib/core/engine/index.js#L400 - that's the entry point for running scripts.

@soulgalore  it is useful. thanks very much.
