### ISSUE TITLE
Connectivity implementation is broken

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#172]
The connectivity implementation is broken right now. TSProxy works fine but when we start it we don't wait for it to start and when we kill, we don't wait for the process to be killed, so running multiple tests in sitespeed.io fails.

I think the easiest way to fix this is:
* Skip the tc implementation for now, just remove it.
* Follow the same pattern as for the BMP Proxy (check the stdout etc). We should be able to use a simple version of the BMPproxy impl and change the part so we use the TSProxy instead.

**Comment by soulgalore** [comment]
I wasn't able to fix this before I'm going offline for (almost) the rest of the week. If you @beenanner or @tobli has some extra time, feel free to give it a shot so we can continue to batch test for releasing beta 1 for sitespeed.io :)

**Comment by beenanner** [comment]
Oops missed this @soulgalore. I can try to take a look this week if you don't get to it. Agreed with removing TC for now. I think pending the work with sltc and gee we can add that back later. I also plan on setting up 4.0 for a few URLs which hopefully will give some feedback on testing some of the other options as well as graphite integration.

**Comment by soulgalore** [comment]
no problem @beenanner I will start with this asap this week and ping you for input :) I think we should keep tc/gee whatever works, I was frustrated that I didn't get the time to fix this. it's cool to have multiple implementations. we also have another blocking task, getting [Geckodriver to work for Firefox](https://github.com/sitespeedio/browsertime/issues/173).
