### ISSUE TITLE
can i generate the result pages using browsertime script

### ISSUE THREAD

**Issue by dyh333** [sitespeedio/browsertime#1737]
### Your question

@soulgalore, hi, can i generate the result pages using browsertime script?

this is generated using cli

![77b9f06389767e3d1d80803783e485d](https://user-images.githubusercontent.com/1221313/156478698-de7b03be-db09-4498-8a20-13e9952b3840.png)

**Comment by soulgalore** [comment]
Hi @dyh333 I'm not sure I fully understand the question?

 If you use Browsertime the outpout is JSON. If you use scripting (https://www.sitespeed.io/documentation/sitespeed.io/scripting/) you can store data/html if you want but the code runs after each iteration. Any reason you can't use sitespeed.io directly? Or like what's your main goal?

**Comment by soulgalore** [comment]
The user didn't get back.
