### ISSUE TITLE
Provide an option so that we don't need to run sudo commands

### ISSUE THREAD

**Issue by julienw** [sitespeedio/browsertime#1747]
### Feature/improvement

When running browsertime on Linux, commands are run using `sudo`. It's a bit surprising and not really nice. It would be good to:
* explain what is executed using `sudo` in the console
* have a possibility to skip these commands at all

**Comment by soulgalore** [comment]
Hi @julienw can you show me how you run? You should be able to run without sudo but if you set connectivity using connectivity engine throttle, you need sudo rights to be able change network interface. That log message _"Changing network interfaces needs sudo rights. Setting connectivity profile .."_ could be tuned though, do you have an idea how we can make that better?

**Comment by soulgalore** [comment]
Ok, hmm, that shouldn't be a thing. Do you have other NodeJS projects installed that works fine? I'll have a try later this weekend.

**Comment by julienw** [comment]
Yeah usually I have no problem running nodejs scripts :)
I'm on a Debian Linux in case this helps, node v16.13.

**Comment by julienw** [comment]
I finally ran it (by mistake: I ran sudo before and forgot :) ) and so got the executed programs in my system logs:

```
Apr  1 17:25:19 torri sudo:   julien : TTY=pts/5 ; PWD=/home/julien/travail/git/browsertime ; USER=root ; COMMAND=/usr/bin/systemd-resolve --flush-caches
Apr  1 17:25:19 torri sudo:   julien : TTY=pts/5 ; PWD=/home/julien/travail/git/browsertime ; USER=root ; COMMAND=/usr/sbin/service dnsmasq restart
```

**Comment by julienw** [comment]
Then this is this code:
https://github.com/sitespeedio/browsertime/blob/d55019ab041ad818295c8d940561217099e18ccc/lib/support/dns.js#L27-L38

**Comment by soulgalore** [comment]
Argh I see, that is my fault. I pushed that some time ago and it would make more sense to only do that when you run throttle, let me fix that to the next release.

**Comment by soulgalore** [comment]
This is fixed now, thanks @julienw for creating the bug!

**Comment by julienw** [comment]
Thanks for the quick fix!
Should we close the issue then?

**Comment by soulgalore** [comment]
Yes wanted you to verify that it worked for you first :)

**Comment by julienw** [comment]
Yep, it's all good now!
