### ISSUE TITLE
Failing URLs that redirects in Chrome with tsproxy

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#175]
The problem is with sites that do redirects. Here are a couple of examples:
http://www.mp.se
http://www.svenskaturistforeningen.se
http://booli.se 
http://byggahus.se
http://www.hhs.se

Errors looks like (we can improve the log):
<pre>
[2016-08-10 00:12:39] http://www.hhs.se generated the following error in Browsertime UrlLoadError: Failed to load http://www.hhs.se
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:10)
    at UrlLoadError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:19:10)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:131:15
From previous event:
    at SeleniumRunner.loadAndWait (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:130:15)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:172:27
From previous event:
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:172:10)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:230:25
From previous event:
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:229:17
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:228:8)
    at /usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at /usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
</pre>

**Comment by soulgalore** [comment]
One part of the problem is the hack we have for 404s:https://github.com/sitespeedio/browsertime/blob/1.0/lib/core/seleniumRunner.js#L100

The URI we get is data:text/html,chromewebdata so it fails. We also need to fix how we handle redirects and when to stop, I don't remember now how that is handled.

**Comment by soulgalore** [comment]
When using the tsproxy I get data:text/html,chromewebdata as the URI, bit it should have been fixed:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1272

We don't use the latest chromedriver though, we should update.

**Comment by soulgalore** [comment]
Tried upgrading but no change. Works fine in Firefox though :)

**Comment by soulgalore** [comment]
It seems to be some problem in our implementation, it works if I run tsproxy standalone with chrome:
<pre>
python tsproxy.py --rtt=200 --inkbps=1600 --outkbps=768 -vvvv
</pre>
And then start Chrome:
<pre>
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --proxy-server="socks://127.0.0.1:1080"
</pre>

And then access http://www.svenskaturistforeningen.se it works.

**Comment by beenanner** [comment]
@soulgalore what's the exact docker run cmd or bin/sitespeed cmd you are using just so I'm using the same for debugging? :-)

**Comment by soulgalore** [comment]
-c cable

and a file with the urls!

**Comment by soulgalore** [comment]
I'm away from my computer today so I can't see the exact command.

**Comment by beenanner** [comment]
Definitely related to the redirects was able to reproduce with http://sitespeed.io/

` bin/browsertime.js --connectivity.profile cable http://sitespeed.io/`

**Comment by beenanner** [comment]
@soulgalore I think this may be related to the selenium-webdriver/proxy setup.

Tested directly in browsertime 1.0 after mapping the tsproxy port to the proxyPort option as I don't think it was going through the proxy before. I create a connectivity branch(https://github.com/sitespeedio/browsertime/commit/cf59357bdbcda645fb9d6705aeaa3ed757c54dc1) if you want to take a look

Running the tsProxy externally and going directly through chrome seems to work fine. Here is the output from tsProxy with -vvvv
```
23:01:18.995 - [23] Incoming connection from ('127.0.0.1', 33758)
23:01:18.995 - [24] Incoming connection from ('127.0.0.1', 33760)
23:01:18.995 - [23] New Socks5 client
23:01:18.996 - [24] New Socks5 client
23:01:18.996 - [23] SOCKS <= 2 byte(s)
23:01:18.996 - [24] SOCKS <= 2 byte(s)
23:01:18.997 - [14] SOCKS => 647 byte(s)
23:01:19.045 - [22] Connecting to 192.185.5.77:80
```

It seems to hang on at the proxy when trying to go through selenium with the proxy turned on.


`bin/browsertime.js --connectivity.profile cable https://sitespeed.io`

```
22:58:40.667 - [1] Incoming connection from ('127.0.0.1', 33640)
22:58:40.667 - [2] Incoming connection from ('127.0.0.1', 33642)
22:59:10.668 - [1] Browser Connection Closed
22:59:10.669 - [2] Browser Connection Closed
22:59:10.764 - [3] Incoming connection from ('127.0.0.1', 33644)
22:59:22.345 - [3] Browser Connection Closed
```

Here is the proxy object from selenium.
```
{ 
  proxyType: 'manual',
  ftpProxy: undefined,
  httpProxy: '127.0.0.1:1080',
  sslProxy: '127.0.0.1:1080',
  noProxy: undefined 
}

```

Though with the fix now anything that goes through the tsProxy doesn't load. :'(

**Comment by beenanner** [comment]
@soulgalore when running tsProxy maunally it's configuring chrome proxy with the socks5 entry vs the http / https entries. Does the chrome and firefox drivers for selenium support just setting a socks5 proxy instead? I was able to confirm what the settings were by hitting  `chrome://net-internals/#proxy` in another tab while the test was trying to connect.

![webdriver-run](https://cloud.githubusercontent.com/assets/723985/17647134/57e3eaa0-61b3-11e6-9829-9378e8970c6c.png)
vs 
![manual-run](https://cloud.githubusercontent.com/assets/723985/17647129/183191be-61b3-11e6-9fbd-dd7b574eda53.png)

**Comment by beenanner** [comment]
https://github.com/SeleniumHQ/selenium/blob/2aa21c1bca3ce863ed19791e20606a007a17dfa7/javascript/firefox-driver/js/proxy.js#L147

Found firefox support and pushed a commit to the connectivity branch to using socks. That appears to have fixed it for firefox, but makes chrome fail. 

[2016-08-14 00:26:05] Error running browsertime BrowserError: unknown error: cannot parse capability: proxy

**Comment by beenanner** [comment]
Just realized you had done this further down for chrome(https://github.com/sitespeedio/browsertime/blob/cf59357bdbcda645fb9d6705aeaa3ed757c54dc1/lib/core/webdriverBuilder.js#L185) I just wasn't passing the `--connectivity.engine tsproxy` to activate it.

**Comment by beenanner** [comment]
Seems that the chrome issue is it's failing on the redirect to https and the handshake.

![ssl-handshake](https://cloud.githubusercontent.com/assets/723985/17647576/d22e8882-61c3-11e6-9e8b-22ec1a89f2d9.png)

Seems to work fine on redirects from http -> http, but not http->https.

**Comment by soulgalore** [comment]
ah sorry it is different in sitespeed.io there you only need to set connectivity, lets change bt to default to tsproxy.

http->https when I tested chrome standalone with tsproxy it worked, that is strange but I get the same with selenium as you.

as for logging for the tsproxy: need to set that up in bt. setting -vvv debugs on stderr from that process, I only tested it locally but didn't push it.

**Comment by soulgalore** [comment]
Pushed -c as alias for connectivity, so it works the same in sitespeed.io & browsertime.

**Comment by soulgalore** [comment]
I was wrong:
http://www.svenskaturistforeningen.se
http://booli.se 
fails also with the proxy standalone.

but:
http://www.mp.se
http://byggahus.se
http://www.hhs.se
works.

Test script:
<pre>
var webdriver = require('selenium-webdriver'),
    chrome = require('selenium-webdriver/chrome');
var chromeOptions = new chrome.Options();

chromeOptions.addArguments("--proxy-server=socks5://localhost:1080");
var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(chromeOptions)
    .build();

driver.get('http://www.hhs.se');
</pre>

**Comment by soulgalore** [comment]
This works now with the latest tsproxy.
