### ISSUE TITLE
visualmetrics-portable throws error for hero times

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1784]
I'll try to hunt down the original video and settings for it.

```
 tile cannot extend outside image
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 116, in crop_im
    return Image.fromarray(
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2949, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2876, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2822, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 827, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
05:54:16.768 - 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 2234, in calculate_hero_time
    target_mask.save(target_mask_path)
AttributeError: 'NoneType' object has no attribute 'save'
05:54:16.768 - '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 2725, in main
    metrics = calculate_visual_metrics(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1962, in calculate_visual_metrics
    hero_timings_sorted = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```

**Comment by soulgalore** [comment]
It's reproducible using:
` ./visualmetrics-portable.py --herodata 1-visualElements.json.gz.failed.json.gz -i 1.mp4.failed.mp4 --orange --force --renderignore 5 --json --viewport --viewportretries 60 --viewportminheight 100 --viewportminwidth 100  -vvvv`

[1-visualElements.json.gz.failed.json.gz](https://github.com/sitespeedio/browsertime/files/8658746/1-visualElements.json.gz.failed.json.gz)

https://user-images.githubusercontent.com/540757/167561940-dd436181-a7ea-4809-8f7d-4501d0b30fcc.mp4

@gmierz do you have the time to have a look? I think the Largest Contentful Paint object is larger than the actual screen in this case.

**Comment by gmierz** [comment]
Actually, the issue is that the region given from the mask is completely outside of the view so we get an empty array (note how the height offset is past the maximum):
```
img.shape: (400, 257, 3)
crop_x: 134
crop_y: 49
crop_x_offset: 18
crop_y_offset: 424
cropped img: []
13:22:46.022 - tile cannot extend outside image
```

I'll add a fix to ensure we don't go past the maximum, and to ignore/skip these masks. It's odd how the original script doesn't raise a failure here when it certainly should.

**Comment by soulgalore** [comment]
Thanks for looking at it @gmierz!  I haven't tested with the original script. I can also change the behaviour of how the metrics is chosen, so that we verify that it is on the screen when we get the sizes, that seems to be a good thing too.

**Comment by gmierz** [comment]
> I can also change the behaviour of how the metrics is chosen, so that we verify that it is on the screen when we get the sizes, that seems to be a good thing too.

That would be much better! I'll only add some checks for boundaries, but otherwise I think having this error thrown is valid and I'll add some custom errors for it.

**Comment by soulgalore** [comment]
@gmierz I think there's missmatch then how things are calculated/recorded? Looking in the visual element file that is generated from the JavaScript that runs in the browser, it says the viewport `"height":640,"width":360` and the element location is `x":26,"y":594` and the size is `height":69," width":188,"`. But in the video I see that the element is pushed out of screen. So the problem is that we do not record the pixels at the bottom of the screen in this case? 


The original script do not throw an error but it calculates it at 0 seconds.

**Comment by gmierz** [comment]
Oh I think what may have happened is that the element was cropped out. The location values get scaled correctly, but still fall out of bounds.

Ok, the 0 value makes sense since it's continuously comparing against either an empty or a blank image.

**Comment by soulgalore** [comment]
There problem on that page is a heading that is one pixel high that somehow fails, and that also makes all other metrics fail. The fix in the PR fixes that only the first broken heading fails.

**Comment by soulgalore** [comment]
I think that fixed the main issues.
