### ISSUE TITLE
Investigate failed rendering of perfcascade from browsertime har output for Firefox

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/browsertime#179]
https://www.verizonwireless.com/tablets/ HAR output fails to work with perfCascade https://micmro.github.io/PerfCascade/ but works fine with a HAR exported directly from firefox

**Comment by soulgalore** [comment]
I filed a PR for the case when the HAR is missing content type https://github.com/micmro/PerfCascade/pull/49

**Comment by soulgalore** [comment]
This can be closed, I could't find anything else than the missing Content Type that you saw @beenanner
