### ISSUE TITLE
ReadyIndex (based on Vesper NSDI'18)

### ISSUE THREAD

**Issue by adnan-ahmed** [sitespeedio/browsertime#1799]
### Feature/improvement

I was wondering if there's a way to measure the interactivity of the web page via browsertime. 
Essentially we want to identify the timing information of the functionality of the elements on the web page. This paper [Vesper' 18](https://www.usenix.org/system/files/conference/nsdi18/nsdi18-netravali-vesper.pdf) proposes a ReadyIndex which is a measure of the visual progress as well as the functional progress of the web page. 
I would be interested in measuring how and when the elements on the web page become functional, i.e. their event handlers and their dependencies across the JavaScript heap and DOM state are defined. 
It would be great if browsertime could measure the visual and functional progress of the web page separately. One way to output the functional progress would be to output the functional state (as defined by the paper) as well as the corresponding timing information of each dom element in the output json.

**Comment by soulgalore** [comment]
Hi @adnan-ahmed I totally missed this issue, sorry. I wonder if "Ready index" actually been implemented somewhere or if it's just an idea? I don't see how it would work without not adding overhead of the tests?

I'm closing this one but please let me know if you have any implementations that you point to. Thanks!
