### ISSUE TITLE
Requested size exceeds screen size error [Firefox]

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#180]
There's bug in Marionette that if you set the Window size bigger than the screen you get a :"Requested size exceeds screen size" Error. That changes the behavior from Firefoxdriver.

There's a fix but hasn't been released in stable yet:
See https://github.com/mozilla/geckodriver/issues/56

**Comment by beenanner** [comment]
@soulgalore that issue has been resolved in 49 is this patch still needed?

**Comment by soulgalore** [comment]
Aha is that fixed now, I haven't tried it out yet. We should still have a more sensible screen size? We are also waiting on a Selenium patch so it will work with Geckodriver to set the Window position.

**Comment by soulgalore** [comment]
Yes tried it out setting the size larger than the screen and it works!
