### ISSUE TITLE
visualmetrics-portable.py:137: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01).

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1807]
Hi @gmierz going through some logs and seen the deprecation warning, can I just change to _Resampling.LANCZOS_ ?

**Comment by gmierz** [comment]
Assuming they are just asking us to change how we use it then there should be no problems with that change. Here's the docs I looked at which suggest this is the case: https://pillow.readthedocs.io/en/stable/reference/Image.html?highlight=Resampling#PIL.Image.Resampling

**Comment by soulgalore** [comment]
This is done I think.

**Comment by amanvastav-del** [comment]
please resize this image in full hd. image size should be 7 meter width and 8 meter length. image should be in 100 dpi.
