### ISSUE TITLE
Can not find "remote.js" file

### ISSUE THREAD

**Issue by ngockute** [sitespeedio/browsertime#183]
Hi,There
I think the program missing "remote.js " file in node_modules , please check again. Thanks so much

**Comment by soulgalore** [comment]
Hey @ngockute ,
could be a that a dependency have problem, which version of Browsertime are you using and can you please share the log where you see the error, that helps us!

Best
Peter

**Comment by soulgalore** [comment]
Closing this, let us know if this was a real problem and we can re-open.
