### ISSUE TITLE
har via chrome-har-capturer?

### ISSUE THREAD

**Issue by paulirish** [sitespeedio/browsertime#184]
Looking at [chromePerflogParser.js](https://github.com/sitespeedio/browsertime/blob/master/lib/support/chromePerflogParser.js) i see a lot that is the same as https://github.com/cyrus-and/chrome-har-capturer

It's built to do the capture as well, but you're working off the same events, just in a log rather than live over the protocol.

Dunno if you want to switch, but figured you wouldn't mind the FYI. :)

**Comment by soulgalore** [comment]
Hey @paulirish we looked at it when we started to do 1.0 a long time ago and at that time the HAR was broken and I kind of like the idea of driving the browsers from Selenium (even though I hate it sometimes hehe). It seems to be fixed now though. 

Me and @tobli have been talking about moving chromePerflogParser.js to a standalone project, but we haven't had time to do it (and don't know if people are interested). But maybe then we could merge with chrome-har-capturer and have the same base, that would be cool.

For me personally it has a higher prio to check if we somehow can use [SpeedLine](https://github.com/pmdartus/speedline/), if you have any suggestions/hints that would be great :)

**Comment by gitgrimbo** [comment]
Hi.  Just registering an interest in moving chromePerflogParser.js to a standalone project.

I've done some very brief tests using both browsertime and chrome-har-capturer (just to see if I can get at the code I need), but I'm using what I assume would be considered internal files/modules.  E.g.:

```
const parser = require("browsertime/lib/support/chromePerflogParser");
const main = require("./main");

function logToHAR(log) {
  const events = log.map(event => event.message);
  return parser.harFromEvents(events);
}

main(logToHAR);
```

and

```
const har = require("chrome-har-capturer/lib/har");
const Page = require("chrome-har-capturer/lib/page");
const main = require("./main");

function logToHAR(log) {
  const id = 0;
  const url = "";
  const chrome = null;
  const fetchContent = false;
  const page = new Page(id, url, chrome, fetchContent);
  log.forEach(entry => page.processMessage(entry.message));
  const pages = [page];
  return har.create(pages);
}

main(logToHAR);
```

**Comment by tobli** [comment]
Hi @gitgrimbo!
We'd definitely be interested in breaking it out, if it's useful to anyone. It is an internal module, but the api (based on our needs in Browsertime) is dead simple. Just one method (+ one for converting Selenium performance log entries). Things to consider if breaking it out might be: logging, how to set options (if it's even needed) and dependencies.

If you could describe your use case a bit more we could see if it is (or can be) a good fit for you.

**Comment by gitgrimbo** [comment]
Hi, my use case is I have a Java-based Selenium test, and currently I'm using [BrowserMob Proxy](https://github.com/lightbody/browsermob-proxy/) to capture HAR files.

This seems to be working absolutely fine, but I wanted to confirm the network results of this test sans-proxy.; make sure that the proxy wasn't affecting the results in any ways I'm not aware of.

So I read up on the [ChromeDriver performance log](https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log) and then searched for log-to-HAR parsers.  Hence arriving at browsertime and chrome-har-capturer.

Also, I don't think BMP supports HTTP2 yet (so all comms via BMP will stay at HTTP1.x), but maybe the ChromeDriver performance log does?

**Comment by tobli** [comment]
Yep, that's exactly why we moved away from BMP. Http2 works great. There are some issues picking up information about h2 push, which looks like it might be Chrome bugs. But all in all it works great. I can start pulling it out to a separate repo, hopefully this weekend.

**Comment by gitgrimbo** [comment]
Excellent, happy to help.

**Comment by soulgalore** [comment]
FYI @gitgrimbo : We have one more problem with H2 checkout https://github.com/sitespeedio/browsertime/issues/246 that we haven't fixed yet.

We used to use BrowsermobProxy too and if I remember correctly some headers is changes, like connection keep alive, but need to go back in issues to remember exactly.

**Comment by tobli** [comment]
I just pushed an initial version to https://github.com/sitespeedio/chrome-har. Took the opportunity to fix some minor bugs along the way, and renamed and simplified the API (I didn't include the trivial unpacking of Selenium log events to messages). Give it a spin!

**Comment by soulgalore** [comment]
We will not move to chrome-har-capturer in a near future, I'll like using Selenium to keep it easy between different browsers.
