### ISSUE TITLE
Unable to setup sitespeed.io on windows

### ISSUE THREAD

**Issue by Pravin7689** [sitespeedio/browsertime#1845]
With node js i am not able to setup locally. Facing below error

request to https://registry.npmjs.org/Browsertime failed, reason: write EPROTO 04250000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:908:

I am using windows os and node version is 8.19.1

**Comment by soulgalore** [comment]
Hi @Pravin7689 try upgrading NodeJS, we stay up to date with NodeJS LTS https://nodejs.org/en/ - so try with NodeJS 16.

**Comment by Pravin7689** [comment]
Tried with 18.9.0 but still facing same issue

**Comment by soulgalore** [comment]
Hi, It seems like people also have problem with 18 https://stackoverflow.com/questions/73630463/write-eproto-b8150000error0a000152ssl-routinesfinal-renegotiateunsafe-legac , can you please try with 16?

**Comment by soulgalore** [comment]
Never got an answer so closing.
