### ISSUE TITLE
Add more options for identifying iframe

### ISSUE THREAD

**Issue by zzhao2010** [sitespeedio/browsertime#1878]
Hi, 
as per [documentation](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#switchtoframeid), switch.toFrame(id) can be done by id ONLY.. What if a scenario where the iframe doesn’t contain id attribute like the snapshot attached? How do I switch to this iframe? I think it is a pretty common use case. So I wanted to request a feature enrichment for iframe specifically such that there are more options that users can choose to identify iframe component with Sitespeed.io out of box without having selenium involved. Thanks.
![image](https://user-images.githubusercontent.com/63174713/204381587-8c777d5a-cd19-4880-973e-75c2a91192d8.png)

**Comment by soulgalore** [comment]
I added a PR where you can use xpath or css selecors.

**Comment by zzhao2010** [comment]
Awesome! Thank you.
