### ISSUE TITLE
Firefox instability with WebPageReplay

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1888]
There's something strange going on with the setup with Firefox. I run tests on bare metal testing the Wikipedia Barack Obama page with a pinned CPU speed on the server. For Chrome the metrics is super stable look at first visual change :
<img width="1180" alt="Screenshot 2023-01-11 at 09 22 21" src="https://user-images.githubusercontent.com/540757/211754639-b174ab31-7f8e-4385-88d8-af3830238553.png">

But with Firefox it looks like this (again focus on first visual change):
<img width="1185" alt="Screenshot 2023-01-11 at 09 23 06" src="https://user-images.githubusercontent.com/540757/211754772-69042520-b603-4f01-bc77-16ecdcc014d0.png">

The settings used is https://github.com/sitespeedio/dashboard.sitespeed.io/blob/main/config/webpagereplay.json and https://github.com/sitespeedio/dashboard.sitespeed.io/blob/main/config/desktop.json

Looking at the tests for Firefox running **without** WebPageReplay it looks much better:
<img width="1181" alt="Screenshot 2023-01-11 at 09 25 29" src="https://user-images.githubusercontent.com/540757/211755330-6dab07cc-0b82-4fff-9a5c-d47b828a6160.png">

@gmierz do you know the best way I can debug it?

**Comment by soulgalore** [comment]
This works much better now, so something has fixed it.

**Comment by gmierz** [comment]
@soulgalore it's possible it was the bug fix we did for visual metrics: https://github.com/sitespeedio/browsertime/pull/1902

The data in the graph above looks bimodal, and the fix above fixed bimodality in a youtube test for us. Here's the bug for that: https://bugzilla.mozilla.org/show_bug.cgi?id=1809874
