### ISSUE TITLE
How to fill some text into DOM  from nodejs?

### ISSUE THREAD

**Issue by kluslulu** [sitespeedio/browsertime#1892]
### Your question

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/12146570/215264145-8e4a1ccb-29fc-4685-9777-3052ba43a0b6.png">

I want to fill some info into DOM from nodejs，I didn't find any document in https://www.sitespeed.io， only find a simple example using sitespeed.io commands. Could you give me a example how to get DOM(eg：click、addText) in nodejs?

Thanks very much.

**Comment by soulgalore** [comment]
Hi @kluslulu here's the documentation for different commands: https://www.sitespeed.io/documentation/sitespeed.io/scripting/

Then you also always run JavaScript directly in the browser using:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#run-javascript

Best
Peter

**Comment by kluslulu** [comment]
Hi @soulgalore, thanks so much for your reply.

I saw these two documents，but they need to be executed through the command line or docker like this: "sitespeed.io login.js --multi http://xxx".

I want to use nodejs directly, like this(main.js):
`
...
async function run() {
const sitespeed = require('sitespeed.io')
const res = await sitespeed.run({
  urls: ['http://xxxx'],
  ...
})
// how to login?
}
run()
...

`

Then, I want to get the result by executing the node command “node main.js”  instead of ‘sitespeed.io’ commands~
What should I do for login?

Thanks very much again~

**Comment by soulgalore** [comment]
Hi @kluslulu sorry there's no good example for that in the documentation. It should be something like this:

```JavaScript
const path = require('path');

 const result = await sitespeed.run({
      urls: [path.resolve('yourscriptingfile.js'), 
      multi: true,
      browsertime: {
     ....
```

Best
Peter

**Comment by kluslulu** [comment]
Hi @soulgalore ：thanks for your reply 😊

I tried this and it worked ! This is so helpful to me！

Thanks very much～
