### ISSUE TITLE
Browsertime can not collect all google core vital metrics such as LCP,CLS, TBT

### ISSUE THREAD

**Issue by tlqiao** [sitespeedio/browsertime#1893]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [ ] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.apple.com

### What are you trying to accomplish

Run the browsertime with cli and choose the safari as the browser, the performance result does not include LCP,CLS, TBT metrics. here is running command.
browsertime https://apple.com -n=1 --browser=safari

### What browser did you use?

Safari Mac OS

### How to reproduce

```shell
run the command browsertime https://apple.com -n=1 --browser=safari.
```

### Relevant log output

```shell
taoli@taolis-MacBook-Pro ~ % browsertime  https://apple.com -n=1 --browser=safari                  
[2023-01-30 17:12:49] INFO: Running tests using Safari - 1 iteration(s)
[2023-01-30 17:12:50] INFO: Testing url https://apple.com iteration 1
[2023-01-30 17:13:17] INFO: https://apple.com TTFB: 0ms, FCP: 1.96s, DOMContentLoaded: 2.02s, Load: 14.06s
[2023-01-30 17:13:17] INFO: Wrote data to browsertime-results/apple.com/2023-01-30T171249+0800

As you can see, only can collect FCP metric, other metrics can not collect. why.
```

**Comment by soulgalore** [comment]
Hi @tlqiao Safari hasn't implemented any of those metrics, the only user experience metric in Safari so far is First Contentful paint (FCP). that the Wikimedia performance team paid for. The best way to try to fix that is to add an issue for WebKit (if it doesn't already exists) in https://bugs.webkit.org.

Best
Peter

**Comment by tlqiao** [comment]
Thanks for updating.
