### ISSUE TITLE
_initiator_detail.stack.parent properties missing from the HAR files

### ISSUE THREAD

**Issue by taavikalvi** [sitespeedio/browsertime#1901]
### Feature/improvement

Hey,

I noticed that stack.parent properties are currently missing from the HAR files generated by browsertime.

But if I use "Copy all as HAR" from the network tab in Chrome, I see all of them.

My Chrome version: 109.0.5414.119

I guess, this is related to the following Chrome update: https://developer.chrome.com/blog/new-in-devtools-107/#har
Bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1343185

Here's an example of how it looks like:

```
      {
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [],
            "parent": {
              "description": "Image",
              "callFrames": [
                {
                  "functionName": "r",
                  "scriptId": "55",
                  "url": "https://www.googleadservices.com/pagead/conversion/123456/?random=1676431475187",
                  "lineNumber": 0,
                  "columnNumber": 759
                },
                {
                  "functionName": "",
                  "scriptId": "55",
                  "url": "https://www.googleadservices.com/pagead/conversion/123456/?random=1676431475187",
                  "lineNumber": 0,
                  "columnNumber": 991
                },
                {
                  "functionName": "",
                  "scriptId": "55",
                  "url": "https://www.googleadservices.com/pagead/conversion/123456/?random=1676431475187",
                  "lineNumber": 0,
                  "columnNumber": 2136
                }
              ]
            }
          }
        },
```

Technically those parents can also be nested like this: initiator.stack.parent.parent.parent etc

Is it somehow possible to add those stack parents to HAR files generated by browsertime?

**Comment by soulgalore** [comment]
Hi @taavikalvi ah thanks.  The HAR is created using https://github.com/sitespeedio/chrome-har and I think the same is created under the _initiator field, checkout https://github.com/sitespeedio/chrome-har/blob/main/index.js#L208-L218

**Comment by taavikalvi** [comment]
Thanks for this. I already figured it out. Here's the solution that describes it: https://github.com/cyrus-and/chrome-har-capturer/issues/94

**Comment by soulgalore** [comment]
I think this was working ok, please let me know if its still an issue and can re-open.
