### ISSUE TITLE
domElements no longer in paginfo summary?

### ISSUE THREAD

**Issue by bdekoz** [sitespeedio/browsertime#1919]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

any

### What are you trying to accomplish

It looks like 17.2.1 is no longer putting domElements into the pageinfo part of the JSON payload (versus 16.8.1), but instead putting this data into each iteration's data fields . Given the value does not seem to change, I'm curious: is this change deliberate, and if so, I'm curious as to why?

Thanks.

### What browser did you use?

Firefox (111.0.1) on linux, Chrome (111)

### How to reproduce

```shell
Run browsertime, generate browsertime-results JSON file for a URL (https://marvel.wikia.com/wiki/Black_PantherP). In this file, look for where the domElements data is found.
```

**Comment by soulgalore** [comment]
Hi @bdekoz I don't remember doing that change so I wonder then if its a bug, let me have look tonight, thanks for reporting!

**Comment by soulgalore** [comment]
Hi again @bdekoz I did a quick check and I'm not sure how it worked in 16, can you show me? The pageinfo data is collected using https://github.com/sitespeedio/browsertime/tree/main/browserscripts/pageinfo and then for each iteration we get that data. It should be put in the iteration part on the JSON and then in the statistics if the metric is numeric so we can get a min/median/max.  If I check I have three domElements (if I run three iterations) and then one domElements on the statistics part of the JSON.

**Comment by bdekoz** [comment]
My fault! Sorry about this. I do see statistics/pageinfo/domElements as you describe.
