### ISSUE TITLE
Cannot read properties of undefined (reading 'startTime')"" error on testing a website

### ISSUE THREAD

**Issue by rsrahulsingh** [sitespeedio/browsertime#1922]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [ ] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

sitespeed.io

### What are you trying to accomplish

I am testing sitespeed.io on a linux instance and I am using sitespeedio docker for the entire setup.
The command I ran is :
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:26.1.0 <urls.txt> --slug chrome_browser_test --graphite.addSlugToKey true -n 1 --graphite.host=<private_ip> --grphite.port 80 -b chrome

I have provided multiple urls in the url text file and it is giving the following error for some of the urls after the command is executed.

"performance": {
"firstContentfulPaint": "Cannot read properties of undefined (reading 'startTime')",
"longTasks": "Cannot read properties of undefined (reading 'startTime')"
}

Is there anything we need to configure to set the startTime?

I have also scheduled a Jenkins job to run the docker command in every 3 hrs and I have observed that the error is not produced in some of the runs. If it was a problem with page, it should be a consistent right?

The metrics that are not displayed are FirstVisualChange and LastVisualChange, attaching the screenshot below,
image.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/42830023/228403655-0baccceb-4f97-4a54-89ad-3158a0727970.png">

The issue is intermittent. Can you please suggest on next steps.?

### What browser did you use?

Chrome

### How to reproduce

```shell
The command I ran is :
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:26.1.0 <urls.txt> --slug chrome_browser_test --graphite.addSlugToKey true -n 1 --graphite.host=<private_ip> --grphite.port 80 -b chrome
```

**Comment by soulgalore** [comment]
Hi @rsrahulsingh seen a couple of these now, it seems Chrome doesn't report first contentful paint. However in your graph where you show the first visual change (that comes from the video) it seems that something else is wrong. If you access the result, what do the video and the filmstrip look like?

**Comment by soulgalore** [comment]
Didn't get a response.
