### ISSUE TITLE
Fail to run browsertime using firefox

### ISSUE THREAD

**Issue by frmok** [sitespeedio/browsertime#195]
I am using 1.0.0-beta.6 get the following error message when running it with firefox. I have no problem when running with chrome.

```
Error running browsertime BrowserError: Unable to parse new session response: {"error":"unknown error","message":"Failed to unzip profile"}
```

**Comment by soulgalore** [comment]
Hey @frmok ,
what OS and Firefox version are you using?

Best
Peter

**Comment by frmok** [comment]
I am using Windows 10, and the firefox version is 48

**Comment by beenanner** [comment]
Closing. I tested and this works with the latest version of Firefox(49.0.2) and browsertime(1.0.0-beta.9).
```
\Users\Beenanner\Documents\GitHub\browsertime [(v1.0.0-beta.9) +1 ~0 -0 !]> node .\bin\browsertime.js -b firefox -n 1 http
//www.sitespeed.io/
2016-11-04 22:06:10] Running firefox for url: https://www.sitespeed.io/
2016-11-04 22:06:10] Testing url https://www.sitespeed.io/ run 1
2016-11-04 22:06:17] 8 requests, 88.25 kb, DOMContentLoaded: 0.53s, Load: 1.s, rumSpeedIndex: 0.54s
2016-11-04 22:06:17] Wrote data to browsertime-results\www.sitespeed.io\2016-11-04T220609-0400
```

@frmok I would highly recommend switching to the docker container if possible as it will standardize everything and avoid host machine issues.
