### ISSUE TITLE
Checks invoking extraWait() ignore --pageCompleteCheckStartWait, always take default 5000ms minimum

### ISSUE THREAD

**Issue by jordan-angold-sophos** [sitespeedio/browsertime#1984]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://sitespeed.io

### What are you trying to accomplish

I'm trying to use the `--pageCompleteCheckStartWait` parameter to control the delay before the first check of the page-complete condition (in an SPA).

Browsertime ignores this setting, probably because https://github.com/sitespeedio/browsertime/blob/main/lib/core/seleniumRunner.js#L134 refers incorrectly to `this.options.beforePageCompleteWaitTime`, which isn't actually an option and is therefore always undefined and therefore replaced with the default of 5000ms.

### What browser did you use?

Chrome

### How to reproduce

```shell
Use a script like:

context.log.info("A");
await commands.wait.byPageToComplete();
context.log.info("B");
await commands.wait.byPageToComplete();
context.log.info("C");

With the documented delay setting:
docker run ... --browsertime.pageCompleteCheckStartWait 100
```

### Log output

```shell
[2023-08-28 22:45:55] INFO: [browsertime] A
[2023-08-28 22:46:00] INFO: [browsertime] B
[2023-08-28 22:46:05] INFO: [browsertime] C
```

**Comment by soulgalore** [comment]
Ah so you don't want to wait any time at all? I think it depends on how you define when your page has finished loading, can you share a concrete example so I can see how it works?

**Comment by jordan-angold-sophos** [comment]
@soulgalore I would like to provide PRs for this issue and #1983 , but when I push, I get `ERROR: Permission to sitespeedio/browsertime.git denied to jordan-angold-sophos` . Is this a repository setting you can change, or am I doing something wrong?

**Comment by soulgalore** [comment]
Nothing more happened here so closing.
