### ISSUE TITLE
How to collect fetch/xhr requests in the network

### ISSUE THREAD

**Issue by Liu6625** [sitespeedio/browsertime#1991]
### Your question

How to collect fetch/xhr requests in the network, even the specific information  data of the request, I need to distinguish it from other resources

**Comment by soulgalore** [comment]
Hi @Liu6625 so you don't get it in the HAR file? I think then you probably need to wait longer before the test to end. I would try to run your test with `--pageCompleteCheckNetworkIdle`.

Best
Peter

**Comment by soulgalore** [comment]
Didn't get a response so closing.
