### ISSUE TITLE
When runMultiple is running, will the script execution time in preScript and postScript be counted in the recorded time?

### ISSUE THREAD

**Issue by Liu6625** [sitespeedio/browsertime#2044]
### Your question

When runMultiple is running, will the script execution time in preScript and postScript be counted in the recorded time? I found that the loading time seems to be longer after adding the pre-script.

**Comment by soulgalore** [comment]
Hi @Liu6625 what do you mean as recorded time, can you show me?

**Comment by soulgalore** [comment]
Didn't get a response so closing.
