### ISSUE TITLE
Calcuation of timings.fullyLoaded 

### ISSUE THREAD

**Issue by worenga** [sitespeedio/browsertime#215]
Hey,  this is more of  an support question i guess

i discovered your tool a few days ago and i love it. It is perfect for my current use case (studying the effect of http/2 server push and evaluating different push heuristics) 

However, when looking at the metrics in the browsertime.json i found that there is the 
.statistics.timings.fullyLoaded Metric.

I was woundering where this metric is calculated but did not find any code (grepping for fullyLoaded did not yield anything useful + not that familiar with node)

How is this metric defined?

**Comment by worenga** [comment]
Never mind, found the code. Instead of grepping I should have looked at the filenames: 
The code can be found under browserscripts/timings/fullyLoaded.js for future reference

**Comment by soulgalore** [comment]
@worenga but it isn't perfectly clean, if the site you are measuring has more than the limit of the ResourceTiming API, it will give false values as found by @beenanner . We should add  a ticket for that + we have a PR where we try to fix it but I haven't tested it too much yet. https://github.com/sitespeedio/browsertime/pull/196

**Comment by worenga** [comment]
@soulgalore Thanks for the hint. This issue may affect the RUM-SpeedIndex as well right (Allthough its less probable)?

Since i am using a modified Chromium version anyway i might be able to recompile the browser with a higher default value if i manage to find that setting.

**Comment by worenga** [comment]
BTW: Just looked at the source for chromium and its default buffer is set to 150.

**Comment by soulgalore** [comment]
I haven't checked the impl for RUM-Speedindex but it should only affect you if all these 150+ requests is shown in the viewport :)
