### ISSUE TITLE
Run Chrome browser on Iphone

### ISSUE THREAD

**Issue by 2343909** [sitespeedio/browsertime#2156]
### Your question

Is there a way to run tests using Chrome browser on the iPhone? This would be helpful if we can do this since Safari does not provide that many perf metrics at all.

**Comment by soulgalore** [comment]
Hi @2343909 no there is not. Chromedriver that drives Chrome do not have support for iOS. Best case is that if Google can make their own Chrome version (not based on WebKit) and release it in EU, then hopefully Chromedriver can drive Chrome.
