### ISSUE TITLE
Convert the video to HTML5 compatible output

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#228]
Today our video works pretty good and we can soon release it.

We should add one extra step where we use the original video and converts it to HTML5 compatible videos (and add more compression to the current version). We should also drop that first orange frames. 

If we haven't configured Browsertime to remove the videos, we can run the extra steps to converts it to HTML5 compatible videos.

We need:
* Examples how to convert the videos using FFMPEG and verify that it works (at least 2 versions?)
* add the hook in Browsertime to run the extra convert.

How can you help us? If you used FFMPEG before and can give us a couple of oneliners, that would be awesome! We can do the integration with the code :)

Right now we record xvfb to a mp4 that really only works in Chrome but we wanna make sure it works in Chrome/Firefox/Safari and Edge.

**Comment by walterebert** [comment]
Here is an example to get a cross-browser MP4 format:

```
ffmpeg -i input.mp4 -c:v libx264 -pix_fmt yuv420p -profile:v main -crf 18 -movflags faststart output.mp4
```

`pix_fmt` sets the pixel format for chroma subsampling. yuv420p is supported by all browsers

`profile:v` sets a standard set of MP4 capabilities. Profile "main" is a safe bet. Profile "high" could be used for high resolution videos.

`crf` sets the constant rate factor. This way you can change the quality. Values can be between 0 (=lossless) and 51 (=worst). I usually set a value between 18 and 23.

`movflags` sets position of the metadata block (aka moov atom). "faststart" moves it to the beginning of the file so the video can be started even if the file is still downloading.

**Comment by soulgalore** [comment]
Hey @walterebert thank you and thanks for the explanation!!! You will get extra special mention in the release notes :)

**Comment by soulgalore** [comment]
Release coming later today/tomorrow!
