### ISSUE TITLE
Using urls.txt with --video only shows 1 video for all pages tested in Browsertime.

### ISSUE THREAD

**Issue by dylangrafmyre** [sitespeedio/browsertime#237]
Just wondering if it is the expected  behavior for using video recording with `urls.txt` to only render the video of the last page tested for all url page reports under Browsertime?

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --video --speedIndex -c cable urls.txt`

![image](https://cloud.githubusercontent.com/assets/8039859/20908101/7a59a2b8-baf6-11e6-8f7a-3629dde513ba.png)
![image](https://cloud.githubusercontent.com/assets/8039859/20908127/a2e64ed4-baf6-11e6-91a8-5b86990384e3.png)

**Comment by soulgalore** [comment]
Hey @dylangrafmyre ,
no this is a bug, thanks for reporting, see if we can fix this tonight.

Best
Peter

**Comment by beenanner** [comment]
Hey @dylangrafmyre,
We just release 4.1.3 which hopefully resolves this issue. Feel free to check it out and let us know if you have any issues.

Thanks,
Jonathan

**Comment by dylangrafmyre** [comment]
@beenanner Thanks so much! Working great! Each video reflects the url that was tested.
