### ISSUE TITLE
Order for timings using Chrome in HAR

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#240]
Checkout the example waterfall graph: http://examples.sitespeed.io/4.2/2016-12-13-12-50-13/pages/en.wikipedia.org/wiki/Main_Page/1.html

The second request in prio ow and an image and the browser do that after the css/js, but the graph has it as number 2. We need to investigate if the timestamp is the same in browsertime or if it is the PerfCascade that needs a bug fix.

**Comment by soulgalore** [comment]
IT's the same with HAR Viewer so we probably need a tweak in BT.

**Comment by soulgalore** [comment]
OK, it looks like this. The first request "should" happen after the other one. 

<pre>
"cache": {},
        "startedDateTime": "2016-12-13T12:50:17.960Z",
        "_requestWillBeSentTime": 85199.729455,
        "_wallTime": 1481633417.95869,
        "_requestId": "233.3",
        "_frameId": "233.1",
        "_initiator": "https://en.wikipedia.org/wiki/Main_Page",
        "_initiator_line": 11,
        "pageref": "page_1",
        "request": {
          "method": "GET",
          "url": "https://en.wikipedia.org/w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector",
          "_timestamp": 85199.729455,
</pre>

And this is the one that is before the other one:
<pre>
"startedDateTime": "2016-12-13T12:50:17.959Z",
        "_requestWillBeSentTime": 85199.729817,
        "_wallTime": 1481633417.95905,
        "_requestId": "233.5",
        "_frameId": "233.1",
        "_initiator": "https://en.wikipedia.org/wiki/Main_Page",
        "_initiator_line": 93,
        "pageref": "page_1",
        "request": {
          "method": "GET",
          "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Altgens1970s.jpg/100px-Altgens1970s.jpg",
          "_timestamp": 85199.729817,
</pre>

Need to check the code for all those extra timings.

**Comment by beenanner** [comment]
Possible related to: https://github.com/sitespeedio/browsertime/commit/82112b9c77164a8961d93cfb49d916d4b4bc4384

**Comment by soulgalore** [comment]
thanks, and the original issue #102

**Comment by soulgalore** [comment]
released and fixed.
