### ISSUE TITLE
Sometimes DNS/Connect/TLS is categorized as blocked for the main document in Chrome

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#245]
<img width="959" alt="screen shot 2016-12-20 at 13 45 39" src="https://cloud.githubusercontent.com/assets/540757/21350982/a4bfa8d4-c6ba-11e6-8de0-66c4fc1c921c.png">

**Comment by soulgalore** [comment]
Running this standalone on my Mac can't reproduce it:
`bin/browsertime.js --experimental.dumpChromePerflog -n 1 https://en.wikipedia.org/wiki/Main_Page -b chrome`

but running in Docker I get it:
<pre>
docker run --privileged --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime --video --speedIndex --experimental.dumpChromePerflog -n 1 https://en.wikipedia.org/wiki/Main_Page -b chrome
</pre>

See Chrome log:
https://gist.github.com/soulgalore/4b0f6c6625b808b7a74120041c02daae

**Comment by soulgalore** [comment]
@beenanner when you have time, can you test if it works on Ubuntu and it's a Docker only thing?

**Comment by beenanner** [comment]
@soulgalore the top is on Ubuntu and the bottom is within Docker. They appear the same to me? What are you seeing on Mac?

![ubuntu-vs-docker](https://cloud.githubusercontent.com/assets/723985/21375998/91a63048-c6ff-11e6-9950-052e58200cf8.png)

**Comment by soulgalore** [comment]
Yes good!
I get connecting and or dns for that first asset, not blocked:

<img width="1271" alt="screen shot 2016-12-21 at 04 58 37" src="https://cloud.githubusercontent.com/assets/540757/21377002/34265282-c73a-11e6-92ef-dfea0e1c3021.png">

**Comment by soulgalore** [comment]
I don't think this a bug on our side.
