### ISSUE TITLE
Missing TLS/connect etc time for assets for Chrome

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#246]
Checkout the HAR for Wikipedia:

![wait](https://cloud.githubusercontent.com/assets/540757/21354526/c2e19790-c6ca-11e6-80ad-a0b7aaa9118e.png)

We are using H2 and the first assets in the domain upload wait for the connect to happen but not the next ones, so something is wrong how we calculate the start time.

In the example I tested https://en.wikipedia.org/wiki/Main_Page

**Comment by tobli** [comment]
Could you dump a perflog and attach to the issue?

**Comment by soulgalore** [comment]
https://gist.github.com/soulgalore/12e83a6e79f27978f93ba4b32e520db1

**Comment by beenanner** [comment]
@soulgalore possible regression from dcdae9760f140570ad0e8d0c098991d0bf61c158?

**Comment by soulgalore** [comment]
yes could be! maybe we need some kind of combination of that?

**Comment by soulgalore** [comment]
@beenanner I think dcdae9760f140570ad0e8d0c098991d0bf61c158 is part of the solution: the start time is right now but we should add blocking time from that start to the one calculated in  dcdae9760f140570ad0e8d0c098991d0bf61c158 ?

**Comment by beenanner** [comment]
Was this on Mac @soulgalore? I can't seem to reproduce on my Linux machine. Are you able to reproduce one of these and attach the HAR here from within a docker run?

**Comment by beenanner** [comment]
Never mind finally got one :-p

**Comment by beenanner** [comment]
@soulgalore checkout the "stalled-time" branch. Might be getting closer, but definitely needs some testing. I still feel like the perflogs from chrome is missing some data we need.

![stalled-time-har-vs-chrome-network](https://cloud.githubusercontent.com/assets/723985/21447671/21c6d89c-c8a6-11e6-8202-2f5b67a1ccce.png)

**Comment by soulgalore** [comment]
@beenanner cool! I wonder if the area that in devtools (the unfilled rectangles before the downloads) should be block time in our case? Or what is that?

**Comment by soulgalore** [comment]
and we need to find more sites where we can test.

**Comment by soulgalore** [comment]
I think this is the end goal?
<img width="857" alt="screen shot 2016-12-26 at 22 29 04" src="https://cloud.githubusercontent.com/assets/540757/21486771/ce34ebfc-cbba-11e6-848d-0409cd39b1e7.png">

But the hack I did isn't nice (if the connection is reused and we have a blocking time for the second request, keep that and add it as block for all request on the same connection id and set the same start time), we should be able to get the info from the trace log instead.

**Comment by soulgalore** [comment]
No that is not correct. Let me make another run tomorrow.

**Comment by soulgalore** [comment]
No I cannot find a way to fix this in a hacky and unreliable :(

**Comment by soulgalore** [comment]
Is this still a issue? Let us re-open it if that's the case.
