### ISSUE TITLE
Support for additional webdriver options through the toplevel config file

### ISSUE THREAD

**Issue by sridharangopal** [sitespeedio/browsertime#253]
Hi, I am trying to see if I can use this tool to drive tests on Saucelabs. It works but I am not sure how to send in additional config items like platform, version, tunnel-identifier, parent-tunnel etc.
Was wondering, just like the browsertime.selenium.url option, is it possible to add the additional items into the same object?

**Comment by soulgalore** [comment]
Sorry I totally missed this one. See https://github.com/sitespeedio/sitespeed.io/issues/1495#issuecomment-284872363 

Let me know if there's a way that can make sure saucelabs and the like give us the same instance etc so metrics between runs are the same, the we can re-open.

**Comment by sridharangopal** [comment]
Hi, Yes your assumptions from browserstack (referring back to sitespeed#1495) apply to Sauce as well. But we have a pretty big selenium internal setup where I can control which machine it goes to etc.

**Comment by soulgalore** [comment]
@sridharangopal cool, ok can you help me exactly what you need and if you have a couple of examples, so we can try it out? either we reopen this or we can create a new one. 
Best
Peter
