### ISSUE TITLE
Create whitelist to filter 3rd party user timing out of resulting HAR

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/browsertime#257]
Noticed today that google ads now have user timings being picked up in the results. The issue is that they are setting unique IDs on the marks which when combined with sitespeed.io and graphite it  slowly fills up the entire disk. :'( My thought is we should implement a whitelist where a user can specify a regex to only add timers that match. For a first pass we could just accept an array of userTimings and expand to the regex if use-cases arise. The other option is since this only really affects graphite we could push this change downstream into sitespeedio code base since it's really only necessary to filter.

**Comment by soulgalore** [comment]
Keep this as a reminder of what it looks like:
![usertimings](https://cloud.githubusercontent.com/assets/540757/21919655/4b9cd4ca-d95c-11e6-992f-8bc78c866044.png)

**Comment by soulgalore** [comment]
Fixed this for now in sitespeed.io: https://github.com/sitespeedio/sitespeed.io/commit/12a4eb30bef38cbb0d1f1053606027ebe7f86f15

**Comment by jpvincent** [comment]
Had the problem too, thanks for the fix
I was about to prefix all my performance.mark calls anyway, because I start to see 3rd parties using it. Since it's a global chanel, prefixing it looks like a good option, so on the siteSpeed side, if we could allow to whitelist with a RegExp or simply a prefix, that would be fantastic

**Comment by soulgalore** [comment]
@jpvincent I only fixed it for the User Timings we fetch in Browsertime, seen that the WPT API will still keep them, so that needs to be fixed. Also @beenanner long term fix will be perfect however  muting the goog_* will be there forever I think, if they don't change.

**Comment by jpvincent** [comment]
you're right, I'm still polluted.
A Whitelist with a prefix or a RegExp at the sitespeed.io level would be perfect for my use case

**Comment by soulgalore** [comment]
I can make a quick fix for WPT to just skip those timings maybe tonight, since there's no use at all for someone except Google? And then we take on the better solution later on. Best case would be if someone at Google could fix the origin of the problem :)
