### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yuriyzinchenko** [sitespeedio/browsertime#260]
Is it possible to execute browsertime in code?

**Comment by tobli** [comment]
Hi @yuriyzinchenko 
If the question is if you can use browsertime as a library, then absolutely. That's exactly what [sitespeedio/coach](https://github.com/sitespeedio/coach) and [sitespeedio/sitespeed.io](https://github.com/sitespeedio/sitespeed.io) does. Check https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/browsertime/analyzer.js#L73 for one example.

/Tobias

**Comment by yuriyzinchenko** [comment]
Thanks @tobli , it's exactly what i want.
