### ISSUE TITLE
Ability to set Firefox Preferences

### ISSUE THREAD

**Issue by worenga** [sitespeedio/browsertime#268]
Similar to `--chrome.args` we should add a command line option to allow advanced users to specify custom firefox preferences such as `network.http.spdy.enabled.http2`. Surely a user can hack 
https://github.com/sitespeedio/browsertime/blob/master/lib/core/webdriver/firefox.js#L7
for her needs, but it still inflexible when trying multiple configurations.

**Comment by soulgalore** [comment]
Good idea, let me fix that tonight.

**Comment by tobli** [comment]
This will be in the next release! 🎉
