### ISSUE TITLE
Fetch Chrome timeline

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#270]
We should redo the dumpChromePerflog so that we could both dump the perflog as today + add the  devtools timeline log, so that you as a user can drag/drop it into devtools in Chrome and check the timeline, that would be super cool.

**Comment by worenga** [comment]
I think that would be a nice convenience feature. However, from experiences i can tell that the entire performance log can be very large (e.g., the first 4-5s of gmail loading are about 25Mb of JSON, the first 10s of Facebook are roughty 50Mb etc.). Hence, if possible, i'd prefer it to be opt-in, as for some analysis the benefit of having the entire timeline data seems little.

**Comment by soulgalore** [comment]
yep I agree. I did some tests, I got it to work but not 100%. The thing is that the same code sometimes generated timeline.json that you can import into Chrome and sometimes it doesn't work. One thing missing is setting how often to get traces like https://github.com/WPO-Foundation/webpagetest/blob/9e2ad5add9b00efa36cb19eb47df3401aef681dd/agent/browser/chrome/extension/wpt/chromeDebugger.js#L246 and https://github.com/GoogleChrome/lighthouse/blob/59bc945ef7e22507de9db6b38aaef7c7133436a2/lighthouse-core/gather/driver.js#L577 not sure how do that from Selenium to the Chromedriver.

**Comment by soulgalore** [comment]
released
