### ISSUE TITLE
Increase in server response time for second view (Chrome only)

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#280]
I've been testing out the new Docker network setup to be able to have better connectivity. Everything looks fine except that second view and login takes a large hit on server response time:
<img width="1259" alt="screen shot 2017-02-24 at 10 00 15 am" src="https://cloud.githubusercontent.com/assets/540757/23297201/e0584134-fa78-11e6-9ed4-3814e1dd230f.png">

When we access the page as a first view it looks like this:
<img width="1036" alt="screen shot 2017-02-24 at 10 04 19 am" src="https://cloud.githubusercontent.com/assets/540757/23297222/f877ac64-fa78-11e6-93e8-40bcfae5d885.png">

And for second view:
<img width="982" alt="screen shot 2017-02-24 at 10 03 19 am" src="https://cloud.githubusercontent.com/assets/540757/23297218/f3421d1a-fa78-11e6-80a0-b51115bd4ba8.png">

Could it be that we are still downloading assets when we access the next page? Should we add a wait before we go to the next page? Checked and we have a 1500 ms wait until the next access.

**Comment by worenga** [comment]
Can you pinpoint how to reproduce this? Also what browser is being used here?
What exactly do you mean with second view? The second browsertime run?

**Comment by soulgalore** [comment]
If you use the latest Docker container and setup different networks something like this:
<pre>
docker network create --driver bridge --subnet=192.168.34.0/24 --gateway=192.168.34.10 --opt "com.docker.network.bridge.name"="docker2" cable
tc qdisc add dev docker2 root handle 1: htb default 12
tc class add dev docker2 parent 1:1 classid 1:12 htb rate 5mbit ceil 5mbit
tc qdisc add dev docker2 parent 1:12 netem delay 28ms
</pre>
(when you need to remove it you can do that  with <code>docker network rm cable</code>).

Then when you run the container just add <code>--network cable</code> with your Docker command and the container will use that network.

<pre>docker run --privileged --shm-size=1g --network cable --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime -n 1 -c cable --video --connectivity.engine external --speedIndex https://www.sitespeed.io/ </pre> 

With second view I mean accessing another URL, you can pre-warm the browser cache with <code>--preURL</code>. So instead of the old repeat view (where you access the same URL two times) you can first access one URL and then measure the next URL you test.

**Comment by soulgalore** [comment]
And we been running it on https://dashboard.sitespeed.io/ for the last 1-2 days to check how it works.

**Comment by soulgalore** [comment]
It seems to only happens for Chrome, FF looks ok.

**Comment by soulgalore** [comment]
Been looking into and I think it is like this: Chrome report the server response time right but Firefox report that completely wrong (in Navigation Timings). 

Then we have a problem on Wikipedia on some pages (check the Obama page) that make the diff in first/second view higher (look ok on the Facebook page). I'll link the Phabricator task here next week..
