### ISSUE TITLE
Add flags for filmstrip images quality and size from Visual Metrics

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#300]
We have the capability in VisualMetrics so best case scenario we could just add a flag in Browsertime to turn on to get the images.

**Comment by soulgalore** [comment]
We already produce the images today! Then let us add a flag for the quality (today 75) and the size (the size is 400x400 by default).

**Comment by kkopachev** [comment]
Would be also great to have an option to not store all these images. In my case, video is ~400kB, images are ~800kB. If page load time is big enough, we end up with a lot of images. They are then uploaded to S3 as well.

**Comment by soulgalore** [comment]
@kkopachev yes good, I think we prepared for that but missed making it configurable, I agree that we should be able to turn them off, lets fix that for the next release.

**Comment by soulgalore** [comment]
This was fixed a couple of releases ago see
```
--videoParams.filmstripFullSize  Keep original sized screenshots. Will make the run take longer time                 [boolean] [default: false]
  --videoParams.filmstripQuality   The quality of the filmstrip screenshots. 0-100.                                                 [default: 75]
  --videoParams.createFilmstrip    Create filmstrip screenshots.                                                        [boolean] [default: true]

```
