### ISSUE TITLE
Create extension to handle clean cache and request headers

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#305]
Now when both Firefox and Chrome supports the same [browser extension API](https://www.smashingmagazine.com/2017/04/browser-extension-edge-chrome-firefox-opera-brave-vivaldi/) we should build an extension that can:
 * Clear all caches
 * Set request headers

Anything else?

**Comment by worenga** [comment]
Can we blacklist domains/urls with this?

**Comment by soulgalore** [comment]
I think WebPageTest did that for Chrome but if many request was blocked, Chrome suffered so that it had an negative impact on metrics, we should be able to find that issue.

**Comment by tufandevrim** [comment]
This feature is needed for us to upgrade to 4.x from 3.x. We test our sites with logged in and logged out use cases along with some other custom headers.

**Comment by soulgalore** [comment]
We gonna release 5.0 next week, let see if we can squeeze in a fix for request headers since upgrading from 3.x is crucial. Let us know @tufandevrim if you can help us test it.

**Comment by tufandevrim** [comment]
I will be so happy to help to test this. One of the most used options in `docker sitespeed.io 3.x` command line we used was `--requestHeaders`. I love to see this coming back with 5.x soon. Let me know how I can help to get this option added to configuration again.

**Comment by soulgalore** [comment]
@worenga let us add blocking at the same time, I'll ping you next week and maybe you can help out testing.

**Comment by soulgalore** [comment]
I've pushed this so far: https://github.com/sitespeedio/browsertime-extension and it works, we'll integrate it the coming days. However to make it work in Firefox we need a fix in Selenium that doesn't support the latest extension setup for Firefox. @tufandevrim will Chrome support be enough for now and then can we add Firefox when Selenium is fixed? Else if someone could help us with the [Selenium issue](https://github.com/SeleniumHQ/selenium/issues/3291) that would be marvelous :)

**Comment by tufandevrim** [comment]
> @tufandevrim will Chrome support be enough for now and then can we add Firefox when Selenium is fixed?

Absolutely yes!

**Comment by soulgalore** [comment]
@worenga released a beta of 1.1 for Browsertime today: 1.1.0-beta1
If you have time, can you test that request blocking works as you want? You blacklist domains with *--block my.domain.com* (using what's available as a browser extension. Think that *.domain.com will block all subdomains on that domain. You need one --block parameter per domain. And it only works in Chrome until Tobias patch has landed and is released in Selenium

@tufandevrim if you have time you can try out request headers. You can use the same tag for Browsertime or use the latest tag in Docker for sitespeed.io. *-r* or the full *--requestheader* and the name:value

We will let it run a couple of days on our test server and add/change whatever needed before we release it hopefully late this week.

**Comment by soulgalore** [comment]
Released this today in 1.1 and going out in sitespeed.io 5.0 tomorrow.
