### ISSUE TITLE
How to attach to docker container of browser time 

### ISSUE THREAD

**Issue by connorzhao-infotrack** [sitespeedio/browsertime#309]
I run browsertime in docker and 
I cannot attach to the container what so ever
tried -td -i command, all not working,
can anybody help plz, what command should i use to run it
so I can attach to this image and modify it

**Comment by tobli** [comment]
Hi!
Could you please explain more about your current situation and what you want to accomplish? There might be easier ways than modifying the prebuilt Docker container.

**Comment by connorzhao-infotrack** [comment]
By the way, is there a configuration to disable chrome's cache? as I want test the speed in the aspect of a new visitor

**Comment by tobli** [comment]
A fresh Chrome instance, with no disk or memory cache, is started for each url and iteration. Are you experiencing any issues?

Regards,
/Tobias

**Comment by soulgalore** [comment]
Please re-open @connorzhao-infotrack if you need more info.
