### ISSUE TITLE
Browsertime video shows inconsistent results while running from docker

### ISSUE THREAD

**Issue by ftore** [sitespeedio/browsertime#314]
I am not sure whether it is normal behavior or not, but when we run sitespeed.io to test our login page, we are having inconsistent/incorrect results. We are measuring fisrtVisualChange:
1st run: 
![screen shot 2017-04-18 at 3 57 09 pm](https://cloud.githubusercontent.com/assets/3230490/25150667/b4131f20-2450-11e7-8156-333b70f72651.png)
2nd run:
![screen shot 2017-04-18 at 3 58 26 pm](https://cloud.githubusercontent.com/assets/3230490/25150720/dd31d23e-2450-11e7-908b-9a19971021d3.png)
3rd run:
![screen shot 2017-04-18 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/3230490/25150727/e4287f52-2450-11e7-95d6-0f7e221805af.png)

As you can see in the first screenshot, firstVisualChange is happening too soon.

Any ideas why it is happening? I would really like to work on fixing this issue. Could you please, give me any suggestions.. Thanks

**Comment by soulgalore** [comment]
Hi @ftore 
thanks for submitting the issue. 

Ok, so if I understand correctly the first page is actually the login page? If I remember correctly the original promises in Selenium isn't perfect and our example for Wikipedia works because Wikipedia is fast, but for slower sites the login script could return early even though the page hasn't finished loading (but I'm only guessing since I don't know what your login script looks like). 

I think there's a config we could try out in Browsertime to turn on native promises for Selenium, but @tobli knows more about that.

Best
Peter

**Comment by soulgalore** [comment]
@ftore if you don't have it already, can you add an extra step in your script so that you wait on sometihng on the page where you have logged in before returning? Checked the example script and we miss that there.

**Comment by ftore** [comment]
Thanks Peter for your response. The problem is, I have not even run any preScripts yet. I am just loading this page from URL.  Most of the time, the measurements are correct. Once in a while it shows totally incorrect firstVisualView measurement. I would say 5:1, where 5 times is shows correct firstVisualView and 1 incorrect.

**Comment by soulgalore** [comment]
Sorry I'm slow and not following, can you explain more in detail how it is incorrect? The first visual change is picked up before anything happen on the screen? Can you show me exact how you run?

**Comment by ftore** [comment]
Hey Peter!

So, I running following command:

docker-compose -f /home/ubuntu/docker-compose.yml run --rm $DOCKER_CONTAINER /sitespeed.io/sitespeed-result/url.txt $CONFIG --graphite.host=graphite >> /tmp/sitespeed.log 2>&1

In url.txt, in the url of https://masterpass.com/switchui/welcome page, but in the dev environment. I configured sitespeed.io from docker-compose and running following this article:
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/

1. curl -O https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml
2. docker-compose up -d
3. docker-compose -f /home/ubuntu/docker-compose.yml run --rm $DOCKER_CONTAINER /sitespeed.io/sitespeed-result/url.txt $CONFIG --graphite.host=graphite >> /tmp/sitespeed.log 2>&1
4. Access the dashboard: http://127.0.0.1:3000

After I run those commands, I access html results from sitespeed-result folder.

**Comment by soulgalore** [comment]
Hi @ftore ,
ok so I've re-read your issue, I think I understand now :)

For the first run you have something in the top left, isn't that what fires firstVisualChange? But it's hard to judge without the video:

![hepp](https://cloud.githubusercontent.com/assets/540757/25249583/a32e240c-2612-11e7-98e0-bea0359e03f6.png)

Best
Peter

**Comment by soulgalore** [comment]
Could it be that we have different definitions of firstVisualChange? For us, that is when something first appears on the screen.

Best
Peter

**Comment by ftore** [comment]
Thank you Peter for your reply. I thought that firstVisualChange is equal to first meaningful visual change. Yeah, it might be our app problem, that we should fix. I was not sure about that.

**Comment by soulgalore** [comment]
Ah I see. No we just analyze the video. There are "meaningful" change coming in Chrome and it's still experimental so we will wait to add that until we see that it works. Usually metrics from the video is more closer to what the user experience than the metrics the browser report.
