### ISSUE TITLE
Firefox 53 fails 

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#316]
There's a current miss-match between releases of Firefox 53, Geckodriver and Selenium (NodeJS version). If you run the current Browsertime with FF 53 you get:
<pre>
[2017-04-19 21:14:03] Error running browsertime BrowserError: Unrecognised timeout: page load
</pre>

When Selenium 3.4.0 and Geckodriver 0.16.0 is released, we can upgrade and fix that. Keep using our Docker containers :)

**Comment by tobli** [comment]
Fail no more! Works as of 06b9d35.
