### ISSUE TITLE
No third party domain resource requests

### ISSUE THREAD

**Issue by lbod** [sitespeedio/browsertime#319]
This is a strange issue and I'm really struggling to get my head around it as well any test results to prove.

We have a site which for months hasn't recorded any 3rd party domain requests. Nothing in the docker sitespeed html reports or grafana/graphite. It's exactly the same sitepeed run config as other sites (we disabled firstParty to check). **It's also the same running in browsertime** e.g.

`
bin/browsertime.js mysite.com -b firefox
`

I don't want to post the URL but I'm certain there's an issue with the implementation/app code that site has written, we don't manage the site so I haven't seen the source.
Looking through the mini'd code I see it's using browserify then including 3rd party request scripts using innerHTML such as analytics, social etc. I always thought that was a bit dodgy re concurrency or even being allowed.

I've also seen strange behaviour on that site in my local FF browser too where it doesn't log the 3rd party requests in the network panel, intermittently it did over the last week though! adblock blocks the requests in chrome, after disabling it the 3rd part requests are successful. 

Sorry I can't provide more, I've been trying to create a local test to replicate but couldn't and wasn't able to discover anything debugging browsertime either, has anyone else seen something similar?

It feels like some sort of race condition or maybe browser/webdriver permissions? I'd like to debug and fix it myself but at the moment, it's not clear at all.

**Comment by soulgalore** [comment]
Hi @lbod ,
we use https://github.com/firebug/har-export-trigger to get the HAR from Firefox. I would debug it like this:
1. Test with Firefox Nighty, do you see the request there in the network traffic? If not, file a bug https://bugzilla.mozilla.org/ and use a proxy to sniff the traffic so you can show what is missing
2. Dive into https://github.com/firebug/har-export-trigger and check if there's something you can do there.

Best
Peter

**Comment by lbod** [comment]
Hi @soulgalore . I tried har-export-trigger but even after finding 0.5.0-beta.10 I couldn't figure out how to get it to work (maybe it doesn't work in nightly so I'll go back to latest), their docs are a bit unclear but can you just run the JS from the console after the page has loaded `HAR.triggerExport(...` as I got undefined too. 
What's the difference between that and just using the "Save all as har" from the network tab?

In nightly the requests don't show either, exporting from "Save all as har" is the same. 
I'm sure it's the site

Thanks again

**Comment by soulgalore** [comment]
@lbod to test HAR Export trigger standalone you can configure to write the HAR to disk by default: https://github.com/firebug/har-export-trigger/wiki/Examples#save-to-file
If I remember correctly you could configure Firefox to automatically store the HAR but I think that was on the original blog post but a couple days ago the site went down: http://www.softwareishard.com/blog/har-export-trigger/

**Comment by soulgalore** [comment]
There's a new HAR exporter now https://github.com/devtools-html/har-export-trigger if you get the same with that one, please open an upstream issue! 

Best
Peter
