### ISSUE TITLE
statistics values

### ISSUE THREAD

**Issue by patitonav** [sitespeedio/browsertime#326]
I am running browsertime in several webpages and the JSON comes with different values in the section statistics. For example: "firstscript", "load", "main_feature" and so on. But some times i am getting different values, witch i think are related to the site i am testing, like : "add.this.render_layers_thankyou".
My question is , witch ones are the standard values, and witch are related to the site, or how is browsertime generating this statistics keys.

Thank you very much

**Comment by soulgalore** [comment]
Hi @patitonav 
the ones that browsertime colllects through JavaScript you can see here: https://github.com/sitespeedio/browsertime/tree/master/browserscripts (go down to each folder), then if you run video and SpeedIndex you will also get firstVisualRender, visualComplete85% and lastVisuaRender.

The ones that you see that are different on different sites are probably [User Timings](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) that the developers of the site had added. Browsertime picks them up through the User Timing API.

Best
Peter

**Comment by patitonav** [comment]
Can we deactivate User Timmings additional statics? We want to get allways the basic statisc and no the one based on a particular site.

Thank you

**Comment by soulgalore** [comment]
You can do that with non matching regex:

<pre> bin/browsertime.js --help
...
 --userTimingWhitelist  All userTimings are captured by default this option takes a regex that will whitelist which userTimings to capture in the results.
...
</pre>

**Comment by patitonav** [comment]
Thank you very much this solve my problem.
