### ISSUE TITLE
Collect Chrome trace categories is broken in Chromedriver 2.29 and 2.30

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#337]
With the current version you don't get the full trace log as configured. You can easily see that by checking the trace file that is only a couple of kbs for each site, it should be mbs.

**Comment by soulgalore** [comment]
Did a quick check and downgrading to Chromedriver 2.28 works (2.29 fails). Has something changed that we don't know about or is it a bug?

**Comment by soulgalore** [comment]
Seems to be: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1811&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&start=100

**Comment by soulgalore** [comment]
Works now when I tested with 2.30.0.

**Comment by tobli** [comment]
👏🏻👏🏻👏🏻

**Comment by soulgalore** [comment]
It's still a thing, I could see that on Digital Ocean when we released the latest version.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1811

**Comment by soulgalore** [comment]
I think we shall try to do a fix ourselves. If I remember correctly we first get the log (to get rid of everything that happens before the first navigation) and then gets it after navigation is done. With latest drivers it seems like you cannot fetch the log twice?

**Comment by soulgalore** [comment]
Did a super simple test just disabling https://github.com/sitespeedio/browsertime/blob/master/lib/core/engineDelegate/chromeDelegate.js#L41-L42 and running with 2.30. The HAR file looks fine and the trace log is there, the only thing is that it starts later:
<img width="1280" alt="screen shot 2017-06-22 at 6 25 26 pm" src="https://user-images.githubusercontent.com/540757/27444960-662881b4-5778-11e7-9576-0e05ba447b80.png">

@tobli do you remember if the emptying of the log was needed or more to make the log smaller?

**Comment by soulgalore** [comment]
Fixed with https://github.com/sitespeedio/browsertime/pull/347
