### ISSUE TITLE
browsertime.pageCompleteCheck not working on few pages

### ISSUE THREAD

**Issue by IrannaGit** [sitespeedio/browsertime#349]
I have been using sitespeed.io for some time now and wanted an option which makes sure that page is actually completely loaded before it send metrics to graphite.   with my docker run command i have added this parameter something like below :

docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io login.js http://xxxx.xxx.xxxxx.com/#p=eyJsdfsdfsdfsdfsdfsdf::  --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 10000;} catch(e) {} return true;})()'

The above code works for few pages and does not work for some other pages. I checked few screenshots [in sitespeed result directory] and could see that pages were still loading, so I am worried whether sitespeed is sending metrics when the page was still loading. I have not been able to understand the reason behind it.    Am i doing anything wrong with the code which i have put above ?

**Comment by tobli** [comment]
Hi!
window.performance.timing.loadEventEnd will return 0 until the load event has actually occurred (check [MDN](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/loadEventEnd) for details). Therefor your check will return true every time. The default check is
```
return (function() {try { var end = window.performance.timing.loadEventEnd; return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})()
```
and includes a check for this. Also note that, depending on your page, the load event might not be enough to match your definition of "loaded", e.g. if you have actions in async loaded scripts.

I'm closing this issue now but please reopen if it doesn't work for you.

Thanks,
/Tobias
