### ISSUE TITLE
Using SOCKS5 proxy server with browsertime?

### ISSUE THREAD

**Issue by jimmy-ly00** [sitespeedio/browsertime#350]
I'm trying to test a modified SOCKS5 proxy server. It is currently hosted on localhost. Is there any method to do this with browsertime, not just "normal" proxy? 

I have tried:  `browsertime http://website.com -b firefox --proxy.http socks5://localhost:1080`

**Comment by soulgalore** [comment]
Hi @jimmy-ly00 the socks5 support in Selenium doesn't seem to work but you can use SOCKS5 with Chrome/Firefox arguments.

For Chrome you can add Chrome command line argments with **--chrome.args** so it would be somthing like **--chrome.args "proxy-server=socks5://localhost:PORT"**

For Firefox you do that with the Firefox preferences **--firefox.preference** and then you need to pass a couple arguments, it would be something like:
**--firefox.preference "network.proxy.socks:localhost" --firefox.preference "network.proxy.socks_port:PORT" --firefox.preference "network.proxy.type:1"**

It could be that you need to finetune some of them :) Please report back what worked for you.

Best
Peter

**Comment by jimmy-ly00** [comment]
Thanks for the quick reply @soulgalore . It seems that none of those arguments get passed with browsertime, but firefox is working itself though. I even put a random link, so that I could check the settings manually while it was running, and it didn't change. Are my arguments correct?

**Doesn't work**
`browsertime http://example.com -b firefox --firefox.preference "network.proxy.socks:localhost" --firefox.preference "network.proxy.socks_port:1080" --firefox.preference "network.proxy.type:1" --firefox.preference "network.proxy.socks_version:5"`

**Works**
`firefox --firefox.preference "network.proxy.socks:localhost" --firefox.preference "network.proxy.socks_port:1080" --firefox.preference "network.proxy.type:1" --firefox.preference "network.proxy.socks_version:5"`

**Comment by soulgalore** [comment]
The values get set through Selenium but it seems like something still is wrong (I tested and checked that it is set). I'll marked it as a bug and let us look into it when we have some free time.

**Comment by ncalexan** [comment]
I just tested this locally, with a version of browsertime forked from 4.9.2, and this appears to work just fine.

**Comment by soulgalore** [comment]
Aha cool, thanks @ncalexan !

**Comment by soulgalore** [comment]
Closing since it probably works now :)
