### ISSUE TITLE
proxy option for connectivity

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/browsertime#351]
Hi @soulgalore  i noticed that `setProxy` option was recently removed from webdriver/index.js.  I need this option :( . Is there any other way we can set the connectivity proxy now?

**Comment by soulgalore** [comment]
Hi @abhagupta you can set the proxy using:
```
proxy
  --proxy.http   Http proxy (host:port)                                 [string]
  --proxy.https  Https proxy (host:port)                                [string]
```

or am I missing something?

Best
Peter

**Comment by abhagupta** [comment]
Yep, thats what it is. I had accidently put it inside `browsertime.capabilities.proxy`
