### ISSUE TITLE
Question about --browsertime.pageCompleteCheck

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/browsertime#373]
Hi @tobli and @soulgalore 

I am trying to understand how/when `--browsertime.pageCompleteCheck` script works since I was under the impression that it would stop immediately recording on `loadEventEnd > 0` if I set it to `return true;`

However it seems still waiting around + 2 sec to stop recording after loadEventEnd is set. Am I right or am I doing something wrong?

What I am trying to accomplish is I want to take the snapshot of everything on loadEventEnd or loadEventStart. Even if possible I'd like to stop recording when `window.performance.timing.domContentLoadedEventStart > 0`

More insight would be appreciated.

Thanks,
Devrim

**Comment by soulgalore** [comment]
Hi @tufandevrim 
in the current version of the webdriver (both for Chrome & Firefox) you can only stop after onLoad has happend (not before) but in the future you can change that with pageLoadStrategies see https://github.com/sitespeedio/browsertime/issues/186 (I haven't looked in a while if it is closer to implementation). When then happens, you will be able to choose almost exactly when to end your test.

If you change **--browsertime.pageCompleteCheck** that should work (remove the two seconds that we have by default). You could probably just return true because that method will be called only after the loadEventEnd has happend. If not I think there's a bug, I need to look at it. If you can give me a full command line example that would be great.

Best
Peter

**Comment by tufandevrim** [comment]
Here is what I tried

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:5.6.2 https://www.yahoo.com --outputFolder test/dummy1 -n 3 --plugins.load analysisstorer --browsertime.viewPort 1280x800 --browsertime.pageCompleteCheck "return true;"`

vs

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:5.6.2 https://www.yahoo.com --outputFolder test/dummy2 -n 3 --plugins.load analysisstorer --browsertime.viewPort 1280x800`


The first command line with `--browsertime.pageCompleteCheck "return true;"` definitely cuts off the test earlier than the second one.

**Comment by soulgalore** [comment]
Without any pageCompleteCheck it uses our default one (=loadEventEnd + 2 seconds). Just return true will be as close as it can get to loadEventEnd I guess.  The extra time is added then in the driver. So I'm a little curious how do you plan to use it? :)

**Comment by tufandevrim** [comment]
My purpose here is to know total the payload size, JS size, CSS size in KB **exactly** on `loadEventEnd` and `domContentLoadedEventEnd`

Actually, since you already have every single request information (from the waterfall - HAR), you should be able to provide what we're looking for in the reports:

- total payload size and request count on **domContentLoadedEventEnd**
- total js size and js request count on **domContentLoadedEventEnd**
- total css size and css request count on **domContentLoadedEventEnd**

- total payload size and request count on ** loadEventEnd**
- total js size and js request count on ** loadEventEnd**
- total css size and css request count on ** loadEventEnd**

Let me know if it makes sense to you guys. I could definitely implement this and contribute back to the project.

**Comment by soulgalore** [comment]
Hi @tufandevrim ah I see, it is something like this https://github.com/sitespeedio/pagexray/issues/17 and a variant like https://github.com/sitespeedio/sitespeed.io/issues/1656.

Yes as you explain that makes sense, also want to add the number of requests. That would live in PageXray (that takes the HAR file and makes the most sense of it). If you have time to contribute it, it would be great! Let me know if you need help to get started. Then I can add the impl into sitespeed.io and compare.sitespeed.io.

So the plan is to release 6.0 in November (sometimes after FF 57 is released) but we will release a couple of betas before that you can use.

Best
Peter

**Comment by soulgalore** [comment]
In 3.0 (master) you can now choose whatever pageCompleteCheck you want because we now switched pageLoadStrategy to none.
