### ISSUE TITLE
Question about --browsertime.requestheader and cookie

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/browsertime#374]
Hi @tobli and @soulgalore

I have another question.
It seems I can set cookies with `--browsertime.requestheader` config.

For example when I use `--browsertime.requestheader "cookie: 'foo=bar'"` in the command line below:

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:5.6.2 https://www.yahoo.com --outputFolder test/dummy2 -n 3 --plugins.load analysisstorer --browsertime.requestheader "cookie: 'foo=bar'"`

I see it is set as cookie in the waterfall diagram (first first request). I also verified on the server side we get the cookies. However when I tried reach the cookies on the client side (javascript) `document.cookie` is empty. This is an issue for some yahoo web sites which check cookies on the client site sometimes by checking `document.cookie`

What is your recommendation or is there any way that if  `--browsertime.requestheader` contains `cookie` key, we set the value to `document.cookie` in current running window?

Thanks,
Devrim

**Comment by soulgalore** [comment]
Hi @tufandevrim sorry that it took a while for me to get back. I think we maybe need to change our implementation so you can set cookies with the WebExtensions plugin we use directly (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set). Then it will be --cookie parameter and I think it will work, but let me try it out asap.

Best
Peter

**Comment by soulgalore** [comment]
There's a [PR](https://github.com/sitespeedio/browsertime-extension/pull/4) for this that must be tested (and updated).

**Comment by tobli** [comment]
@soulgalore now that https://github.com/sitespeedio/browsertime-extension/pull/4 is merged, can this be closed?

**Comment by soulgalore** [comment]
This is fixed now so we can close this.
