### ISSUE TITLE
Possible error in Browsertime home page examples

### ISSUE THREAD

**Issue by JoaoGFarias** [sitespeedio/browsertime#377]
[Browsertime homepage](http://browsertime.net/) examples shows the option `-u`, which seems to be deprecated. Is it?

![screen shot 2017-10-05 at 10 53 58 am](https://user-images.githubusercontent.com/1585655/31230922-d2d958ac-a9bb-11e7-9f18-26c52c69b906.png)
![screen shot 2017-10-05 at 10 54 09 am](https://user-images.githubusercontent.com/1585655/31230923-d30e3cb6-a9bb-11e7-8555-31d1ac6a9181.png)

**Comment by soulgalore** [comment]
Thanks for reporting @JoaoGFarias ! You are right, it's always best to do `browsertime --help`.

@tobli do you have access so we can redirect that domain to https://www.sitespeed.io/documentation/browsertime/?

**Comment by soulgalore** [comment]
Tobias has fixed it now so we redirects to https://www.sitespeed.io/documentation/browsertime/
