### ISSUE TITLE
Errors while checking browsertime

### ISSUE THREAD

**Issue by mrajiullah** [sitespeedio/browsertime#383]
$ bin/browsertime.js -help
/Users/../browsertime/lib/core/engine.js:215
      options.postScript.unshift(...videoPostScripts);
                                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/MRajS/Documents/my_project_work/MONROE/browsertime/index.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by mrajiullah** [comment]
The problem disappears with upgrading the node version but required me installing the following modules

 1267  npm install --save bluebird
 1269  npm install --save intel
 1271  npm install --save lodash.merge
 1273  npm install --save lodash.get
 1275  npm install --save lodash.set
 1277  npm install --save fast-stats
 1296  npm install --save lodash.isempty
 1298  npm install --save moment
 1300  npm install --save mkdirp
 1311  npm install --save selenium-webdriver
 1315  npm install --save lodash.pick
 1317  npm install --save chrome-har
 1319  npm install --save lodash.remove
 1321  npm install --save alto-saxophone
 1323* npm install --save lodash.foreach
 1326  npm install --save soprano-saxophone
 1328  npm install --save execa
 1330  npm install --save adbkit
 1332  npm install --save @sitespeed.io/throttle
 1334  npm install --save xvfb
 1336  npm install --save lodash
 1338  npm install --save lodash.foreach
 1340  npm install --save yargs
 1342  npm install --save valid-url
 1344  npm install --save hasbin

**Comment by soulgalore** [comment]
Hi @mrajiullah we run NodeJS 8 in master now preparing for 2.0. If you wanna do changes for current stable you can use https://github.com/sitespeedio/browsertime/tree/1.x  or install with npm or just use Docker!

Best
Peter
