### ISSUE TITLE
--ResultsDir flag not being honored

### ISSUE THREAD

**Issue by sabler** [sitespeedio/browsertime#387]
I've tried about every iteration I can think of, but `--resultsDir` followed by an arbitrary path on my system is disregarded and all output is sent to the default, browsertime-results/[domain]/

Is this currently being addressed? It's a bit of a roadblock to some automation I'm trying to build out.

I'm running v1.9.5

Thanks!

**Comment by soulgalore** [comment]
Hi @sabler I'm pretty sure it works. In you example you have an extra s, it should be `--resultDir`:

Best way to check the options is alwas:` browsertime --help`

Best
Peter

**Comment by sabler** [comment]
That was a typo in the issue box, the code is correct. :) I've since resolved the issue, the path string being built was formatted incorrectly in one of our dependencies and patched locally. Taking the issue to their door instead. :) Thanks for checking in!
