### ISSUE TITLE
window.setSize does not work on Android.

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/browsertime#401]
Hi @peter  I am running sitespeed tests  on android real device via connecting to Appium. But there is a piece of code in which the test fails because of window.setSize here : https://github.com/sitespeedio/browsertime/blob/master/lib/core/seleniumRunner.js#L83. Reason:  Android does not support `window.setSize`.  Can I propose to add an option of boolean `mobile` in the options sent to sitespeed.io which determines whether this code will be executed or not.  I can send a PR.

**Comment by soulgalore** [comment]
Hi @abhagupta yes please send a PR. We have a fix for it in sitespeed.io  see https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/browsertime/index.js#L78-L85 but we should solve it better in Browsertime. So master is hot now (coming 2.0). If you need the fix now, we need to merge in 1.x.

Best
Peter

**Comment by soulgalore** [comment]
There's a hack now since 3.x. Add `--android` as a cli param and it will work.
