### ISSUE TITLE
Chrome 64 to deprecate the chrome.loadTimes() API

### ISSUE THREAD

**Issue by worenga** [sitespeedio/browsertime#417]
Chrome Versions >=64 will deprecate chrome.loadTimes() which is currently used to calculate firstPaint within bt [1,2].

While current versions only show a deprecation warning we might think about how to incorporate this and maybe also think about first-contentful-paint from the PaintTiming API can be included.

[1] https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=621512

**Comment by soulgalore** [comment]
Yep lets change the current impl and release that asap. We have paint timing today already in https://github.com/sitespeedio/browsertime/blob/master/browserscripts/timings/paintTiming.js so I think we just keep that + change the first paint implementation.

One thing though about first contentfull paint: We implemented so we report it but I still think it is like the "Emperor's New Clothes": Chrome and Google people promote it really hard, but I and [other people](https://github.com/WPO-Foundation/webpagetest/issues/942) has shown it doesn't work. It is pretty annoying for me that they keep banging the drum for it, though it seems to not work as expected.

**Comment by soulgalore** [comment]
This is released!
