### ISSUE TITLE
Implement WebExtension HAR Export Trigger for Firefox Quantum

### ISSUE THREAD

**Issue by joshuabuildsthings** [sitespeedio/browsertime#424]
It looks like the Firefox DevTools team is working on an update to the HAR Export Trigger functionality that would enable HAR Export in the latest Firefox as well as Chrome.

https://github.com/devtools-html/har-export-trigger

Thought you and the team might like to know based on this issue the SiteSpeedIO Team filed with Firebug:
https://github.com/firebug/har-export-trigger/issues/45

**Comment by soulgalore** [comment]
Hi @joshuabuildsthings yes thanks we are on it, we need to wait on a couple of merges in FF for it to work first, best case it will be there in FF 59 if I understand correctly.

Best
Peter

**Comment by soulgalore** [comment]
This has been implemented in master, now wait for it to work with minimal effect on performance, hope that will happen in FF 61.
