### ISSUE TITLE
Support remote browsers

### ISSUE THREAD

**Issue by tobli** [sitespeedio/browsertime#43]
Support fetching metrics from a remote grid of browsers.

**Comment by exdis** [comment]
+1

**Comment by tobli** [comment]
@exdis - have you tried spinning up a [Selenium Standalone Server](http://docs.seleniumhq.org/download/) on a remote machine and specifying the server url via --seleniumServer? We use it for running a local Selenium java server in the [Sitespeed docker containers](https://hub.docker.com/r/sitespeedio/sitespeed.io/), but I've not really tried it for remote servers. However it "should just work".

**Comment by tobli** [comment]
One thing to note though: since har creation, connection throttling etc. depends on a local proxy, those features won't be available when running a remote browser. You'd have to pass the --noProxy option when running with a remote selenium server.

**Comment by azimut** [comment]
Right, I got errors on the har creation. Other that that chrome seems to work fine. Wondering if there is something it could be do to support hars too.

**Comment by soulgalore** [comment]
I think this should work if someone actually want to do it. Please re-open if there's something that don't work.
