### ISSUE TITLE
Unhandled "error" event in browsertime

### ISSUE THREAD

**Issue by mrajiullah** [sitespeedio/browsertime#433]
Hi!

I get the following issue while using browsertime.
I have docker container with the latest browsertime, firefox 56 and chrome 64.
I saw the similar behaviour with firefox 54 and chrome 63.

2018-01-25T11:08:50.105289950Z events.js:182
2018-01-25T11:08:50.105470730Z       throw er; // Unhandled 'error' event
2018-01-25T11:08:50.105540075Z       ^
2018-01-25T11:08:50.105574056Z 
2018-01-25T11:08:50.105608847Z Error: write EPIPE
2018-01-25T11:08:50.105643195Z     at _errnoException (util.js:1021:11)
2018-01-25T11:08:50.105687289Z     at WriteWrap.afterWrite [as oncomplete] (net.js:860:14)

M. Rajiullah

**Comment by soulgalore** [comment]
Hi @mrajiullah so where do you get them? What host OS are you running, wanna try to reproduce.

Best
Peter

**Comment by mrajiullah** [comment]
Hi!

Its Linux where the container runs. I can send you the docker files if you think that is helpful.

Best 
Mohammad

**Comment by soulgalore** [comment]
Yeah but what flavor of Linux? We have seen different behavior depending on host OS. Not only the OS in the container matter, also the host.

> I can send you the docker files if you think that is helpful.

We only support our Docker containers :) Show us how we can reproduce it and we can have a look :)

Best
Peter

**Comment by mrajiullah** [comment]
Hi, its debian (stretch) linux. The container can be reached at mraj/monroe-browsertime
#docker pull mraj/monroe-browsertime
#docker run -it --entrypoint=bash mraj/monroe-browsertime 
you will be in /opt/monroe directory 
than you have to run python browsertime.py 
But before than do few changes to browsertime.py
change DEBUG=False to True
add "eth0" or the interface you have in allowed interfaces
and change the ip for the interface at line 406 

Mohammad

**Comment by soulgalore** [comment]
In 3.0 we moved most promises to async/await that makes it easier to catch errors and log where it actually happens. Let us know if this still happens.

**Comment by soulgalore** [comment]
We release 4.0 some time ago, I'll close it and please create a new issue if you get more errors.
