### ISSUE TITLE
User timings aren't picked up correctly for yandex.ru

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#439]
I think the naming somehow breaks how we pickup the metrics.

<img width="1305" alt="screen shot 2018-02-05 at 00 26 26" src="https://user-images.githubusercontent.com/540757/35783672-54dac70a-0a0b-11e8-8fc6-6cf6dfc6fc49.png">

And the browsertime.json looks like this:
`"userTimings":{"marks":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, ...`

We can reproduce by: `bin/browsertime.js http://yandex.ru`

**Comment by tobli** [comment]
I have an upcoming fix for this. Marks (and measurements) with "." in the name was not handled by the code that used dotted paths to get/set values in the the stats structure.
