### ISSUE TITLE
Storage location for collectNetLog

### ISSUE THREAD

**Issue by sri85** [sitespeedio/browsertime#459]
```
{
  "browsertime": {
    "iterations": 1,
    "browser": "chrome",
    "chrome": {
      "collectNetLog":true
    },
    "preURLDelay": 3000,
    "videoParams": {
      "combine": true
    }
  },
  "utc": true
}
```
Above is the configuration that i have for browsertime , all the tests run fine but i am unable to find the data generated by `collectNetLog`. Where is this stored? 

I am using the below versions

```
Google Chrome 63.0.3239.132
Mozilla Firefox 54.0.1
[2018-02-20 18:45:53] INFO: Versions OS: linux 4.9.49-moby nodejs: v8.9.4 sitespeed.io: 6.3.5 browsertime: 2.1.4 coach: 1.2.0
```

**Comment by soulgalore** [comment]
Hi @sri85 if you run it from sitespeed.io it should be in the data folder, for me it looks like this:
` sitespeed.io https://www.sitespeed.io -n 1 --browsertime.chrome.collectNetLog`

<img width="617" alt="screen shot 2018-02-20 at 8 16 50 pm" src="https://user-images.githubusercontent.com/540757/36444212-24d205a6-167b-11e8-831a-2a20b08b0627.png">

Best
Peter

**Comment by sri85** [comment]
Thanks @soulgalore, that worked. 
I tried with console logs and perf metricsbut no file was found under data folder.

**Comment by soulgalore** [comment]
> chrome.collectPerfLog 

That is probably a be bug in sitespeed. Can you use  **--browsertimechrome.collectTracingEvents**?

> chrome.collectConsoleLog 

Sitespeed hasn't been upgraded to use that Browsertime version yet. Wanna do so we parse the log and add it to the HTML result before we release that.

> As you can see CSS field is marked as N/A does it mean NO CSS was downloaded?

No CSS request was done. You could still inline CSS In the HTML, we don't measure that today, but that would be cool to include in the coach.

**Comment by sri85** [comment]
@soulgalore  This works `-browsertime.chrome.collectTracingEvents?`

**Comment by soulgalore** [comment]
In sitespeed.io 7.0 we added the same cli params for sitespeed.io as for browsertime, hope that will fix things. If doesn't work, please open an issue in sitespeed.io

Best
Peter
