### ISSUE TITLE
HAR issue: log.pages[0].startedDateTime attribute is an empty string.

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/browsertime#522]
Hi!
I guess there is some problem with HAR generating (exporting) process.
Some of my HAR files that I got from sitespeed run contain an empty string for the `log.pages[0].startedDateTime` field. This cause the NaN values in waterfall chart.

Could you check it please?
I've left more info in PerfCascade repo https://github.com/micmro/PerfCascade/issues/224 including examples of HARs and screenshots.

**Comment by soulgalore** [comment]
This has been fixed now in Chrome-har.
