### ISSUE TITLE
ability to check extensions 

### ISSUE THREAD

**Issue by ko4evnik** [sitespeedio/browsertime#541]
It would be great for me if browsertime will have ability to test internal pages and extensions.

Now I see 3 things which blocked:
1) Check url with isWebUrl method, chrome://blabla isn't legal web url, but method isUrl validate it as correct
2) Use javascript for navigate to test url. JS redirect to local url is blocked by security policy in FF and Chrome. Why you use JS script for this but not browser.get(url)? 
3) url.pathname return null for chrome://blabla. 

I have pull request for this pieces, if you ok with this changes.

**Comment by soulgalore** [comment]
Hi @ko4evnik 
can you share some more why/how you plan to test your internal pages and extensions (haven't seen the use case before)?

 > Why you use JS script for this but not browser.get(url)?

We use plain JS (in master) because of getting rid of lag between setting the background color to white and start to navigate to the URL. Using executeJS and then get introduces lag in some cases.

Best
Peter

**Comment by ko4evnik** [comment]
We have extensions for Firefox and Chrome and want monitoring performance issues automatically.
This is examples of our products:
[Pulse](https://chrome.google.com/webstore/detail/%D0%BF%D1%83%D0%BB%D1%8C%D1%81/eamdgloldgfdgleehaahlpbcdgdgdkif)
[Visual bookmarks](https://chrome.google.com/webstore/detail/%D0%B2%D0%B8%D0%B7%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B7%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8-mailr/enafhpjmlnpmbdnbpjkihmadnkfnpiim)
[Pulse for FF](https://addons.mozilla.org/ru/firefox/addon/%D0%BF%D1%83%D0%BB%D1%8C%D1%82/)

**Comment by soulgalore** [comment]
Hi @ko4evnik sorry for not getting back on this, I forgot about when releasing latest major of BT and sitespeed.io. I'm a little concerned that this will complicate things in the future, ping @tobli .

**Comment by soulgalore** [comment]
I think we will keep on focusing on URLs, sorry.
