### ISSUE TITLE
Feature Request: CLI Option to Load User Specified Extensions

### ISSUE THREAD

**Issue by joshuabuildsthings** [sitespeedio/browsertime#551]
I would love to see a run-time CLI Option to enable dynamic loading of Chrome & Firefox extensions for emulating Real User experiences more accurately. 

An example use case might be to run a test with Ad Blocking enabled.

Thoughts?

**Comment by joshuabuildsthings** [comment]
@soulgalore - Excited to see how fast that got added; I didn't even have time to offer to pitch in. Thanks for the rapid response. Hopefully this is of use to lots of other users of SiteSpeed.io's toolkit.

**Comment by soulgalore** [comment]
@joshuabuildsthings yes but it will be a while until it is released in stable though, just so you know (launching in 3.0).
