### ISSUE TITLE
Concurrent sessions

### ISSUE THREAD

**Issue by pc-alves** [sitespeedio/browsertime#560]
Hi!

I am looking for a way to run concurrent sessions, and I can't seem to find anything in the docs.
So far the documentation looks really nice (good work there) so I'm guessing that this feature is missing.
Am I missing something, or would this be a new feature?

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @pc-alves ,
can you explain a little more what you concurrent sessions? It it running multiple browser instances at the same time?

Best
Peter

**Comment by pc-alves** [comment]
@soulgalore 
Yes. That would be it. The idea would be to simulate concurrent users, instead of a series of consecutive requests.
Of course, I can just trigger multiple processes running browsertime, but in that case I don't get the statistics consolidated across the concurrent runs (with the percentiles and averages...).

**Comment by soulgalore** [comment]
Ah ok, I would use another tool for load testing scenarios (JMeter or something). Browsertime is good at measuring front end performance (=how you build your page). 

Best
Peter

**Comment by pc-alves** [comment]
My goal was actually to measure the front end performance, by putting some load on the system as a whole.

Here is a use case:
- Let's say that a page has multiple components with content loaded from different backend services.
- I can test those different resources separately, but that way I won't know how that would impact the end-user experience.
- Putting the load through the browser would allow to measure the actual impact of that load to the end-user
  - Did the TTFB increased as expected?
  - Did it really affect the page load time?
  - Or the time to interactive?
  - Was the increase in TTFB residual in the overall experience?

Regarding my original post, I now know that this is not supported today in browsertime.
Question that remains is if you would consider adding this feature, or not include it in the scope of browsertime.

**Comment by soulgalore** [comment]
> Question that remains is if you would consider adding this feature, or not include it in the scope of browsertime. 

No I don't think it would be implemented. What you can do is generate load on your different components and then run Browsertime with X runs on a url and take the median and compare with different amount of load put on different systems.

Best
Peter

**Comment by pc-alves** [comment]
@soulgalore 
That would be an option, but a more elaborate one as I would have to manage a separate tool for the additional load.
Running multiple processes of browsertime also does the job, and this way I collect more data points on the frontend performance.
I have my answer now, so we can close this issue.

Thank you for your support.
Cheers!
