### ISSUE TITLE
Windows NodeJs visualmetrics.py ffmpeg Segmentation fault

### ISSUE THREAD

**Issue by GeekZebre** [sitespeedio/browsertime#595]
I can run browsertime in Windows 10 with NodeJs.

I have an issue with 
`./bin/browsertime.js https://www.sitespeed.io/ --n 1 --video true -vvv --visualMetrics
`

This is the log of browsertime command : 
https://gist.github.com/GeekZebre/18e68268284427d0b30e4e974229a6b8

This is the log of the ffmpeg command : 
https://gist.github.com/GeekZebre/1b735333decd0232d5fce1912c1179b0

I have a Segmentation fault error.
I don't know why. I don't develop python.

Thanks.

**Comment by soulgalore** [comment]
Hi @GeekZebre I think the segmentation fault comes from ffmpeg?  Do you know if you run the latest versions? When I searched for the error it seems there has been problem before but I only found old 
 references. We haven't tested on Windows but it would be cool it it worked but it is the same as with sitespeed.io we only support running in Docker.

Best
Peter

**Comment by GeekZebre** [comment]
I run version 4.0 of ffmpeg.

ffmpeg cause segmentation fault during the 'find_video_viewport' function.

https://gist.github.com/GeekZebre/6da65b55f48d0bbcfe9da344062fad7c

The fonction doesn't create 'viewport.png' file.

Thanks.

**Comment by soulgalore** [comment]
Hi @GeekZebre you could look into what version of ffmpeg https://github.com/WPO-Foundation/wptagent uses on Windows, and/or create an upstream issue in https://github.com/WPO-Foundation/visualmetrics 

Best
Peter

**Comment by GeekZebre** [comment]
Ok.

I have read https://github.com/WPO-Foundation/wptagent/blob/master/docs/install.md and I notice this : 

> ImageMagick includes ffmpeg in the path automatically but not the latest version. It is usually easiest to just copy the static ffmpeg build over the one installed by ImageMagick.

So I copy ma ffmpeg.exe in ImageMagick and visualmetrics.py seems works.

**Comment by soulgalore** [comment]
ok, so ffmpeg issues then, closing.
