### ISSUE TITLE
proxy.pac usage in browsertime or docker run

### ISSUE THREAD

**Issue by vinay100sg** [sitespeedio/browsertime#609]
Hi @soulgalore ,

Could you please advise if there is a way to use a proxy.pac file in the docker run -browsertime options.

--browsertime.proxy.https [=host:port] works fine when we have all the domains resolved by the page hit is behind the proxy. The issue is, in our test environment the main (https://**main_domain.com**/login.html) page doesn't need to go through proxy; however, some of the resources (eg: https://**sub_domain.com**/required.png) are behind the proxy as the content is directly accessed from prod to construct the complete page. So, when hit the main page without proxy set we can see only html page without resources.

Simplest way we are thinking is to use the rules defined in the proxy.pac file to address this issue. However, if we give the option something like below,

--browsertime.proxy.https=http://XXX:pppp/proxy.pac OR
--proxy=http://XXX:pppp/proxy.pac

both options seem to be ignored and the test is running without proxy. Any help to address this would be highly appreciated.

Thanks,
Vinay

**Comment by soulgalore** [comment]
Hi @vinay100sg 
we are missing support for pac files but it looks like Selenium supports it see https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/proxy.html

We need to add an extra CLI param for the pac configuration and do some small changes when we setup the proxy. Do you have time to do a PR? We can help out to guide you?

Best
Peter

**Comment by vinay100sg** [comment]
Thanks @soulgalore ! Happy to contribute. I will try my best, kindly guide through.

**Comment by vinay100sg** [comment]
Hi @soulgalore ,

We made few changes in our local docker image and tried to test with a pac file. However, getting below error. 

**Error:**
[2018-06-26 06:03:30] INFO: Browser failed to start, trying one more time: unknown error: cannot parse capability: proxy
from unknown error: 'proxyAutoconfigUrl' must be a string
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
[2018-06-26 06:03:30] INFO: Browser failed to start, trying one more time: unknown error: cannot parse capability: proxy
from unknown error: 'proxyAutoconfigUrl' must be a string
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
[2018-06-26 06:03:30] INFO: Browser failed to start, trying one more time: unknown error: cannot parse capability: proxy
from unknown error: 'proxyAutoconfigUrl' must be a string
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
[2018-06-26 06:03:30] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Looks like this is related to selenium webdriver. Any help to address this issue?
https://github.com/SeleniumHQ/selenium/issues/5050 ---> Not sure if it is relevant

Below are the browsertime changes made,

1. Additional option added in cli.js:

**_File path:_** ./usr/src/app/node_modules/browsertime/lib/support/cli.js
  .option('proxy.pac', {
      type: 'string',
      describe: 'Proxy pac URL',
      group: 'proxy'
    }) 

2.  And tried to call proxy.pac inside the chrome webdriver index.js

**_File path:_**: ./usr/src/app/node_modules/browsertime/lib/chrome/webdriver/index.js
  const proxySettingsPac = pick(options.proxy, ['pac']);

  if (!isEmpty(proxySettingsPac)) {
    chromeOptions.setProxy(proxy.pac(proxySettingsPac));
  }

**Comment by soulgalore** [comment]
Hey @vinay100sg I'm not sure, try to isolate and just try out the configuration in Selenium and see if it works? 

Best
Peter

**Comment by soulgalore** [comment]
This is more of a Selenium issue, so closing,
