### ISSUE TITLE
Alias for single run with pageCompleteCheck 

### ISSUE THREAD

**Issue by BPrathap** [sitespeedio/browsertime#627]
Is possible to have alias for page with single run

example

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.3.5 https://www.sitespeed.io/  **---alias mycheck** . --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 10000;} catch(e) {} return true;})()

**Comment by BPrathap** [comment]
Thanks @soulgalore.  We have 100+ Pages where we entered in url.txt with alias . Then we moved to cli based  because of pageCompleteCheck but unfortunately we not able to give alias., which blocks us. If you any pointer then we can try by ourself or patch code to work.

**Comment by soulgalore** [comment]
Yeah but pageCompleteCheck should work with alias? Can you show we me an example, so we can fix that?

Best practice is first using a [configuration json file](https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json) and then override the individual parameters that you need. We should look into adding alias to the config file too, that would make it easier I think.

**Comment by BPrathap** [comment]
Here you go,  docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.3.5 https://www.sitespeed.io/ ---alias mycheck . --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 10000;} catch(e) {} return true;})()

To more specific,

In cli.js

  getAliases(urls) {
    const urlMetaData = {};
    urls = urls.map(url => url.trim());

    for (let url of urls) {
      if (url.startsWith('http')) {
        return {};

whenever user directly giving the url instead of text file. Then setting a alias as empty object.

**Comment by soulgalore** [comment]
Yeah but `--alias` isn't implemented or how do you mean? It was my understanding that if you use a file with URLs (where you also put the alias) and then add a pageCompleteCheck the alias doesn't work for you?

**Comment by BPrathap** [comment]
Example in url.txt have 2 pages and each page having its own logic of pageCompleteCheck functionality. which is not possible with url .txt . So I need to run via cli two times with different pageCompleteCheck but in that case i not able to give alias.

**Comment by soulgalore** [comment]
Ah I finally understand, sorry. Ok lets see how we can fix that. @beenanner I'll discuss this with you asap, I could probably implement something the coming days.

**Comment by soulgalore** [comment]
This is a sitespeed.io thing, so I created an issue for it there: https://github.com/sitespeedio/sitespeed.io/issues/2127 and closing this issue.

**Comment by soulgalore** [comment]
BTW @BPrathap having one specific pageCompleteCheck feels like a anti-pattern. Have you tried `--pageCompleteCheckInactivity` ?

Best
Peter
