### ISSUE TITLE
How can I test a website which requires user authentication 

### ISSUE THREAD

**Issue by SharonJacobMP** [sitespeedio/browsertime#628]
Hi, I'm trying to run sitespeed.io on an webpage that requires user authentication
1. I need to login to the portal
2. run sitespeed.io
How can I accomplish this?
I developed selenium e2e tests for this portal. trying to see if I can run sitespeed.io after I perform user login with selenium

**Comment by soulgalore** [comment]
Hi @SharonJacobMP you can use a preScript to login the user. The pre script is using Selenium (NodeJS flavor) and you need to follow a couple of patterns, checkout the documentation:
https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/

Best
Peter

**Comment by SharonJacobMP** [comment]
Hi @soulgalore, I tried to run the pre-script from the documentation. 
Doesn't look like I'm doing the right way. Can you help me with this command?
login.js has the code for user login 
url.txt has all the urls that I want to execute after user login

this is what I'm using with node 
const cmd = 'sitespeed.io --prescript login.js url.txt --config config.json'

**Comment by soulgalore** [comment]
HI @SharonJacobMP 
I think it's easier to just run it from CLI first so you can make it work, then run it from node (if you really need that). If you run it from within node you can follow the pattern of https://github.com/sitespeedio/grunt-sitespeedio/blob/master/tasks/sitespeedio.js instead of starting your own process.

Best
Peter

**Comment by soulgalore** [comment]
FYI: I'll be totally offline for the coming week, so please add a full example showing what not works (so we can reproduce) and then someone can help you. 

Best
Peter

**Comment by SharonJacobMP** [comment]
Hi @soulgalore, here's the sample code

What am I doing?
1. user login 
2. analyze the url with sitespeed.io
3. I'm running this from CL `sitespeed.io --prescript login.js https://www.facebook.com/marketplace/`

Expected result:
User login happens successfully 

Actual Result:
User login doesn't happen


Sample loginfb.js

`module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      // Go to Wikipedias login URL
      return driver.get(conf.ecxEnvironment)
        .then(() => {
          // You need to find the form, the login input fields and the
          // password field. Just add you name and password and submit the form
          // For more docs, checkout the NodeJS Selenium version
          // http://seleniumhq.github.io/selenium/docs/api/javascript/index.html
          // we fetch the selenium webdriver from context
          const webdriver = context.webdriver;
          // and get hold of some goodies we want to use
          const until = webdriver.until;
          const By = webdriver.By;
          // before you start, make your username and password
          const userName = conf.userName;
          const password = conf.password;
          await driver.manage().window().maximize()
          await driver.sleep(500)
          //Login to the FB page
          await driver.wait(until.elementLocated(By.id("email")),50000)
          await driver.findElement(By.id("email")).sendKeys(user)
          await driver.findElement(By.id("pass")).sendKeys(pass)
          await driver.findElement(By.id("loginbutton")).click()
          await driver.sleep(300)
          // we wait for something on the page that verifies that we are logged in
          return driver.wait(until.elementLocated(By.name("xhpc_message")),50000)
        });
    })
  }
};`

**Comment by SharonJacobMP** [comment]
Should I declare context somewhere?

**Comment by SharonJacobMP** [comment]
Had to remove await, and it worked well!
