### ISSUE TITLE
ERROR: Could not load URLUnexpectedAlertOpenError: unexpected alert open

### ISSUE THREAD

**Issue by msalles-winn** [sitespeedio/browsertime#632]
Reproduce :
Install browsertime with yarn : 
`sudo yarn global add browsertime`

Then try to get site speed with chrome emulation iPhone 6 : 

`browsertime -n 1 --video=false --visualMetrics=false --timeouts.pageCompleteCheck=60000 --browser=chrome --chrome.chromedriverPath=/usr/local/bin/chromedriver --chrome.binaryPath=/usr/bin/google-chrome --chrome.args="--no-sandbox" --chrome.args="--disable-dev-shm-usage" --headless=true --chrome.mobileEmulation.deviceName="iPhone 6" https://www.societegenerale.fr`

This returns : 

> [2018-09-03 12:38:26] INFO: Running chrome for url: https://www.societegenerale.fr
> [2018-09-03 12:38:26] INFO: Testing url https://www.societegenerale.fr iteration 1
> [2018-09-03 12:38:28] ERROR: Could not load URLUnexpectedAlertOpenError: unexpected alert open
>   (Session info: headless chrome=68.0.3440.106)
>   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-133-generic x86_64)
> [2018-09-03 12:38:28] ERROR: UrlLoadError: Failed to load https://www.societegenerale.fr
>     at SeleniumRunner.loadAndWait (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:189:13)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> [2018-09-03 12:38:28] INFO: 0
> [2018-09-03 12:38:28] INFO: Wrote data to browsertime-results/www.societegenerale.fr/2018-09-03T123826+0000

I tried to redefine alert function in the SeleniumRunner file, executing script into the driver ... But did not work.

I have found a commit of 2016 dealing with kind of error, but it seems to be really deprecated in Browsertime 3.x.

Any idea ?

**Comment by msalles-winn** [comment]
Problem solved. I did not see anything recent on the web these days, if someone wants the solution:

Add : 

`await driver.switchTo().alert().then(function(a) { driver.switchTo().alert().accept(); }, function() {});`

After the delay loop in the selenium runner js file.

**Comment by soulgalore** [comment]
Hi @msalles-winn so it works now for you?

One thing in your config. The Chrome args can skip the -- if I remember correctly so your `--chrome.args="--no-sandbox"` should be `--chrome.args="no-sandbox"`

Best
Peter

**Comment by msalles-winn** [comment]
It seems to work for some cases, but not all. I have a website this hack does not work for.

`browsertime -n 3 --video=false --visualMetrics=false --timeouts.pageCompleteCheck=20000 --browser=chrome --chrome.chromedriverPath=/usr/local/bin/chromedriver --chrome.binaryPath=/usr/bin/google-chrome --chrome.args="no-sandbox" --chrome.args="disable-dev-shm-usage" --headless=true --chrome.mobileEmulation.deviceName="iPhone 6" --timeouts.pageLoad=10000 --timeouts.script=15000 https://www.sogecartenet.fr/`

It seems that the switchTo().alert() sometime freezes.

It sometime works for 2 iterations but not 3. I changed the navigate part of the code to use `driver.navigate().to(...)`, it seems to be more stable like that, but still don't work for 3 iterations.

Any idea ?
