### ISSUE TITLE
Unable to end the test on demand. --browsertime.pageCompleteCheck 'return true;' --browsertime.pageLoadStrategy none

### ISSUE THREAD

**Issue by PedroS-D** [sitespeedio/browsertime#644]
Hi,

I'm using sitespeed.io/7.4.0 to test my website. My Test must end on event either of the following events:
- domComplete OR
- domContentLoadedEventEnd
(i prefer the later).

when run docker, I add following options:

```
docker run --net=host --rm --shm-size=1g -v ${BASEDIR}/sitespeed.io:/sitespeed.io \
-v ${BASEDIR}/Madrid:/etc/localtime:ro \
'sitespeedio/sitespeed.io:7.4.0' \
"--speedIndex" \
"--firstParty" \
".*.mysite.com.*" \
"--connectivity" \
"native" \
"--mobile" \
"false" \
"--browsertime.viewPort" \
"1366x708" \
"--browsertime.chrome.timeline" \
"true" \
"--browsertime.browser chrome" \
--browsertime.pageCompleteCheck 'return true;' \
--browsertime.iterations 1 \
--browsertime.pageLoadStrategy none \
"https://mysite.com"
```

But the test ends way after the loadEventEnd
(note that on the last test, I'm using --browsertime.pageCompleteCheck 'return true;' !. instead of
return window.performance.timing.domContentLoadedEventEnd > 0 ; ). Look at timeline!!

<img width="707" alt="screen shot 2018-10-04 at 15 35 11" src="https://user-images.githubusercontent.com/40207369/46477546-2b26b880-c7eb-11e8-8790-3783a9f76643.png">

I have read all of these posts:
- https://github.com/sitespeedio/browsertime/issues/278
- https://github.com/sitespeedio/browsertime/issues/349
- https://github.com/sitespeedio/browsertime/issues/373
- https://github.com/sitespeedio/browsertime/issues/430

and they said this should be fixed, that does not seem to be the case on the latest version,

also this one
https://github.com/sitespeedio/pagexray/issues/17
suggested collecting it all on the HAR, and then processing it... but there are no explanations on how.

Can you tell if it is possible to end a test and compute all metrics either on domContentLoadEventEnd or domComplete?

an example would be trully appreciated, as I spent a couple of days testing javascripts with no luck.

Best Regards,

**Comment by soulgalore** [comment]
Hi @PedroS-D maybe the docs are miss leading, it works like this:
when you configure pageLoadStrategy none, Browsertime will get control as soon as the navigation started. However first the we have loop that waits on navigation to start that can add worst case 500 ms, and then when we get back in control, we start to run all the JavaScript we do to fetch all the metrics, so we don't close the browser, we get control and run tests but the browser will still continue to fetch responses and populate browser APIs.

We categorize requests/responses, checkout http://examples.sitespeed.io/7.x/en.wikipedia.org/2018-06-27-05-33-14/pages/en.wikipedia.org/wiki/Main_Page/index.html#pagexray (scroll down) for an example. That is already implemented and you should be able to see it on your result page.
Best
Peter

**Comment by PedroS-D** [comment]
@soulgalore Hi Peter, thanks for your prompt reply.

From the example, and my execution, I understand that I can only get to calculate results either on graphite, by processing the difference between the total  (Requests per response code) and the available checkpoints (Requests loaded after onLoad event / Requests loaded after onContentLoad) or processing the HAR file.
Also, I'll take it that the design goal on the --browsertime.{pageCompleteCheck,pageLoadStrategy} is to extend the check beyond the default 2 seconds AFTER the loadEventEnd, shall we need to do that on site, but never to stop the execution before the browser api gets populated.

Is this correct? if so I'm happy to close the issue.

Best Regards,

**Comment by PedroS-D** [comment]
@soulgalore  Thanks.
