### ISSUE TITLE
Firefox proxy port not being set properly

### ISSUE THREAD

**Issue by dpalmeiro** [sitespeedio/browsertime#701]
When using the --proxy.http and --proxy.https options, the hostnames are set properly, ,but the ports are always set to 80, and 443 for http and SSL proxies.

A simple example:
browsertime https://www.sitespeedio.com --skipHar -b firefox --proxy.http localhost:8080 --proxy.https localhost:8080
If you navigate to preferences->network settings, you'll see that the ports are not set to 8080.  

This appears to be an existing bug in selenium:  https://github.com/SeleniumHQ/selenium/issues/5627

**Comment by soulgalore** [comment]
Thank you @dpalmeiro for the fix. I'm working in getting 4.0 to reach stable, but got a couple of alphas and one/two betas before it will be released, so it will take some time before this reach stable.

Best
Peter
