### ISSUE TITLE
UserTiming & ResourceTiming fails on IE 11 on Windows

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#71]
When fetching things like:
<code>window.performance.getEntriesByType('resource')</code>, there's a stacktrace returned instead of the values.

<pre>
{"url":"http://www.sitespeed.io","runs":1,"browserName":"internet explorer","browserVersion":"11","platform":"WINDOWS","userAgent":"","windowSize":"unknown","browserTimeVersion":"0.8.19","statistics":[{"name":"serverConnectionTime","min":"-455","max":"-455","p10":"-455","p70":"-455","p80":"-455","p90":"-455","p99":"-455","median":"-455","mean":"-455"},{"name":"pageLoadTime","min":"
erverResponseTime","min":"1","max":"1","p10":"1","p70":"1","p80":"1","p90":"1","p99":"1","median":"1","mean":"1"},{"name":"frontEndTime","min":"228","max":"228","p10":"228","p70":"228","p80":"228","p90":"228","p99":"228","median":"228","mean":"228"},{"name":"backEndTime","min":"457","max":"457","p10":"457","p70":"457","p80":"457","p90":"457","p99":"457","median":"457","mean":"457"}
"median":"662","mean":"662"},{"name":"domInteractiveTime","min":"662","max":"662","p10":"662","p70":"662","p80":"662","p90":"662","p99":"662","median":"662","mean":"662"},{"name":"redirectionTime","min":"1","max":"1","p10":"1","p70":"1","p80":"1","p90":"1","p99":"1","median":"1","mean":"1"},{"name":"speedIndex","min":"690","max":"690","p10":"690","p70":"690","p80":"690","p90":"690"
:"690","p90":"690","p99":"690","median":"690","mean":"690"}],"data":[{"firstPaint":690,"navigation":{"fetchStart":1419283917348,"redirectStart":0,"domComplete":1419283918027,"redirectEnd":0,"loadEventStart":1419283918032,"navigationStart":1419283917347,"requestStart":1419283917803,"responseEnd":1419283917804,"secureConnectionStart":null,"domLoading":1419283917804,"domInteractive":1
,"connectEnd":1419283917348,"responseStart":1419283917804,"unloadEventStart":0,"domContentLoadedEventEnd":1419283918019,"connectStart":1419283917348,"unloadEventEnd":0,"domainLookupStart":1419283917348},"resources":[{"driver_":{"session_":{},"executor_":{},"flow_":{"events_":{},"timer":{},"history_":[{"parent_":null,"promise":{},"description_":"WebDriver.executeScript()","snapshot_
me\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:1346:18)\n    at webdriver.WebDriver.schedule (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\webdriver.js:345:15)\n    at webdriver.WebDriver.executeScript (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\webdrive
ach (native)\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\lib\\browsertime.js:127:30\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\goog\\base.js:1582:15\n    at webdriver.promise.ControlFlow.runInNewFrame_ (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:16
river\\promise.js:465:12)\n    at notifyAll (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:442:7)"}}],"activeFrame_":{"flow_":"[Circular ~.data.0.resources.0.driver_.flow_]","parent_":{"flow_":"[Circular ~.data.0.resources.0.driver_.flow_]","parent_":{"flow_":"[Circular ~.data.0.resources.0.driver_.flow_]","parent_":n
ndingTask_":null,"isLocked_":true,"isWaiting":false,"onComplete":null,"onAbort":null},"children_":["[Circular ~.data.0.resources.0.driver_.flow_.activeFrame_]"],"lastInsertedChild_":null,"pendingTask_":null,"isLocked_":true,"isWaiting":false},"children_":[{"flow_":"[Circular ~.data.0.resources.0.driver_.flow_]","parent_":"[Circular ~.data.0.resources.0.driver_.flow_.activeFrame_]",
er_.flow_.activeFrame_.children_.0]","children_":[{"flow_":"[Circular ~.data.0.resources.0.driver_.flow_]","parent_":"[Circular ~.data.0.resources.0.driver_.flow_.activeFrame_.children_.0.children_.0]","children_":[{"parent_":null,"promise":{},"description_":"WebDriver.quit()","snapshot_":{"slice_":1,"stack_":"    at webdriver.promise.ControlFlow.execute (C:\\Users\\peter\\Document
river.schedule (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\webdriver.js:345:15)\n    at webdriver.WebDriver.quit (C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\selenium-webdriver\\lib\\webdriver\\webdriver.js:418:21)\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\lib\\browsertime.js:150:30\n    at
\\peter\\Documents\\GitHub\\browsertime\\node_modules\\async\\lib\\async.js:135:19)\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\async\\lib\\async.js:32:16\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\async\\lib\\async.js:251:21\n    at C:\\Users\\peter\\Documents\\GitHub\\browsertime\\node_modules\\async\\lib\\async.js:575:34\n
lar ~.data.0.resources.0.driver_.flow_.activeFrame_.children_.0.children_.0.children_.0.children_.0]","pendingTask_":null,"isLocked_":false,"isWaiting":false,"onComplete":null,"onAbort":null}],"lastInsertedChild_":"[Circular ~.data.0.resources.0.driver_.flow_.activeFrame_.children_.0.children_.0.children_.0]","pendingTask_":null,"isLocked_":false,"isWaiting":false,"onComplete":null
en_.0]","pendingTask_":null,"isLocked_":false,"isWaiting":false,"onComplete":null,"onAbort":null}],"lastInsertedChild_":"[Circular ~.data.0.resources.0.driver_.flow_.activeFrame_.children_.0]","pendingTask_":null,"isLocked_":true,"isWaiting":false},"schedulingFrame_":null,"shutdownId_":null,"eventLoopId_":{"_idleTimeout":10,"_idlePrev":{"_idleNext":"[Circular ~.data.0.resources.0.d
dleNext":"[Circular ~.data.0.resources.0.driver_.flow_.eventLoopId_._idlePrev]","_idleStart":1419283919045,"_repeat":true},"pendingRejections_":0,"numAbortedFrames_":0}},"id_":{}},{"driver_":"[Circular ~.data.0.resources.0.driver_]","id_":{}},{"driver_":"[Circular ~.data.0.resources.0.driver_]","id_":{}},{"driver_":"[Circular ~.data.0.resources.0.driver_]","id_":{}},{"driver_":"[Ci
edIndex":690,"timings":{"serverConnectionTime":-455,"domainLookupTime":0,"pageDownloadTime":0,"pageLoadTime":685,"serverResponseTime":1,"frontEndTime":228,"backEndTime":457,"domContentLoadedTime":662,"domInteractiveTime":662,"redirectionTime":1},"userTiming":{"marks":[{"driver_":"[Circular ~.data.0.resources.0.driver_]","id_":{}},{"driver_":"[Circular ~.data.0.resources.0.driver_]"
info: Storing C:\Users\peter\Documents\GitHub\browsertime\www.sitespeed.io.har
info: Storing C:\Users\peter\Documents\GitHub\browsertime\www.sitespeed.io.json
info: Stopping proxy
</pre>

**Comment by parangsjo** [comment]
Hello,

I'm extremely grateful to you for all you have done, please read my message for you here <http://tetindywo.gearinstall.com/xykguv>

Hope this helps, pa@rangsjo.com

**Comment by soulgalore** [comment]
Closing this since it totally new implementation in 1.0
