### ISSUE TITLE
Error running browsertime TypeError: Cannot read property 'timings' of undefined

### ISSUE THREAD

**Issue by hamza88** [sitespeedio/browsertime#733]
`browsertime --version`
4.0.3

`sitespeed.io --version`
8.0.3

`browsertime https://www.topshop.com/ `

Mac OS moJave 10.14.1

Google Chrome Version 71.0.3578.98

`ERROR: Error running browsertime TypeError: Cannot read property 'timings' of undefined
    at addExtraFieldsToHar (/Users/hamzarazzak/.nvm/versions/node/v8.9.4/lib/node_modules/browsertime/lib/core/engine/index.js:46:25)
    at Engine.runByScript (/Users/hamzarazzak/.nvm/versions/node/v8.9.4/lib/node_modules/browsertime/lib/core/engine/index.js:139:7)
    at <anonymous>`

Strangely .., works ok when testing http://www.amazon.co.uk

**Comment by hamza88** [comment]
Thanks for the quick reply!

**Comment by soulgalore** [comment]
Yeah but not sure though how we would solve it ...

**Comment by hamza88** [comment]
Fair enough .. is there any way to limit the iteration to just the single one rather than 3 iterations?

**Comment by soulgalore** [comment]
I'll fix so we catch the error and log it better. Use `--iterations` to choose number of iterations. 

Best
Peter

**Comment by soulgalore** [comment]
This should be fixed in the latest release: I've switched so it collects data under the URL that you give as a test (as it worked prior to 4.0).
