### ISSUE TITLE
Set cookie on a different domain than the tested one

### ISSUE THREAD

**Issue by kazazor** [sitespeedio/browsertime#737]
Hi everyone, first of all, AMAZING tool!!

I would like to test my website which is protected by a login page.

## Setting a different domain for the cookie
This website is part of multiple websites which `share the login between them`.

For example:
Website A: `https://a.hello.com`
Website B: `https://b.hello.com`
Login page: `https://hello.com`

The cookie that we're storing is registered under the domain: `.hello.com`

Let's assume I would like to test `https://a.hello.com`.
Therefore, when testing using sitespeedio `docker image`, I'm required for the cookie to be set to the `.hello.com` domain and NOT to the `https://a.hello.com` URL.

This is the command I run:
```shell
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3-plus1 https://a.hello.com --browser chrome -n 1 --connectivity custom --downstreamKbps 20480 --upstreamKbps 5120 --viewPort "1366x708" --speedIndex --video --fps 30 --cookie session=<my_cookie_no_question_marks_or_anything_special>
```

According to the docs [How do I set a cookie?](https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#how-do-i-set-a-cookie) the way to go is indeed using the `--cookie` flag, but it also says:
>The cookie will be set on the domain that you test

I believe this is the root cause of me not being able to successfully login to the site when running the above command.

Can anyone please advise what can be done? Am I missing something? Is there a way for the cookie to be registered to a different domain than the tested URL one?

Thanks in advance and again, great tools!

More info:
Using docker for mac: 2.0.0.0-mac81 (29211)
macOS: 10.14.2 (18C54)

**Comment by soulgalore** [comment]
I think you can do this now with the https://chromedevtools.github.io/devtools-protocol/ if you use scripting.
