### ISSUE TITLE
Visual Metrics picks up small orange using Chrome

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#755]
Updated to the latest Visual Metrics we removed our fix for checking that there are no partial orange in the screen. 

![ms_000000](https://user-images.githubusercontent.com/540757/52197909-7ae0c380-2861-11e9-94b1-d0bbaea7bdc7.jpg)

This give some page a really early first visual change.

**Comment by soulgalore** [comment]
Some fixes in https://github.com/sitespeedio/browsertime/pull/757 rolled out in 4.2.2.

**Comment by soulgalore** [comment]
This is dependent on FPS. If we use 60 fps this happens often. 30 fps its better. And I guess 10 fps will eliminate it.

**Comment by soulgalore** [comment]
Haven't seen this since the switch to 30 fps.

**Comment by soulgalore** [comment]
I still see this on our test instance:
<img width="804" alt="Screen Shot 2019-06-08 at 19 59 38" src="https://user-images.githubusercontent.com/540757/59150703-02b12700-8a28-11e9-8572-71a7fec658d8.png">

**Comment by soulgalore** [comment]
The 33 ms is a sign of that the small orange bit picks up the orange. I think we should fine tune Visual Metrics again.

**Comment by soulgalore** [comment]
This is better now but still happens. We should do another fix in Visual Metrics so we the bottom area is larger and maybe fine tune the area that could be orange.

**Comment by soulgalore** [comment]
This is still an issue:
![ms_000000](https://user-images.githubusercontent.com/540757/72890527-5bf96c80-3d12-11ea-840f-7454962261f3.jpg)

Let me try to reproduce with an original video so its easier to fix. Ping @tarekziade is this something you have seen? Maybe there's a smarter way than the fix I've been trying out.

**Comment by tarekziade** [comment]
@sefeng211 do you have an idea?

**Comment by sefeng211** [comment]
Sorry I was on PTO last week, I'll take a look sometime this week.

**Comment by soulgalore** [comment]
Let me know @sefeng211 if you have time to take a look. I think somewhere there's bug either how we check "the bottom" of the screen or if it could be the margin that also messes it up. or if there's just a better way to check.

**Comment by sefeng211** [comment]
@soulgalore Sorry, didn't get a chance to look it last week. And I misunderstood the bug, I thought it was related to the converting 60fps PR we merged. 
I don't think I fully understand what is happening. Is this Chrome desktop? And there are partial orange frame left when cropping? 
I'll spend some time to look it tomorrow, not sure I can find anything though as I have never seen this before.

**Comment by soulgalore** [comment]
@sefeng211 ah sorry I didn't give you the background. 

Running Chrome on Linux doesn't sync the screen 100% so for example when we first set the screen to orange and then turn it white (to white to signal that the navigation happens) in some cases a frame could be 50% white/50% orange or 90%white/10% orange. And then Visual Metrics analyse that, it picks up the change to fully white as the first visual change.

The code for checking if its a color frame: https://github.com/sitespeedio/browsertime/blob/master/browsertime/visualmetrics.py#L809-L866 - I've seen at work that we sometimes have first visual change that is direct of the navigation with small orange line at the bottom as first frame.

**Comment by sefeng211** [comment]
@soulgalore Sorry I still didn't get a chance to look into it and I am not sure that I'll be able to do it anytime soon :(

**Comment by soulgalore** [comment]
Closing this since I will implement a new version. Lets create new issues for that version.
