### ISSUE TITLE
New timestamp in the video introduced some flickering in the time stamp

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#771]
See https://github.com/sitespeedio/browsertime/pull/770

**Comment by ponyo877** [comment]
I will work on that correction.

**Comment by soulgalore** [comment]
I wonder what's the best way to fix this? We could have a hardcoded left position (instead of using the size of the text) but then we would have some small flickering to the right. Or should we switch font, is that the problem?

**Comment by soulgalore** [comment]
Had a quick look but couldn't find a good solution with the current look and fell so I removed the box. Let me know @ponyo877 if you have an suggestion how we can do it better, else stick with the new PR and push fix release.

**Comment by ponyo877** [comment]
Please check PR #773

**Comment by soulgalore** [comment]
Cool, thanks @ponyo877

**Comment by soulgalore** [comment]
@ponyo877 it's strange, it got the same behavior as my fix (it works local on my machine), checkout the video:
https://s3.amazonaws.com/results.sitespeed.io/en.wikipedia.org/2019-02-15-09-39-21/pages/en.wikipedia.org/wiki/Barack_Obama/data/video/1.mp4

That's from our test server.

**Comment by ponyo877** [comment]
oh, I think more

**Comment by soulgalore** [comment]
This is pretty annoying, lets take this up again.

**Comment by soulgalore** [comment]
Fixed in https://github.com/sitespeedio/browsertime/pull/944
