### ISSUE TITLE
Full screenshot / screenshot with scroll support?

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#792]
Is there any arg/flag that I can add to make the full screenshot of a page if the page needs to be scrolled down to get the full view? Currently, Browsertime seems to only take the upper area of a given webpage.

**Comment by soulgalore** [comment]
Hi @phongiswindy not at the moment.  It takes the viewport. The last time (but that was maybe a couple of years ago) webdriver (that we use through Selenium) didn't support full screenshots. I've checked again and it seems to be the issue: https://github.com/w3c/webdriver/issues/1283

But it seems to be a workaround for Firefox, but I haven't looked if there's one for Chrome.

Best
Peter

**Comment by phongiswindy** [comment]
@soulgalore, thank you for the prompt reply. I would love to see this implemented. I am currently using browsertime with firefox, I would be really thankful if you could give me some pointers to any aforementioned workarounds out there.

**Comment by soulgalore** [comment]
It looks like Geckodriver should support it now: https://bugzilla.mozilla.org/show_bug.cgi?id=1431148 but I haven't looked at how to actually use it. This os low prio for me but if you can do a PR I could look at it. 

Best
Peter

**Comment by ozcoder** [comment]
I'm using these flags to get a long (and big) screenshot
`--screenshotParams.maxSize=4504 --viewPort="1024x4580"`
As a workaround. But the images are huge, about 14Mb PNG, or 2Mb JPG @ 75%

**Comment by soulgalore** [comment]
Closing, let us open a new issue when webdriver supports it.
