### ISSUE TITLE
Need a guidline for spinning up docker without removing the instance after finish

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#793]
Currently, I can see that our guidelines for Docker usage always have a flag `--rm` for removing the container after finish. Since spining up a container instance and tearing it down can be expensive, I wonder if we could please also add some guidelines for re-using these instance for future run?

**Comment by soulgalore** [comment]
> Since spining up a container instance and tearing it down can be expensive

Yeah I've heard this a couple of times but I haven't seen any actual metrics what it means to us :) What I kind of like with creating a new is that we always start from a clean slate. 

However if you wanna try it out, you need to look into the [start script](https://github.com/sitespeedio/sitespeed.io/blob/master/docker/scripts/start.sh) on how to start and override that.

Best
Peter

**Comment by soulgalore** [comment]
Please let me know if you need anymore info!
