### ISSUE TITLE
'document.body.style.display = "none" can not make background white

### ISSUE THREAD

**Issue by luisxiaomai** [sitespeedio/browsertime#795]
Use below code from https://www.sitespeed.io/documentation/sitespeed.io/scripting/#pass-your-own-options-to-your-script. If you want to click a link and make sure the background is white, you can hide the HTML and then click the link.

```
module.exports = async function(context, commands) {
    await commands.measure.start('https://www.sitespeed.io');
    // Hide everything
    await commands.js.run('document.body.style.display = "none";');
    // Start measurning
    await commands.measure.start();
    // Click on the link and wait on navigation to happen
    await commands.click.bySelectorAndWait('body > nav > div > div > div > ul > li:nth-child(2) > a');
    return commands.measure.stop();
};
```
But from the result video or filmstrip, it can not make sure the background is white.

![test](https://user-images.githubusercontent.com/6835229/53725357-c9a46c00-3ea6-11e9-8fec-e4e559f6d0ca.png)

**Comment by soulgalore** [comment]
Hi @luisxiaomai yeah that's right. It works like this at the moment:
- we add a layer of orange on top of the screen (and make the body show)
- start the video recording
- remove the layer 

So I think there's a mismatch there, since when we remove the orange layer, the old view is there. 

Best
Peter

**Comment by soulgalore** [comment]
Depending on the page you wanna test, you can hide all children to the body, something like:
`for (let node of document.body.childNodes) { if (node.style) node.style.display = "none";}'`

but if you have body background you need to hack that too. I'll change the documentation tonight that should change it according to your site.

**Comment by luisxiaomai** [comment]
@soulgalore thanks a lot , it works.
