### ISSUE TITLE
Can't customize Screenshot filename.

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#796]
It seems like the flag `--output` will only have effect on the `.json` and `.har` files exported, while the screenshot's filename is still exported as`1.jpg`. Also, setting `--useSameDir true` will only make `.json` and `.har` saved in the same dir, while the screenshots are saved in a diff dir named `screenshots` with file named `1.jpg` in it. Is there anyway to output all of these files (`.json`, `.har`, `.jpg`) under the same directory with the same output name (i.e., `name.json`, `name.har`, and `name.jpg`)?
 
<img width="351" alt="screen shot 2019-03-05 at 1 30 06 am" src="https://user-images.githubusercontent.com/11869279/53785433-7f42df80-3ee6-11e9-8d89-4de734a1c362.png">

Note that I already turned `--screenshot true` to make sure that there will only one screenshot will be exported, and turned off video recording.

**Comment by soulgalore** [comment]
I agree this isn't super clean. Introducing 4.0 we added the new path structure and added the `--useSameDir` but the name probably should have been legacyDirStructure since follow the old structure with a own dir for screenshots.

Can you explain your use case, maybe there's a workaround?

Best
Peter

**Comment by phongiswindy** [comment]
Ah I see, it's not a big deal at all. I will just write some scripts to make the dir name clearer. Just thought that these flags could do some desired jobs. In the documentation, shouldn't `Store all files is the same structure` be `Store all files IN the same structure`, typo?

**Comment by soulgalore** [comment]
Ok cool closing then.
