### ISSUE TITLE
SpeedIndex and FirstPaint resulting in -1

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/browsertime#83]
When running browsertime with phantomjs2 the resulting JSON file shows the following:
```
[...]
	"firstPaint": {
		"min": "-1",
		"max": "-1",
		"p10": "-1",
		"p70": "-1",
		"p80": "-1",
		"p90": "-1",
		"p99": "-1",
		"median": "-1",
		"mean": "-1"
	},
	"speedIndex": {
		"min": "-1",
		"max": "-1",
		"p10": "-1",
		"p70": "-1",
		"p80": "-1",
		"p90": "-1",
		"p99": "-1",
		"median": "-1",
		"mean": "-1"
	}
[...]
```

I am not sure if this is an issue of this repository or of a sub-component.

On debian with 2.0.1-development self-compiled
```
root@xxxxxx ~ # browsertime -u http://www.toptarif.de -n 1 -b phantomjs
info: Starting proxy on port 2001, will wait at most 15000 ms
info: Fetching http://www.toptarif.de (1 of 1)
info: Storing /root/www.toptarif.de.har
info: Storing /root/www.toptarif.de.json
info: Stopping proxy
```
On windows with phantomjs 2.0.0 from phantomjs.org
```
C:\Users\wieczorekp\Desktop>browsertime -u http://www.toptarif.de -n 1 -b phantomjs
info: Starting proxy on port 2001, will wait at most 15000 ms
info: Fetching http://www.toptarif.de (1 of 1)
info: Storing C:\Users\xxxxx\Desktop\www.toptarif.de.har
info: Storing C:\Users\xxxxx\Desktop\www.toptarif.de.json
info: Stopping proxy
```
The results are the same.

**Comment by soulgalore** [comment]
yes, I need to add some docs. So it is like this: the RUM Speed Index needs a browser that supports the resource timing API (today Chrome, Firefox and IE (but it doesn't work in IE) and if the browser doesn't support firstPaint natively, the resource timings is used to calculate it. PhantomJS has not support for the resource timing API.
