### ISSUE TITLE
Override DNS lookups

### ISSUE THREAD

**Issue by bessdsv** [sitespeedio/browsertime#84]
In my project i want function of BrowserMob Proxy Rest API :

POST /proxy/[port]/hosts - Overrides normal DNS lookups and remaps the given hosts with the associated IP address
Payload data should be json encoded set of name/value pairs (ex: {"example.com": "1.2.3.4"})

**Comment by tobli** [comment]
Hi, thanks for the feature request. Right now I won't be able to prioritize implementing this. Improving stability, especially on Linux/Chrome is my main focus right now. Additionally I'd prefer to get rid of BrowserMobProxy in the future, to not have to rely on Java. Starting up BMP adds significant time to running Browsertime. Hence I'm hesitant to adding more functionality at this stage that relies on BMP.

That said, there are other options you could try. Would it be feasible for you to edit your host file to do the remapping? For Linux browsers you could try running Browsertime within a Docker container to avoid a system wide dns override.

**Comment by soulgalore** [comment]
> For Linux browsers you could try running Browsertime within a Docker container to avoid a system wide dns override.

Yep, anyone who can help us out with a PR for the docs on how to do that?

**Comment by soulgalore** [comment]
If you use Chrome you could do something like we did in https://github.com/sitespeedio/browsertime/pull/840/files
