### ISSUE TITLE
About Proxy vs NoProxy 

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/browsertime#857]
Is it possible to use NO PROXY for just the PAGE itself -- but all the resources on page are still going thru PROXY -- while testing on AWS?

Any thoughts..?

**Comment by soulgalore** [comment]
Hi @softwareklinic no I don't think so. Whats your use case, what do you need to do?

Best
Peter

**Comment by soulgalore** [comment]
Closing, let me know if you still need it and please give me the use case :)
