### ISSUE TITLE
Opening browsertime with the DevTool tab

### ISSUE THREAD

**Issue by gogo9th** [sitespeedio/browsertime#865]
Hi,

I wonder if there is a way to open up browsertime's chrome window with the DevTool tab enabled from the very beginning.

**Comment by soulgalore** [comment]
Hi @gogo9th check if you can do that with a Chrome switch: https://peter.sh/experiments/chromium-command-line-switches/

Then you can add that like `--chrome.args my-switch`

Best
Peter

**Comment by soulgalore** [comment]
Closing this, let me know if you needed something more.
