### ISSUE TITLE
Response bodies not displayed in Waterfall html

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/browsertime#894]
Dockerized Sitespeed 9.6.0

Config:
```
"chrome": {
    "includeResponseBodies": "html"
```

```
"firefox": {
    "includeResponseBodies": "html"
```

Response bodies are not listed in the waterfall html even with this enabled.

**Comment by soulgalore** [comment]
The fix for this will go out in the next release, probably the coming weekend.

**Comment by leathej1** [comment]
Thanks!

**Comment by soulgalore** [comment]
Released this in sitespeed.io earlier today.

**Comment by soulgalore** [comment]
This was fixed long time ago!
