### ISSUE TITLE
fullyLoaded.js, how it works?

### ISSUE THREAD

**Issue by Uladik** [sitespeedio/browsertime#909]
Hi Guys! Could you please explain how fullyLoaded.js works? I tried to find explanation in documentation and didn't find anything. I need to measure how long page loaded, and i want figure out can i trust fullyLoaded metric.
Thanks in advance!

**Comment by Uladik** [comment]
I know i can do it by waiting a certain element using xpath, but i wonder if i can escape it:)

**Comment by soulgalore** [comment]
Hi @Uladik we get the fullyLoaded metric from the HAR file (when the last response has finished), you can check the code here:

https://github.com/sitespeedio/browsertime/blob/master/lib/support/har/index.js#L68-L95

Best
Peter

**Comment by Uladik** [comment]
@soulgalore thank you!
