### ISSUE TITLE
Can't run Firefox extension

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#954]
I am getting an error `INFO: Browser failed to start, trying one more time: ffOptions.addExtension is not a function` when running browsertime with some firefox extension using the flag `--extension`. Following the `--extension` flag is a path to an **.xpi** file that I downloaded from https://addons.mozilla.org/.

I am not sure if it's because an `s` is missing from `ffOptions.addExtension` here https://github.com/sitespeedio/browsertime/blob/7d671f1bbbf010c90c565e7ca78bc3ab9a4f01fc/lib/firefox/webdriver/index.js#L70 ?

**Comment by soulgalore** [comment]
Thank you @phongiswindy for reporting, yep it's a bug on our side, let me fix that ASAP.

Best
Peter

**Comment by soulgalore** [comment]
I think this was broken when we upgraded to Selenium 4 and missed that in the upgrade.

**Comment by phongiswindy** [comment]
Thank you @soulgalore so much for your prompt response. Do you have a rough estimation when I will be able to pull the latest fixed version (6.1.2) from docker hub?
Best regards,
Phong

**Comment by soulgalore** [comment]
Yes it should work now :)

Best
Peter

**Comment by phongiswindy** [comment]
thanks! I was able to pull 6.1.2 from docker. However, it seems like the path navigation doesn't work. Now I get another error `INFO: Browser failed to start, trying one more time: ENOENT: no such file or directory, open <the path to xpi on the parent machine that already specified>`.

Sorry for keeping bugging you :)

**Comment by phongiswindy** [comment]
NVM! I got it worked. I would have to provide the path to the extension in the docker, not the relative path from the parent machine! Please go ahead and close this ticket! Thanks again for your help.

**Comment by soulgalore** [comment]
Great that it worked!
