### ISSUE TITLE
Failed to load extension from . : Manifest is missing or unreadable

### ISSUE THREAD

**Issue by gogo9th** [sitespeedio/browsertime#975]
Hi,

Browsertime doesn't seem to work properly anymore for chromium. If I run the following command:

`node node_modules/browsertime/bin/browsertime https://www.google.com`

 I get the following error window:

`Failed to load extension from . : Manifest is missing or unreadable`

Could you please look into this issue as soon as possible, because I need to collect experimental results urgently...

**Comment by soulgalore** [comment]
What version of Chromium are you using? What Chromedriver? What OS are you using? Any special reason why you run as **node_modules/browsertime/bin/browsertime**?

You can disable loading the web extension with `--chrome.disableWebExtensions`.

**Comment by gogo9th** [comment]
Hi Peter,

I tried both:
browsertime --chrome.disableWebExtensions https://www.google.com
--> This gives the same error

nodejs node_modules/browsertime/bin/browsertime --chrome.disableWebExtensions https://www.google.com
--> This gives the error message: "browsertime [options] <url>/<scriptFile>"

I tried the same on a freshly installed Ubuntu 19.10, but doesn't work. So I think something is broken on browsertime during a recent update, or Ubuntu 19.10 is incompatible with it...?

**Comment by soulgalore** [comment]
We run latest Chrome and Chrome driver in Docker in Ubuntu 19 where it works, so I don't think that's a problem.

You said you are using Chromium, what Chromium version/build are you using? We usually just test with Chrome.

Chrome and Chromedriver need to match, that's why its important to know which versions you are using. On Friday we will release a new version of Browsertime that comes bundled with latest Chromedriver, if you run a newer version you may need to download Chromedriver yourself.

Best 
Peter

**Comment by gogo9th** [comment]
Hi Peter,

I freshly re-installed 19.10 (not 19.04) on my laptop twice and tried browsertime, but I get the same error message. After installing Ubuntu 19.10, I typed the following:

sudo apt install vim npm nodejs chromium-browser -y
sudo npm install -g npm@latest
npm install browsertime
node node node_modules/browsertime/bin/browsertime https://www.facebook.com

And the error message is:

Failed to load extension from . : Manifest is missing or unreadable

Have you tried it with Ubuntu 19.10? I wonder if you could look into this issue as soon as possible, because I am supposed to start my speed index experiments today...

**Comment by soulgalore** [comment]
Hi @gogo9th thanks for showing exactly how you do, that will make it easier to reproduce, I will try that tomorrow. I never tried Chromium (only Chrome), but I can give it a shoot, it seems strange that it would not work. And you need Chromium for your tests and not Chrome then I guess?

Best
Peter

**Comment by gogo9th** [comment]
Hi Peter, 

When it used to work, I it worked for chromium-browser v78 (installed by apt get install chromium-browser), chrome v79 (downloaded directly from the chromium binary archive), and chrome v78 (downloaded directly from the chromium binary archive https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/). But now  none of them seems to work...

**Comment by soulgalore** [comment]
Can you try using Chrome instead? You can follow over Dockerfile how to install it:
https://github.com/sitespeedio/docker-browsers/blob/master/Dockerfile

**Comment by danyaljj** [comment]
There is no update on this thread?

**Comment by soulgalore** [comment]
It worked when I tried it, can you help me making a reproducible test case @danyaljj ?

**Comment by soulgalore** [comment]
Never got feedback on how to reproduce, please let me know if it is still an issue.
