### ISSUE TITLE
visualmetrics with "carousel" element 

### ISSUE THREAD

**Issue by matti** [sitespeedio/browsertime#993]
Visualmetrics last visual change for https://www.kaalimato.com/ is ~25s because the carousel keeps changing the page - is there any way to mitigate this?

**Comment by soulgalore** [comment]
I looked into it now, since we have the same problem at work. Well, it would need quite many changes and I don't see this happening any time soon.

**Comment by matti** [comment]
what kind of changes? if you help me out a bit, maybe I could try to do a PR?

**Comment by soulgalore** [comment]
Ooops I looked at the wrong place, fixed now at least the best we can do, lets see what kind of impact it will have.

**Comment by soulgalore** [comment]
The way I would fix this is to add a custom --injectJs to that page that actually blacks out the carousel element. Seem more and more people using this approach to "black out" ads so you do not measure them in the visual metrics.
